version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    target-branch: main

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Zagreb
    open-pull-requests-limit: 5
    target-branch: main
