const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const ALLOWED_CASE_STATUS=new Set(['submitted','in_review','waiting_consumer','approved','rejected','repair','replacement','refund','resolved','closed']);
const DECISION_STATUS={accepted:'approved',need_more_info:'waiting_consumer',bring_to_store:'in_review',repair:'repair',replacement:'replacement',refund:'refund',rejected:'rejected',other:'in_review'};
const enc=new TextEncoder();
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}})}
function id(prefix=''){return prefix+crypto.randomUUID().replaceAll('-','')}
function publicId(){const a=new Uint8Array(6);crypto.getRandomValues(a);return 'ST-'+[...a].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
function now(){return new Date().toISOString()}
function clean(v,n=500){return typeof v==='string'?v.trim().slice(0,n):''}
function email(v){const x=clean(v,254).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:''}
function date(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:''}
async function sha(v){const b=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(req){try{return await req.json()}catch{return null}}
function bearer(req){const h=req.headers.get('authorization')||'';return h.startsWith('Bearer ')?h.slice(7).trim():''}
async function merchant(req,env){const token=bearer(req);if(!token)return null;const hash=await sha(token);const row=await env.DB.prepare(`SELECT t.id token_id,t.organization_id,t.member_id,m.role,o.name organization_name,o.status organization_status FROM merchant_api_tokens t LEFT JOIN merchant_members m ON m.id=t.member_id JOIN merchant_organizations o ON o.id=t.organization_id WHERE t.token_hash=? AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at>?) AND (m.status IS NULL OR m.status='active')`).bind(hash,now()).first();if(!row||row.organization_status!=='verified')return null;env.DB.prepare('UPDATE merchant_api_tokens SET last_used_at=? WHERE id=?').bind(now(),row.token_id).run().catch(()=>{});return row}
async function consumerCase(req,env,publicIdValue){const token=req.headers.get('x-still-case-token')||new URL(req.url).searchParams.get('token')||'';if(!token)return null;const hash=await sha(token);return env.DB.prepare('SELECT * FROM consumer_cases WHERE public_id=? AND consumer_access_hash=?').bind(publicIdValue,hash).first()}
async function event(env,caseId,type,actorType,actorId,payload={}){await env.DB.prepare('INSERT INTO case_events(id,case_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('evt_'),caseId,type,actorType,actorId||null,JSON.stringify(payload),now()).run()}
async function createCase(req,env){const b=await body(req);if(!b)return json({error:'invalid_json'},400);const required={retailerName:clean(b.retailerName,160),countryCode:clean(b.countryCode,2).toLowerCase(),purchaseMode:clean(b.purchaseMode,10),caseType:clean(b.caseType,10),purchaseDate:date(b.purchaseDate),productName:clean(b.productName,200)};if(!required.retailerName||!required.countryCode||!['online','store'].includes(required.purchaseMode)||!['return','warranty'].includes(required.caseType)||!required.purchaseDate||!required.productName)return json({error:'invalid_case'},422);const accessToken=id('case_'),accessHash=await sha(accessToken),caseId=id('c_'),pid=publicId(),ts=now();let org=null;const retailerKey=clean(b.retailerKey,100);if(retailerKey)org=await env.DB.prepare("SELECT id FROM merchant_organizations WHERE retailer_key=? AND country_code=? AND status='verified'").bind(retailerKey,required.countryCode).first();await env.DB.prepare(`INSERT INTO consumer_cases(id,public_id,organization_id,retailer_key,retailer_name,country_code,purchase_mode,case_type,purchase_date,product_name,order_reference,serial_number,consumer_email,issue_summary,requested_resolution,proof_type,official_source_url,still_result,status,consumer_access_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(caseId,pid,org?.id||null,retailerKey||null,required.retailerName,required.countryCode,required.purchaseMode,required.caseType,required.purchaseDate,required.productName,clean(b.orderReference,120)||null,clean(b.serialNumber,120)||null,email(b.consumerEmail)||null,clean(b.issueSummary,3000)||null,clean(b.requestedResolution,500)||null,clean(b.proofType,80)||null,clean(b.officialSourceUrl,1000)||null,clean(b.stillResult,1000)||null,'submitted',accessHash,ts,ts).run();await event(env,caseId,'case_created','consumer',null,{retailerKey,organizationId:org?.id||null});return json({case:{publicId:pid,status:'submitted',retailerConnected:!!org,createdAt:ts},accessToken},201)}
async function getConsumerCase(req,env,pid){const c=await consumerCase(req,env,pid);if(!c)return json({error:'not_found'},404);const messages=await env.DB.prepare("SELECT id,actor_type,message_type,body,created_at FROM case_messages WHERE case_id=? ORDER BY created_at ASC").bind(c.id).all();const decisions=await env.DB.prepare("SELECT id,decision_type,reason,service_reference,proposed_resolution,created_at FROM case_decisions WHERE case_id=? ORDER BY created_at DESC").bind(c.id).all();const resolutions=await env.DB.prepare("SELECT id,decision_id,consumer_status,consumer_note,created_at FROM case_resolutions WHERE case_id=? ORDER BY created_at DESC").bind(c.id).all();return json({case:{publicId:c.public_id,retailerName:c.retailer_name,countryCode:c.country_code,purchaseMode:c.purchase_mode,caseType:c.case_type,purchaseDate:c.purchase_date,productName:c.product_name,issueSummary:c.issue_summary,requestedResolution:c.requested_resolution,status:c.status,createdAt:c.created_at,updatedAt:c.updated_at,resolvedAt:c.resolved_at},messages:messages.results,decisions:decisions.results,resolutions:resolutions.results})}
async function consumerResolve(req,env,pid){const c=await consumerCase(req,env,pid);if(!c)return json({error:'not_found'},404);const b=await body(req),status=clean(b?.status,20);if(!['accepted','declined','completed'].includes(status))return json({error:'invalid_resolution'},422);const ts=now(),rid=id('res_');await env.DB.prepare('INSERT INTO case_resolutions(id,case_id,decision_id,consumer_status,consumer_note,created_at) VALUES(?,?,?,?,?,?)').bind(rid,c.id,clean(b.decisionId,80)||null,status,clean(b.note,2000)||null,ts).run();if(status==='completed')await env.DB.prepare("UPDATE consumer_cases SET status='resolved',resolved_at=?,updated_at=? WHERE id=?").bind(ts,ts,c.id).run();else await env.DB.prepare('UPDATE consumer_cases SET updated_at=? WHERE id=?').bind(ts,c.id).run();await event(env,c.id,'consumer_resolution','consumer',null,{status,decisionId:clean(b.decisionId,80)||null});return json({ok:true,status,updatedAt:ts})}
async function merchantList(req,env,auth){const u=new URL(req.url),status=clean(u.searchParams.get('status'),30),q=clean(u.searchParams.get('q'),100);let sql='SELECT public_id,retailer_name,case_type,product_name,status,created_at,updated_at FROM consumer_cases WHERE organization_id=?',args=[auth.organization_id];if(status&&ALLOWED_CASE_STATUS.has(status)){sql+=' AND status=?';args.push(status)}if(q){sql+=' AND (public_id LIKE ? OR product_name LIKE ? OR retailer_name LIKE ?)';const x=`%${q}%`;args.push(x,x,x)}sql+=' ORDER BY updated_at DESC LIMIT 100';const rows=await env.DB.prepare(sql).bind(...args).all();return json({organization:{name:auth.organization_name},cases:rows.results})}
async function merchantGet(env,auth,pid){const c=await env.DB.prepare('SELECT * FROM consumer_cases WHERE public_id=? AND organization_id=?').bind(pid,auth.organization_id).first();if(!c)return json({error:'not_found'},404);await env.DB.prepare('UPDATE consumer_cases SET merchant_last_viewed_at=? WHERE id=?').bind(now(),c.id).run();const messages=await env.DB.prepare('SELECT id,actor_type,message_type,body,created_at FROM case_messages WHERE case_id=? ORDER BY created_at ASC').bind(c.id).all();const decisions=await env.DB.prepare('SELECT id,decision_type,reason,service_reference,proposed_resolution,created_at FROM case_decisions WHERE case_id=? ORDER BY created_at DESC').bind(c.id).all();return json({case:c,messages:messages.results,decisions:decisions.results})}
async function merchantDecision(req,env,auth,pid){const c=await env.DB.prepare('SELECT id FROM consumer_cases WHERE public_id=? AND organization_id=?').bind(pid,auth.organization_id).first();if(!c)return json({error:'not_found'},404);const b=await body(req),decision=clean(b?.decision,30);if(!(decision in DECISION_STATUS))return json({error:'invalid_decision'},422);const ts=now(),did=id('dec_'),status=DECISION_STATUS[decision];await env.DB.prepare('INSERT INTO case_decisions(id,case_id,organization_id,decision_type,reason,service_reference,proposed_resolution,created_by_member_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(did,c.id,auth.organization_id,decision,clean(b.reason,3000)||null,clean(b.serviceReference,120)||null,clean(b.proposedResolution,2000)||null,auth.member_id||null,ts).run();await env.DB.prepare('UPDATE consumer_cases SET status=?,updated_at=? WHERE id=?').bind(status,ts,c.id).run();await event(env,c.id,'merchant_decision','merchant',auth.member_id||null,{decision,status,decisionId:did});return json({ok:true,decisionId:did,status,updatedAt:ts})}
async function merchantMessage(req,env,auth,pid){const c=await env.DB.prepare('SELECT id FROM consumer_cases WHERE public_id=? AND organization_id=?').bind(pid,auth.organization_id).first();if(!c)return json({error:'not_found'},404);const b=await body(req),text=clean(b?.body,5000),type=clean(b?.type,30)||'note';if(!text||!['note','request_info'].includes(type))return json({error:'invalid_message'},422);const ts=now();await env.DB.prepare('INSERT INTO case_messages(id,case_id,actor_type,actor_member_id,message_type,body,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('msg_'),c.id,'merchant',auth.member_id||null,type,text,ts).run();if(type==='request_info')await env.DB.prepare("UPDATE consumer_cases SET status='waiting_consumer',updated_at=? WHERE id=?").bind(ts,c.id).run();await event(env,c.id,'merchant_message','merchant',auth.member_id||null,{type});return json({ok:true,updatedAt:ts})}
async function profile(env,auth){const row=await env.DB.prepare('SELECT o.id,o.slug,o.name,o.country_code,o.retailer_key,o.website_url,o.support_email,o.status,p.returns_summary,p.warranty_summary,p.returns_url,p.warranty_url,p.complaint_url,p.return_address,p.required_evidence_json,p.verified_at,p.updated_at FROM merchant_organizations o LEFT JOIN merchant_profiles p ON p.organization_id=o.id WHERE o.id=?').bind(auth.organization_id).first();return json({profile:row})}
async function api(req,env){const u=new URL(req.url),p=u.pathname,method=req.method;if(method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':u.origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-still-case-token'}});if(p==='/api/v1/health')return json({ok:true,service:'still-merchant-api'});if(p==='/api/v1/cases'&&method==='POST')return createCase(req,env);let m=p.match(/^\/api\/v1\/cases\/([^/]+)$/);if(m&&method==='GET')return getConsumerCase(req,env,m[1]);m=p.match(/^\/api\/v1\/cases\/([^/]+)\/resolution$/);if(m&&method==='POST')return consumerResolve(req,env,m[1]);const auth=await merchant(req,env);if(!auth)return json({error:'unauthorized'},401,{'www-authenticate':'Bearer'});if(p==='/api/v1/merchant/cases'&&method==='GET')return merchantList(req,env,auth);if(p==='/api/v1/merchant/profile'&&method==='GET')return profile(env,auth);m=p.match(/^\/api\/v1\/merchant\/cases\/([^/]+)$/);if(m&&method==='GET')return merchantGet(env,auth,m[1]);m=p.match(/^\/api\/v1\/merchant\/cases\/([^/]+)\/decision$/);if(m&&method==='POST')return merchantDecision(req,env,auth,m[1]);m=p.match(/^\/api\/v1\/merchant\/cases\/([^/]+)\/messages$/);if(m&&method==='POST')return merchantMessage(req,env,auth,m[1]);return json({error:'not_found'},404)}
export default {async fetch(req,env){try{const u=new URL(req.url);if(u.pathname.startsWith('/api/')){if(!env.DB)return json({error:'database_not_configured'},503);return await api(req,env)}return env.ASSETS.fetch(req)}catch(e){console.error(e);return json({error:'internal_error'},500)}}};
