import app from './worker-v133.js';

const HEADERS = { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'x-content-type-options': 'nosniff' };
const NEED_TYPES = new Set(['REPAIR','REPLACE','BUY','SELL','SERVICE','HIRE','LEARN','DECIDE','FOLLOW_UP','RENEW','MAINTAIN','FIND','BOOK','BORROW','RENT','OTHER']);
const NEED_STATUSES = new Set(['DETECTED','NEEDS_CONFIRMATION','ACTIVE','HANDLING','WAITING','RESOLVED','DISMISSED','CANCELLED']);
const ACTIVE_STATUSES = ['DETECTED','NEEDS_CONFIRMATION','ACTIVE','HANDLING','WAITING'];
const SOURCES = new Set(['USER_CREATED','SITUATION_DERIVED','OPEN_LOOP_DERIVED','DATE_RULE','THING_LIFECYCLE','RECEIPT_DERIVED','DOCUMENT_DERIVED','AI_INFERRED']);
const URGENCIES = new Set(['LOW','NORMAL','HIGH','URGENT']);
const CONFIDENCES = new Set(['LOW','MEDIUM','HIGH','CONFIRMED']);
const LINK_TYPES = new Set(['thing','situation','knowledge','open_loop','receipt','document']);
const RESOLUTION_TYPES = new Set(['KEEP','DO_IT','LEARN','REPAIR','REPLACE','BUY','SELL','HIRE','BORROW','RENT','WAIT','OTHER']);
const now = () => new Date().toISOString();
const clean = (value, max = 5000) => String(value ?? '').replace(/\0/g, '').trim().slice(0, max);
const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers: { ...HEADERS, ...headers } });
const safeJson = (value, fallback = {}) => { try { return JSON.parse(value || ''); } catch { return fallback; } };
const has = (object, key) => Object.prototype.hasOwnProperty.call(object || {}, key);
const uid = prefix => `${prefix}${crypto.randomUUID().replaceAll('-', '')}`;
const publicId = prefix => `${prefix}-${crypto.randomUUID().replaceAll('-', '').slice(0, 16).toUpperCase()}`;
const normalized = value => clean(value, 180).toLocaleLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, ' ').trim();
const safeDate = value => { const input = clean(value, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(input)) return null; const date = new Date(`${input}T00:00:00Z`); return Number.isNaN(date.valueOf()) || date.toISOString().slice(0,10) !== input ? null : input; };
const safeUrl = value => { try { const url = new URL(clean(value, 1000)); return url.protocol === 'https:' ? url.href : null; } catch { return null; } };
const cents = value => { const number = Number(value); return Number.isInteger(number) && number >= 0 && number <= 1_000_000_000 ? number : null; };
const currency = value => /^[A-Z]{3}$/.test(clean(value, 3).toUpperCase()) ? clean(value, 3).toUpperCase() : 'EUR';

function log(event, fields = {}) { console.log(JSON.stringify({ scope: 'still_resolution', event, at: now(), ...fields })); }
async function sha(value) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(String(value))); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2,'0')).join(''); }
function cookie(request, name) { for (const part of (request.headers.get('cookie') || '').split(';')) { const [key, ...value] = part.trim().split('='); if (key === name) return decodeURIComponent(value.join('=')); } return ''; }
async function buyerSession(request, env) { const token = cookie(request, 'still_buyer'); if (!token || !env.DB) return null; return env.DB.prepare(`SELECT a.id buyer_account_id,a.email,a.name FROM buyer_sessions s JOIN buyer_accounts a ON a.id=s.buyer_account_id WHERE s.token_hash=? AND s.expires_at>? AND a.status='active'`).bind(await sha(token), now()).first(); }
function sameOrigin(request) { const origin = request.headers.get('origin'); return !origin || origin === new URL(request.url).origin; }
function rewrite(request, pathname, init = {}) { const url = new URL(request.url); url.pathname = pathname; url.search = ''; return new Request(url, { method: init.method || 'GET', headers: init.headers || request.headers, body: init.body }); }
async function delegatedJson(request, env, ctx, pathname) { const response = await app.fetch(rewrite(request, pathname), env, ctx); return { response, data: await response.clone().json().catch(() => ({})) }; }

let schemaReady = false;
async function ensureSchema(env) {
  if (schemaReady) return;
  const statements = [
    `CREATE TABLE IF NOT EXISTS world_needs(id TEXT PRIMARY KEY,public_id TEXT NOT NULL UNIQUE,buyer_account_id TEXT NOT NULL,title TEXT NOT NULL,normalized_title TEXT NOT NULL,description TEXT,need_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',source_type TEXT NOT NULL,source_entity_type TEXT,source_entity_public_id TEXT,situation_id TEXT,thing_passport_id TEXT,urgency TEXT NOT NULL DEFAULT 'NORMAL',confidence TEXT NOT NULL DEFAULT 'CONFIRMED',due_at TEXT,desired_outcome TEXT,budget_min_cents INTEGER,budget_max_cents INTEGER,currency TEXT,deadline TEXT,location_mode TEXT,required_capabilities_json TEXT NOT NULL DEFAULT '[]',category TEXT,desired_attributes_json TEXT NOT NULL DEFAULT '[]',condition_preference TEXT,external_url TEXT,problem_description TEXT,shareable_brief_json TEXT NOT NULL DEFAULT '{}',detected_at TEXT NOT NULL,confirmed_at TEXT,handling_at TEXT,waiting_on TEXT,waiting_until TEXT,resolved_at TEXT,dismissed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS world_need_links(id TEXT PRIMARY KEY,public_id TEXT NOT NULL UNIQUE,buyer_account_id TEXT NOT NULL,need_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_public_id TEXT NOT NULL,relationship TEXT NOT NULL DEFAULT 'context',created_at TEXT NOT NULL,UNIQUE(buyer_account_id,need_id,entity_type,entity_public_id,relationship))`,
    `CREATE TABLE IF NOT EXISTS world_need_quotes(id TEXT PRIMARY KEY,public_id TEXT NOT NULL UNIQUE,buyer_account_id TEXT NOT NULL,need_id TEXT NOT NULL,provider_name TEXT NOT NULL,amount_cents INTEGER NOT NULL,currency TEXT NOT NULL,description TEXT,notes TEXT,document_id TEXT,valid_until TEXT,selected_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS world_resolution_outcomes(id TEXT PRIMARY KEY,public_id TEXT NOT NULL UNIQUE,buyer_account_id TEXT NOT NULL,need_id TEXT NOT NULL,resolution_type TEXT NOT NULL,summary TEXT NOT NULL,cost_cents INTEGER,currency TEXT,related_thing_passport_id TEXT,selected_quote_id TEXT,provider_name TEXT,feedback TEXT,resolved_at TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
    `CREATE INDEX IF NOT EXISTS idx_world_needs_owner ON world_needs(buyer_account_id,status,due_at,updated_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_world_needs_context ON world_needs(buyer_account_id,thing_passport_id,situation_id,status)`,
    `CREATE INDEX IF NOT EXISTS idx_world_needs_duplicate ON world_needs(buyer_account_id,normalized_title,need_type,status)`,
    `CREATE INDEX IF NOT EXISTS idx_world_need_links_owner ON world_need_links(buyer_account_id,need_id,entity_type)`,
    `CREATE INDEX IF NOT EXISTS idx_world_need_quotes_owner ON world_need_quotes(buyer_account_id,need_id,created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_world_outcomes_owner ON world_resolution_outcomes(buyer_account_id,need_id,resolved_at DESC)`
  ];
  await env.DB.batch(statements.map(sql => env.DB.prepare(sql))); schemaReady = true;
}

function historyStatement(env, buyerId, type, entityId, eventType, title, details = {}, sourceType = 'user', sourceId = null) {
  const timestamp = now(); return env.DB.prepare(`INSERT INTO world_history_events(id,public_id,buyer_account_id,entity_type,entity_public_id,event_type,title,details_json,source_type,source_public_id,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid('whe_'), publicId('HIS'), buyerId, type, entityId, eventType, title, JSON.stringify(details).slice(0,4000), sourceType, sourceId, timestamp, timestamp);
}

const NEED_SELECT = `SELECT n.*,p.public_id thing_public_id,p.title thing_title,s.public_id situation_public_id,s.title situation_title FROM world_needs n LEFT JOIN ownership_passports p ON p.id=n.thing_passport_id LEFT JOIN world_situations s ON s.id=n.situation_id`;
async function needForOwner(env, buyerId, id) { return env.DB.prepare(`${NEED_SELECT} WHERE n.buyer_account_id=? AND n.public_id=?`).bind(buyerId,id).first(); }
function needJson(row) { return { publicId:row.public_id,title:row.title,description:row.description||null,type:row.need_type,status:row.status,sourceType:row.source_type,sourceEntityType:row.source_entity_type||null,sourceEntityId:row.source_entity_public_id||null,situationId:row.situation_public_id||null,situationTitle:row.situation_title||null,thingId:row.thing_public_id||null,thingTitle:row.thing_title||null,urgency:row.urgency,confidence:row.confidence,dueAt:row.due_at||null,desiredOutcome:row.desired_outcome||null,budgetMinCents:row.budget_min_cents,budgetMaxCents:row.budget_max_cents,currency:row.currency||null,deadline:row.deadline||null,locationMode:row.location_mode||null,requiredCapabilities:safeJson(row.required_capabilities_json,[]),category:row.category||null,desiredAttributes:safeJson(row.desired_attributes_json,[]),conditionPreference:row.condition_preference||null,externalUrl:row.external_url||null,problemDescription:row.problem_description||null,detectedAt:row.detected_at,confirmedAt:row.confirmed_at||null,handlingAt:row.handling_at||null,waitingOn:row.waiting_on||null,waitingUntil:row.waiting_until||null,resolvedAt:row.resolved_at||null,dismissedAt:row.dismissed_at||null,createdAt:row.created_at,updatedAt:row.updated_at}; }
function quoteJson(row) { return { publicId:row.public_id,needId:row.need_public_id,providerName:row.provider_name,amountCents:row.amount_cents,currency:row.currency,description:row.description||null,notes:row.notes||null,documentId:row.document_public_id||null,validUntil:row.valid_until||null,selectedAt:row.selected_at||null,createdAt:row.created_at,updatedAt:row.updated_at }; }
function outcomeJson(row) { return { publicId:row.public_id,needId:row.need_public_id,resolutionType:row.resolution_type,summary:row.summary,costCents:row.cost_cents,currency:row.currency||null,relatedThingId:row.thing_public_id||null,selectedQuoteId:row.quote_public_id||null,providerName:row.provider_name||null,feedback:row.feedback||null,resolvedAt:row.resolved_at,createdAt:row.created_at }; }

async function entityForOwner(env,buyerId,type,id) {
  if(type==='thing')return env.DB.prepare(`SELECT id,public_id,title FROM ownership_passports WHERE buyer_account_id=? AND public_id=? AND status<>'archived'`).bind(buyerId,id).first();
  if(type==='situation')return env.DB.prepare(`SELECT id,public_id,title FROM world_situations WHERE buyer_account_id=? AND public_id=? AND archived_at IS NULL`).bind(buyerId,id).first();
  if(type==='knowledge')return env.DB.prepare(`SELECT id,public_id,title FROM world_knowledge_items WHERE buyer_account_id=? AND public_id=? AND status='ACTIVE'`).bind(buyerId,id).first();
  if(type==='open_loop')return env.DB.prepare(`SELECT id,public_id,title FROM world_open_loops WHERE buyer_account_id=? AND public_id=?`).bind(buyerId,id).first();
  if(type==='receipt')return env.DB.prepare(`SELECT id,public_id,COALESCE(merchant,'Receipt') title FROM world_receipts WHERE buyer_account_id=? AND public_id=? AND archived_at IS NULL`).bind(buyerId,id).first();
  if(type==='document')return env.DB.prepare(`SELECT id,public_id,title FROM world_documents WHERE buyer_account_id=? AND public_id=? AND archived_at IS NULL`).bind(buyerId,id).first();
  return null;
}

async function resolveLinks(env,buyerId,body) {
  const thing = clean(body.thingId,40) ? await entityForOwner(env,buyerId,'thing',clean(body.thingId,40)) : null;
  const situation = clean(body.situationId,40) ? await entityForOwner(env,buyerId,'situation',clean(body.situationId,40)) : null;
  if(clean(body.thingId,40)&&!thing)return{error:'thing_not_found'}; if(clean(body.situationId,40)&&!situation)return{error:'situation_not_found'};
  return {thing,situation};
}

function parseNeedInput(body,current={}) {
  const typeCandidate=clean(has(body,'needType')?body.needType:current.need_type,30).toUpperCase();
  const statusCandidate=clean(has(body,'status')?body.status:current.status,30).toUpperCase();
  const sourceCandidate=clean(has(body,'sourceType')?body.sourceType:current.source_type,40).toUpperCase();
  const urgencyCandidate=clean(has(body,'urgency')?body.urgency:current.urgency,20).toUpperCase();
  const confidenceCandidate=clean(has(body,'confidence')?body.confidence:current.confidence,20).toUpperCase();
  const title=clean(has(body,'title')?body.title:current.title,180);
  return { title, normalizedTitle:normalized(title), description:clean(has(body,'description')?body.description:current.description,5000)||null, type:NEED_TYPES.has(typeCandidate)?typeCandidate:'OTHER', status:NEED_STATUSES.has(statusCandidate)?statusCandidate:'ACTIVE', source:SOURCES.has(sourceCandidate)?sourceCandidate:'USER_CREATED', urgency:URGENCIES.has(urgencyCandidate)?urgencyCandidate:'NORMAL', confidence:CONFIDENCES.has(confidenceCandidate)?confidenceCandidate:'CONFIRMED', dueAt:safeDate(has(body,'dueAt')?body.dueAt:current.due_at), desiredOutcome:clean(has(body,'desiredOutcome')?body.desiredOutcome:current.desired_outcome,1000)||null, budgetMin:cents(has(body,'budgetMinCents')?body.budgetMinCents:current.budget_min_cents), budgetMax:cents(has(body,'budgetMaxCents')?body.budgetMaxCents:current.budget_max_cents), currency:currency(has(body,'currency')?body.currency:current.currency), deadline:safeDate(has(body,'deadline')?body.deadline:current.deadline), locationMode:clean(has(body,'locationMode')?body.locationMode:current.location_mode,60)||null, requiredCapabilities:Array.isArray(body.requiredCapabilities)?body.requiredCapabilities.map(x=>clean(x,100)).filter(Boolean).slice(0,30):safeJson(current.required_capabilities_json,[]), category:clean(has(body,'category')?body.category:current.category,120)||null, desiredAttributes:Array.isArray(body.desiredAttributes)?body.desiredAttributes.map(x=>clean(x,120)).filter(Boolean).slice(0,30):safeJson(current.desired_attributes_json,[]), conditionPreference:clean(has(body,'conditionPreference')?body.conditionPreference:current.condition_preference,80)||null, externalUrl:has(body,'externalUrl')?(clean(body.externalUrl)?safeUrl(body.externalUrl):null):(current.external_url||null), problemDescription:clean(has(body,'problemDescription')?body.problemDescription:current.problem_description,3000)||null };
}

async function duplicateNeeds(env,buyerId,input,links) {
  const result=await env.DB.prepare(`${NEED_SELECT} WHERE n.buyer_account_id=? AND n.status IN ('DETECTED','NEEDS_CONFIRMATION','ACTIVE','HANDLING','WAITING') AND (n.normalized_title=? OR (n.need_type=? AND ((n.thing_passport_id IS NOT NULL AND n.thing_passport_id=?) OR (n.situation_id IS NOT NULL AND n.situation_id=?)))) ORDER BY n.updated_at DESC LIMIT 10`).bind(buyerId,input.normalizedTitle,input.type,links.thing?.id||'',links.situation?.id||'').all();
  return (result.results||[]).map(needJson);
}

async function createNeed(request,env,buyer) {
  const body=await request.json().catch(()=>null); if(!body)return json({error:'invalid_json'},400);
  const input=parseNeedInput(body); if(input.title.length<2)return json({error:'title_required'},422);
  if(has(body,'externalUrl')&&clean(body.externalUrl)&&!input.externalUrl)return json({error:'external_url_must_be_https'},422);
  const links=await resolveLinks(env,buyer.buyer_account_id,body); if(links.error)return json({error:links.error},404);
  const duplicates=await duplicateNeeds(env,buyer.buyer_account_id,input,links); if(duplicates.length&&!body.allowDuplicate)return json({error:'duplicate_need_review_required',matches:duplicates},409);
  const timestamp=now(),internal=uid('wnd_'),pid=publicId('NED');
  const requestedStatus=['DETECTED','NEEDS_CONFIRMATION','ACTIVE'].includes(input.status)?input.status:'ACTIVE';
  const status=input.confidence==='LOW'?'NEEDS_CONFIRMATION':requestedStatus,confirmedAt=input.confidence==='CONFIRMED'?timestamp:null;
  const statements=[env.DB.prepare(`INSERT INTO world_needs(id,public_id,buyer_account_id,title,normalized_title,description,need_type,status,source_type,source_entity_type,source_entity_public_id,situation_id,thing_passport_id,urgency,confidence,due_at,desired_outcome,budget_min_cents,budget_max_cents,currency,deadline,location_mode,required_capabilities_json,category,desired_attributes_json,condition_preference,external_url,problem_description,shareable_brief_json,detected_at,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(internal,pid,buyer.buyer_account_id,input.title,input.normalizedTitle,input.description,input.type,status,input.source,clean(body.sourceEntityType,30)||null,clean(body.sourceEntityId,40)||null,links.situation?.id||null,links.thing?.id||null,input.urgency,input.confidence,input.dueAt,input.desiredOutcome,input.budgetMin,input.budgetMax,input.currency,input.deadline,input.locationMode,JSON.stringify(input.requiredCapabilities),input.category,JSON.stringify(input.desiredAttributes),input.conditionPreference,input.externalUrl,input.problemDescription,'{}',timestamp,confirmedAt,timestamp,timestamp),historyStatement(env,buyer.buyer_account_id,'need',pid,'need.created','Need created',{type:input.type,source:input.source,confidence:input.confidence},'user',buyer.buyer_account_id)];
  for(const [type,key] of [['knowledge','knowledgeId'],['open_loop','openLoopId'],['receipt','receiptId'],['document','documentId']]){const id=clean(body[key],40);if(!id)continue;const entity=await entityForOwner(env,buyer.buyer_account_id,type,id);if(!entity)return json({error:`${type}_not_found`},404);statements.push(env.DB.prepare(`INSERT OR IGNORE INTO world_need_links(id,public_id,buyer_account_id,need_id,entity_type,entity_public_id,relationship,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(uid('wnl_'),publicId('NLK'),buyer.buyer_account_id,internal,type,id,'context',timestamp));}
  await env.DB.batch(statements); log('need_created',{buyerId:buyer.buyer_account_id,needId:pid,type:input.type,source:input.source});
  return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,pid))},201);
}

async function listNeeds(env,buyer,url) {
  const filter=clean(url.searchParams.get('status'),30).toUpperCase(); let sql=`${NEED_SELECT} WHERE n.buyer_account_id=?`,args=[buyer.buyer_account_id];
  if(filter==='OPEN')sql+=` AND n.status IN ('DETECTED','NEEDS_CONFIRMATION','ACTIVE','HANDLING')`;else if(filter==='WAITING')sql+=` AND n.status='WAITING'`;else if(filter==='RESOLVED')sql+=` AND n.status='RESOLVED'`;else if(NEED_STATUSES.has(filter)){sql+=` AND n.status=?`;args.push(filter);}
  sql+=` ORDER BY CASE n.urgency WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,n.due_at IS NULL,n.due_at,n.updated_at DESC LIMIT 300`;
  const rows=await env.DB.prepare(sql).bind(...args).all();return json({needs:(rows.results||[]).map(needJson)});
}

async function patchNeed(request,env,buyer,id) {
  const current=await needForOwner(env,buyer.buyer_account_id,id);if(!current)return json({error:'not_found'},404);if(['RESOLVED','DISMISSED','CANCELLED'].includes(current.status))return json({error:'need_not_editable'},409);
  const body=await request.json().catch(()=>null);if(!body)return json({error:'invalid_json'},400);const input=parseNeedInput(body,current);if(input.title.length<2)return json({error:'title_required'},422);
  const links=await resolveLinks(env,buyer.buyer_account_id,{thingId:has(body,'thingId')?body.thingId:current.thing_public_id,situationId:has(body,'situationId')?body.situationId:current.situation_public_id});if(links.error)return json({error:links.error},404);
  const timestamp=now();await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET title=?,normalized_title=?,description=?,need_type=?,situation_id=?,thing_passport_id=?,urgency=?,due_at=?,desired_outcome=?,budget_min_cents=?,budget_max_cents=?,currency=?,deadline=?,location_mode=?,required_capabilities_json=?,category=?,desired_attributes_json=?,condition_preference=?,external_url=?,problem_description=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(input.title,input.normalizedTitle,input.description,input.type,links.situation?.id||null,links.thing?.id||null,input.urgency,input.dueAt,input.desiredOutcome,input.budgetMin,input.budgetMax,input.currency,input.deadline,input.locationMode,JSON.stringify(input.requiredCapabilities),input.category,JSON.stringify(input.desiredAttributes),input.conditionPreference,input.externalUrl,input.problemDescription,timestamp,current.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'need.updated','Need updated',{type:input.type},'user',buyer.buyer_account_id)]);return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,id))});
}

async function transitionNeed(env,buyer,id,action,body={}) {
  const current=await needForOwner(env,buyer.buyer_account_id,id);if(!current)return json({error:'not_found'},404);const timestamp=now();
  if(action==='confirm'){if(current.status!=='NEEDS_CONFIRMATION'&&current.status!=='DETECTED')return json({error:'invalid_status_transition'},409);await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET status='ACTIVE',confidence='CONFIRMED',confirmed_at=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,timestamp,current.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'need.confirmed','Need confirmed',{},'user',buyer.buyer_account_id)]);log('need_confirmed',{buyerId:buyer.buyer_account_id,needId:id});}
  if(action==='wait'){if(!['ACTIVE','HANDLING'].includes(current.status))return json({error:'invalid_status_transition'},409);const waitingOn=clean(body.waitingOn,500),waitingUntil=safeDate(body.waitingUntil);if(waitingOn.length<2)return json({error:'waiting_on_required'},422);await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET status='WAITING',waiting_on=?,waiting_until=?,handling_at=COALESCE(handling_at,?),updated_at=? WHERE id=? AND buyer_account_id=?`).bind(waitingOn,waitingUntil,timestamp,timestamp,current.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'need.waiting','Need is waiting',{waitingOn,waitingUntil},'user',buyer.buyer_account_id)]);log('need_waiting',{buyerId:buyer.buyer_account_id,needId:id,hasDate:Boolean(waitingUntil)});}
  if(action==='resume'){if(current.status!=='WAITING')return json({error:'invalid_status_transition'},409);await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET status='ACTIVE',waiting_on=NULL,waiting_until=NULL,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,current.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'need.resumed','Need resumed',{},'user',buyer.buyer_account_id)]);log('need_resumed',{buyerId:buyer.buyer_account_id,needId:id});}
  if(action==='dismiss'){if(!ACTIVE_STATUSES.includes(current.status))return json({error:'invalid_status_transition'},409);await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET status='DISMISSED',dismissed_at=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,timestamp,current.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'need.dismissed','Need dismissed',{},'user',buyer.buyer_account_id)]);log('need_dismissed',{buyerId:buyer.buyer_account_id,needId:id});}
  if(action==='resolve')return resolveNeed(env,buyer,current,body);
  return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,id))});
}

async function quotesForNeed(env,buyerId,needInternalId) { const rows=await env.DB.prepare(`SELECT q.*,n.public_id need_public_id,d.public_id document_public_id FROM world_need_quotes q JOIN world_needs n ON n.id=q.need_id LEFT JOIN world_documents d ON d.id=q.document_id WHERE q.buyer_account_id=? AND q.need_id=? ORDER BY q.amount_cents,q.created_at`).bind(buyerId,needInternalId).all();return (rows.results||[]).map(quoteJson); }
async function outcomesForNeed(env,buyerId,needInternalId) { const rows=await env.DB.prepare(`SELECT o.*,n.public_id need_public_id,p.public_id thing_public_id,q.public_id quote_public_id FROM world_resolution_outcomes o JOIN world_needs n ON n.id=o.need_id LEFT JOIN ownership_passports p ON p.id=o.related_thing_passport_id LEFT JOIN world_need_quotes q ON q.id=o.selected_quote_id WHERE o.buyer_account_id=? AND o.need_id=? ORDER BY o.resolved_at DESC`).bind(buyerId,needInternalId).all();return (rows.results||[]).map(outcomeJson); }

async function addQuote(request,env,buyer,needId) {
  const need=await needForOwner(env,buyer.buyer_account_id,needId);if(!need)return json({error:'not_found'},404);if(!ACTIVE_STATUSES.includes(need.status))return json({error:'need_not_active'},409);
  const body=await request.json().catch(()=>null);if(!body)return json({error:'invalid_json'},400);const provider=clean(body.providerName,180),amount=cents(body.amountCents);if(provider.length<2||amount===null)return json({error:'quote_provider_and_amount_required'},422);
  let document=null;const documentId=clean(body.documentId,40);if(documentId){document=await entityForOwner(env,buyer.buyer_account_id,'document',documentId);if(!document)return json({error:'document_not_found'},404);}
  const timestamp=now(),pid=publicId('QTE');await env.DB.batch([env.DB.prepare(`INSERT INTO world_need_quotes(id,public_id,buyer_account_id,need_id,provider_name,amount_cents,currency,description,notes,document_id,valid_until,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uid('wnq_'),pid,buyer.buyer_account_id,need.id,provider,amount,currency(body.currency),clean(body.description,2000)||null,clean(body.notes,2000)||null,document?.id||null,safeDate(body.validUntil),timestamp,timestamp),historyStatement(env,buyer.buyer_account_id,'need',needId,'quote.added','Quote added',{quoteId:pid,amountCents:amount,currency:currency(body.currency)},'quote',pid)]);log('quote_added',{buyerId:buyer.buyer_account_id,needId,quoteId:pid,amountCents:amount,currency:currency(body.currency)});return json({ok:true,quotes:await quotesForNeed(env,buyer.buyer_account_id,need.id)},201);
}

async function selectQuote(env,buyer,needId,quoteId) {
  const need=await needForOwner(env,buyer.buyer_account_id,needId);if(!need)return json({error:'not_found'},404);const quote=await env.DB.prepare(`SELECT * FROM world_need_quotes WHERE buyer_account_id=? AND need_id=? AND public_id=?`).bind(buyer.buyer_account_id,need.id,quoteId).first();if(!quote)return json({error:'quote_not_found'},404);
  const timestamp=now();await env.DB.batch([env.DB.prepare(`UPDATE world_need_quotes SET selected_at=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,timestamp,quote.id,buyer.buyer_account_id),env.DB.prepare(`UPDATE world_needs SET status='HANDLING',handling_at=COALESCE(handling_at,?),updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,timestamp,need.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',needId,'resolution.selected','Quote selected',{quoteId},'quote',quoteId)]);log('resolution_selected',{buyerId:buyer.buyer_account_id,needId,optionType:'QUOTE'});return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,needId)),quotes:await quotesForNeed(env,buyer.buyer_account_id,need.id)});
}

function words(value){const stop=new Set(['need','needs','want','find','help','with','this','that','someone','something','trebam','treba','zelim','želim','pronaći','pomoc','pomoć','repair','buy','hire','learn','replace']);return normalized(value).split(' ').filter(word=>word.length>=3&&!stop.has(word));}
function scoreMatch(need,item){const wanted=new Set([...words(need.title),...words(need.category),...words(need.desired_outcome)]),candidate=new Set([...words(item.title),...words(item.category),...words(item.tags_json)]);if(!wanted.size)return 0;let common=0;for(const word of wanted)if(candidate.has(word))common++;return common/wanted.size;}
function option(type,title,description,source,actionType,actionPayload,evidenceRefs=[],limitations=[]){return{type,title,description,source,confidence:'DETERMINISTIC',actionable:Boolean(actionType),actionType:actionType||null,actionPayload:actionPayload||null,evidenceRefs,limitations};}

async function resolutionOptions(env,buyer,need) {
  const [thingsResult,knowledgeResult,linksResult,quotes]=await Promise.all([
    env.DB.prepare(`SELECT p.public_id,p.title,COALESCE(tp.category,'') category FROM ownership_passports p LEFT JOIN world_thing_profiles tp ON tp.passport_id=p.id WHERE p.buyer_account_id=? AND p.status<>'archived' ORDER BY p.updated_at DESC LIMIT 300`).bind(buyer.buyer_account_id).all(),
    env.DB.prepare(`SELECT public_id,title,body,tags_json FROM world_knowledge_items WHERE buyer_account_id=? AND status='ACTIVE' ORDER BY updated_at DESC LIMIT 300`).bind(buyer.buyer_account_id).all(),
    env.DB.prepare(`SELECT * FROM world_need_links WHERE buyer_account_id=? AND need_id=?`).bind(buyer.buyer_account_id,need.id).all(),quotesForNeed(env,buyer.buyer_account_id,need.id)
  ]);
  const links=linksResult.results||[],explicitKnowledge=new Set(links.filter(link=>link.entity_type==='knowledge').map(link=>link.entity_public_id));const options=[];
  if(['BUY','BORROW','RENT','FIND'].includes(need.need_type)){
    const matches=(thingsResult.results||[]).map(item=>({item,score:scoreMatch(need,item)})).filter(match=>match.score>=0.66).sort((a,b)=>b.score-a.score).slice(0,3);
    for(const match of matches)options.push(option('KEEP','You may already have what you need',match.item.title,'WORLD','OPEN_THING',{thingId:match.item.public_id},[{type:'thing',id:match.item.public_id,reason:'Explicit title or category terms match this Need.'}],['Still matched recorded words only; confirm that the Thing is actually suitable.']));
  }
  const knowledge=(knowledgeResult.results||[]).map(item=>({item,score:explicitKnowledge.has(item.public_id)?1:scoreMatch(need,item)})).filter(match=>match.score>=0.66).sort((a,b)=>b.score-a.score).slice(0,4);
  for(const match of knowledge)options.push(option('LEARN','You already saved something that may help',match.item.title,'KNOWLEDGE','OPEN_KNOWLEDGE',{knowledgeId:match.item.public_id},[{type:'knowledge',id:match.item.public_id,reason:explicitKnowledge.has(match.item.public_id)?'Explicitly linked to this Need.':'Recorded title or tag terms match this Need.'}],['Still has not judged whether the content is complete or correct.']));
  if(need.thing_public_id)options.push(option('DO_IT','Review what you already know','Open the Thing Passport, documents and service history.','STILL','OPEN_THING',{thingId:need.thing_public_id},[{type:'thing',id:need.thing_public_id,reason:'This Need is explicitly linked to the Thing.'}]));
  if(['REPAIR','SERVICE','REPLACE','HIRE'].includes(need.need_type))options.push(option(need.need_type==='HIRE'?'HIRE':'REPAIR','Add a real quote','Add a provider quote or attach its private document before comparing.','STILL','ADD_QUOTE',{needId:need.public_id},quotes.length?[{type:'quote',id:quotes[0].publicId,reason:`${quotes.length} quote(s) already recorded.`}]:[],quotes.length?[]:['No provider, price or availability is assumed.']));
  options.push(option('DO_IT','Make the next step explicit','Create an Open Loop linked to this Need and its current context.','STILL','CREATE_OPEN_LOOP',{needId:need.public_id},[{type:'need',id:need.public_id,reason:'Open Loops track pending action without resolving the Need.'}]));
  if(need.external_url)options.push(option('OTHER','Continue externally','Open the HTTPS link you supplied.','EXTERNAL','OPEN_EXTERNAL',{url:need.external_url},[{type:'need',id:need.public_id,reason:'You supplied this external link.'}],['Still protection and availability are not provided. Opening the link does not resolve the Need.']));
  const missing=[];if(['REPAIR','REPLACE'].includes(need.need_type)&&!quotes.length)missing.push('Add a repair quote before comparing repair and replacement costs.');if(need.need_type==='HIRE'&&!need.desired_outcome)missing.push('Describe the outcome you want before comparing external help.');
  log('resolution_options_generated',{buyerId:buyer.buyer_account_id,needId:need.public_id,optionCount:options.length,missingCount:missing.length});return{options,missing,method:'deterministic_world_first'};
}

async function needContext(request,env,ctx,buyer,id) {
  const need=await needForOwner(env,buyer.buyer_account_id,id);if(!need)return json({error:'not_found'},404);
  const [linksResult,quotes,outcomes,historyResult,resolution]=await Promise.all([env.DB.prepare(`SELECT * FROM world_need_links WHERE buyer_account_id=? AND need_id=? ORDER BY created_at`).bind(buyer.buyer_account_id,need.id).all(),quotesForNeed(env,buyer.buyer_account_id,need.id),outcomesForNeed(env,buyer.buyer_account_id,need.id),env.DB.prepare(`SELECT public_id,event_type,title,details_json,source_type,source_public_id,occurred_at FROM world_history_events WHERE buyer_account_id=? AND entity_type='need' AND entity_public_id=? ORDER BY occurred_at DESC LIMIT 100`).bind(buyer.buyer_account_id,id).all(),resolutionOptions(env,buyer,need)]);
  const linked=[];for(const link of linksResult.results||[]){const entity=await entityForOwner(env,buyer.buyer_account_id,link.entity_type,link.entity_public_id);if(entity)linked.push({type:link.entity_type,publicId:entity.public_id,title:entity.title,relationship:link.relationship});}
  let thingContext=null,situationContext=null;if(need.thing_public_id){const result=await delegatedJson(request,env,ctx,`/api/v1/world/context/thing/${encodeURIComponent(need.thing_public_id)}`);if(result.response.ok)thingContext=result.data;}if(need.situation_public_id){const result=await delegatedJson(request,env,ctx,`/api/v1/world/context/situation/${encodeURIComponent(need.situation_public_id)}`);if(result.response.ok)situationContext=result.data;}
  const comparison=quotes.length>1?{lowestCents:Math.min(...quotes.map(q=>q.amountCents)),highestCents:Math.max(...quotes.map(q=>q.amountCents)),differenceCents:Math.max(...quotes.map(q=>q.amountCents))-Math.min(...quotes.map(q=>q.amountCents)),currency:quotes.every(q=>q.currency===quotes[0].currency)?quotes[0].currency:null,note:'Price difference is factual. Still has not ranked provider quality.'}:null;
  return json({need:needJson(need),why:{sourceType:need.source_type,confidence:need.confidence,sourceEntityType:need.source_entity_type||null,sourceEntityId:need.source_entity_public_id||null,explanation:need.source_type==='USER_CREATED'?'You created and confirmed this Need.':'This Need records an explicit source in your World.'},linked,thingContext,situationContext,quotes,quoteComparison:comparison,outcomes,history:(historyResult.results||[]).map(row=>({publicId:row.public_id,eventType:row.event_type,title:row.title,details:safeJson(row.details_json),occurredAt:row.occurred_at})),...resolution});
}

async function selectOption(request,env,ctx,buyer,id) {
  const need=await needForOwner(env,buyer.buyer_account_id,id);if(!need)return json({error:'not_found'},404);const body=await request.json().catch(()=>null);if(!body)return json({error:'invalid_json'},400);const resolution=await resolutionOptions(env,buyer,need),type=clean(body.optionType,30).toUpperCase(),action=clean(body.actionType,40).toUpperCase();const selected=resolution.options.find(option=>option.type===type&&option.actionType===action);if(!selected)return json({error:'option_not_available'},409);
  const timestamp=now();let createdOpenLoop=null;
  if(action==='CREATE_OPEN_LOOP'){const payload={title:clean(body.title,180)||`Next step · ${need.title}`,notes:clean(body.notes,2000)||`Created while handling ${need.public_id}.`,type:'ACTION',status:'OPEN',thingId:need.thing_public_id||undefined,situationId:need.situation_public_id||undefined};const origin=new URL(request.url).origin,headers=new Headers(request.headers);headers.set('content-type','application/json');headers.set('origin',origin);const result=await app.fetch(rewrite(request,'/api/v1/world/open-loops',{method:'POST',headers,body:JSON.stringify(payload)}),env,ctx);const data=await result.json().catch(()=>({}));if(!result.ok)return json({error:'open_loop_creation_failed',details:data.error||null},result.status);createdOpenLoop=data.openLoop;await env.DB.prepare(`INSERT OR IGNORE INTO world_need_links(id,public_id,buyer_account_id,need_id,entity_type,entity_public_id,relationship,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(uid('wnl_'),publicId('NLK'),buyer.buyer_account_id,need.id,'open_loop',createdOpenLoop.publicId,'handling',timestamp).run();}
  const status=action==='START_WAITING'?'WAITING':'HANDLING';await env.DB.batch([env.DB.prepare(`UPDATE world_needs SET status=?,handling_at=COALESCE(handling_at,?),updated_at=? WHERE id=? AND buyer_account_id=?`).bind(status,timestamp,timestamp,need.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',id,'resolution.selected','Resolution step selected',{optionType:type,actionType:action,openLoopId:createdOpenLoop?.publicId||null},'user',buyer.buyer_account_id)]);log('resolution_selected',{buyerId:buyer.buyer_account_id,needId:id,optionType:type,actionType:action});log('need_handling_started',{buyerId:buyer.buyer_account_id,needId:id,status});return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,id)),selectedOption:selected,openLoop:createdOpenLoop});
}

async function resolveNeed(env,buyer,need,body) {
  if(!ACTIVE_STATUSES.includes(need.status))return json({error:'invalid_status_transition'},409);const resolutionType=clean(body.resolutionType,30).toUpperCase();if(!RESOLUTION_TYPES.has(resolutionType))return json({error:'resolution_type_required'},422);const summary=clean(body.summary,2000);if(summary.length<2)return json({error:'resolution_summary_required'},422);
  let quote=null;const quoteId=clean(body.selectedQuoteId,40);if(quoteId){quote=await env.DB.prepare(`SELECT * FROM world_need_quotes WHERE buyer_account_id=? AND need_id=? AND public_id=?`).bind(buyer.buyer_account_id,need.id,quoteId).first();if(!quote)return json({error:'quote_not_found'},404);}
  const cost=has(body,'costCents')?cents(body.costCents):(quote?.amount_cents??null);if(has(body,'costCents')&&cost===null)return json({error:'invalid_cost'},422);const timestamp=now(),outcomeId=uid('wro_'),pid=publicId('OUT'),relatedThing=need.thing_passport_id||null;
  const statements=[env.DB.prepare(`INSERT INTO world_resolution_outcomes(id,public_id,buyer_account_id,need_id,resolution_type,summary,cost_cents,currency,related_thing_passport_id,selected_quote_id,provider_name,resolved_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(outcomeId,pid,buyer.buyer_account_id,need.id,resolutionType,summary,cost,cost===null?null:currency(body.currency||quote?.currency),relatedThing,quote?.id||null,clean(body.providerName,180)||quote?.provider_name||null,timestamp,timestamp,timestamp),env.DB.prepare(`UPDATE world_needs SET status='RESOLVED',resolved_at=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(timestamp,timestamp,need.id,buyer.buyer_account_id),historyStatement(env,buyer.buyer_account_id,'need',need.public_id,'need.resolved','Need resolved',{outcomeId:pid,resolutionType,costCents:cost,currency:cost===null?null:currency(body.currency||quote?.currency)},'outcome',pid)];
  if(relatedThing&&resolutionType==='REPAIR')statements.push(historyStatement(env,buyer.buyer_account_id,'thing',need.thing_public_id,'thing.service_recorded','Repair outcome recorded',{needId:need.public_id,outcomeId:pid,costCents:cost,currency:cost===null?null:currency(body.currency||quote?.currency),providerName:clean(body.providerName,180)||quote?.provider_name||null},'outcome',pid));
  await env.DB.batch(statements);log('need_resolved',{buyerId:buyer.buyer_account_id,needId:need.public_id,outcomeId:pid,resolutionType});return json({ok:true,need:needJson(await needForOwner(env,buyer.buyer_account_id,need.public_id)),outcome:(await outcomesForNeed(env,buyer.buyer_account_id,need.id))[0]});
}

async function feedback(request,env,buyer,outcomeId){const body=await request.json().catch(()=>null),value=clean(body?.feedback,10).toUpperCase();if(!['YES','NO'].includes(value))return json({error:'feedback_must_be_yes_or_no'},422);const row=await env.DB.prepare(`SELECT o.*,n.public_id need_public_id FROM world_resolution_outcomes o JOIN world_needs n ON n.id=o.need_id WHERE o.buyer_account_id=? AND o.public_id=?`).bind(buyer.buyer_account_id,outcomeId).first();if(!row)return json({error:'not_found'},404);await env.DB.prepare(`UPDATE world_resolution_outcomes SET feedback=?,updated_at=? WHERE id=? AND buyer_account_id=?`).bind(value,now(),row.id,buyer.buyer_account_id).run();log('resolution_feedback',{buyerId:buyer.buyer_account_id,needId:row.need_public_id,outcomeId,feedback:value});return json({ok:true,feedback:value});}

function rankNeed(row){const today=new Date().toISOString().slice(0,10),soon=new Date(Date.now()+7*86400000).toISOString().slice(0,10);if(row.due_at&&row.due_at<today)return 0;if(row.urgency==='URGENT')return 1;if(row.urgency==='HIGH')return 2;if(row.due_at&&row.due_at<=soon)return 3;if(row.status==='NEEDS_CONFIRMATION')return 4;if(row.status==='HANDLING'||row.status==='WAITING')return 5;return 6;}
async function needsNow(env,buyer){const result=await env.DB.prepare(`${NEED_SELECT} WHERE n.buyer_account_id=? AND n.status IN ('DETECTED','NEEDS_CONFIRMATION','ACTIVE','HANDLING','WAITING') ORDER BY n.updated_at DESC LIMIT 200`).bind(buyer.buyer_account_id).all();const rows=(result.results||[]).sort((a,b)=>rankNeed(a)-rankNeed(b)||String(a.due_at||'9999').localeCompare(String(b.due_at||'9999'))||String(b.updated_at).localeCompare(String(a.updated_at)));const items=rows.map(needJson);return{dominantNeed:items[0]||null,activeNeedCount:items.length,needsRequiringConfirmation:items.filter(item=>item.status==='NEEDS_CONFIRMATION').slice(0,8),urgentNeeds:items.filter((_,index)=>rankNeed(rows[index])<=3).slice(0,8),recentNeeds:[...items].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,8)};}

function classifyNeed(content){const text=clean(content,5000),value=normalized(text);let type='OTHER';if(/\b(repair|broken|fix|poprav|pokvar|ostecen)\b/.test(value))type='REPAIR';else if(/\b(replace|zamijen|zamjena)\b/.test(value))type='REPLACE';else if(/\b(buy|purchase|kupiti|kupi)\b/.test(value))type='BUY';else if(/\b(hire|someone|professional|fotograf|dizajn)\b/.test(value))type='HIRE';else if(/\b(understand|learn|objasn|razumjeti|nauciti)\b/.test(value))type='LEARN';else if(/\b(decide|whether|odluc|odlučiti)\b/.test(value))type='DECIDE';const explicit=/\b(i need|we need|trebam|treba mi|need someone|needs repair)\b/.test(value),broken=/\b(broken|pokvar|ostecen)\b/.test(value);return(explicit||broken)?{route:'need',confidence:explicit?0.94:0.88,needsConfirmation:true,proposedNeed:{needType:type,title:text.slice(0,180),description:text,confidence:explicit?'CONFIRMED':'HIGH'}}:null;}

async function bootstrapWithNeeds(request,env,ctx,buyer){const result=await delegatedJson(request,env,ctx,'/api/v1/world/bootstrap');if(!result.response.ok)return result.response;const list=await env.DB.prepare(`${NEED_SELECT} WHERE n.buyer_account_id=? AND n.status NOT IN ('DISMISSED','CANCELLED') ORDER BY n.updated_at DESC LIMIT 100`).bind(buyer.buyer_account_id).all();return json({...result.data,needs:(list.results||[]).map(needJson)});}
async function contextWithNeeds(request,env,ctx,buyer,path){const result=await app.fetch(request,env,ctx);if(!result.ok)return result;const data=await result.json(),type=path.split('/')[5],id=decodeURIComponent(path.split('/')[6]);let condition='',value=null;if(type==='thing'){const entity=await entityForOwner(env,buyer.buyer_account_id,'thing',id);if(entity){condition='n.thing_passport_id=?';value=entity.id;}}if(type==='situation'){const entity=await entityForOwner(env,buyer.buyer_account_id,'situation',id);if(entity){condition='n.situation_id=?';value=entity.id;}}if(type==='knowledge'||type==='receipt'||type==='document'||type==='open_loop'){condition=`EXISTS(SELECT 1 FROM world_need_links l WHERE l.buyer_account_id=n.buyer_account_id AND l.need_id=n.id AND l.entity_type=? AND l.entity_public_id=?)`;value=[type,id];}let needs=[];if(condition){const query=env.DB.prepare(`${NEED_SELECT} WHERE n.buyer_account_id=? AND ${condition} ORDER BY n.updated_at DESC LIMIT 100`);const rows=Array.isArray(value)?await query.bind(buyer.buyer_account_id,...value).all():await query.bind(buyer.buyer_account_id,value).all();needs=(rows.results||[]).map(needJson);}return json({...data,needs});}

async function handleNeedApi(request,env,ctx,buyer,url){const path=url.pathname;let match;if(path==='/api/v1/world/needs'&&request.method==='GET')return listNeeds(env,buyer,url);if(path==='/api/v1/world/needs'&&request.method==='POST')return createNeed(request,env,buyer);match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)\/context$/);if(match&&request.method==='GET')return needContext(request,env,ctx,buyer,decodeURIComponent(match[1]));match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)\/quotes$/);if(match&&request.method==='POST')return addQuote(request,env,buyer,decodeURIComponent(match[1]));match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)\/quotes\/([^/]+)\/select$/);if(match&&request.method==='POST')return selectQuote(env,buyer,decodeURIComponent(match[1]),decodeURIComponent(match[2]));match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)\/select$/);if(match&&request.method==='POST')return selectOption(request,env,ctx,buyer,decodeURIComponent(match[1]));match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)\/(confirm|dismiss|wait|resume|resolve)$/);if(match&&request.method==='POST')return transitionNeed(env,buyer,decodeURIComponent(match[1]),match[2],await request.json().catch(()=>({})));match=path.match(/^\/api\/v1\/world\/needs\/([^/]+)$/);if(match&&request.method==='GET'){const row=await needForOwner(env,buyer.buyer_account_id,decodeURIComponent(match[1]));return row?json({need:needJson(row)}):json({error:'not_found'},404);}if(match&&request.method==='PATCH')return patchNeed(request,env,buyer,decodeURIComponent(match[1]));match=path.match(/^\/api\/v1\/world\/resolution-outcomes\/([^/]+)\/feedback$/);if(match&&request.method==='POST')return feedback(request,env,buyer,decodeURIComponent(match[1]));return json({error:'not_found'},404);}

export default { async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname,isNeedApi=path.startsWith('/api/v1/world/needs')||path.startsWith('/api/v1/world/resolution-outcomes');const isPhase3Read=path==='/api/v1/world/now'||path==='/api/v1/world/bootstrap'||path==='/api/v1/world/search'||path.startsWith('/api/v1/world/context/');const isInput=path==='/api/v1/world/input/route'&&request.method==='POST';if(!isNeedApi&&!isPhase3Read&&!isInput)return app.fetch(request,env,ctx);try{const foundation=await delegatedJson(request,env,ctx,'/api/v1/world/history');if(!foundation.response.ok)return foundation.response;await ensureSchema(env);const buyer=await buyerSession(request,env);if(!buyer)return json({error:'unauthorized'},401);if(!['GET','HEAD'].includes(request.method)&&!sameOrigin(request))return json({error:'origin_not_allowed'},403);
  if(isNeedApi)return handleNeedApi(request,env,ctx,buyer,url);
  if(path==='/api/v1/world/now'){const base=await app.fetch(request,env,ctx);if(!base.ok)return base;const baseData=await base.json(),needData=await needsNow(env,buyer);return json({...baseData,...needData,quietState:Boolean(baseData.quietState)&&needData.activeNeedCount===0});}
  if(path==='/api/v1/world/bootstrap')return bootstrapWithNeeds(request,env,ctx,buyer);
  if(path.startsWith('/api/v1/world/context/'))return contextWithNeeds(request,env,ctx,buyer,path);
  if(path==='/api/v1/world/search'){const base=await app.fetch(request,env,ctx);if(!base.ok)return base;const data=await base.json(),q=normalized(url.searchParams.get('q'));if(q.length<2)return json(data);const rows=await env.DB.prepare(`SELECT public_id,title,need_type,updated_at FROM world_needs WHERE buyer_account_id=? AND status NOT IN ('DISMISSED','CANCELLED') AND (normalized_title LIKE ? OR lower(COALESCE(description,'')) LIKE ?) ORDER BY updated_at DESC LIMIT 80`).bind(buyer.buyer_account_id,`%${q}%`,`%${q}%`).all();return json({...data,results:[...(data.results||[]),...(rows.results||[]).map(row=>({resultType:'Need',publicId:row.public_id,title:row.title,subtype:row.need_type,updatedAt:row.updated_at}))].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,150)});}
  if(isInput){const clone=request.clone(),body=await clone.json().catch(()=>({})),requested=clean(body.requestedType,30).toLocaleLowerCase();if(requested==='need'){return json({route:'need',confidence:1,needsConfirmation:true,allowedRoutes:['thing','situation','knowledge','open_loop','need'],method:'explicit_user_choice',persisted:false,proposedNeed:{needType:clean(body.needType,30).toUpperCase()||'OTHER',title:clean(body.content,180),description:clean(body.content,5000),confidence:'CONFIRMED'}});}const result=classifyNeed(body.content);if(result){log('need_input_routed',{buyerId:buyer.buyer_account_id,type:result.proposedNeed.needType,confidence:result.confidence,contentLength:clean(body.content,50000).length});return json({...result,allowedRoutes:['thing','situation','knowledge','open_loop','need'],method:'deterministic_need_rules',persisted:false});}return app.fetch(request,env,ctx);}
  return app.fetch(request,env,ctx);
}catch(error){log('resolution_provider_failed',{path,category:clean(error?.name||'error',80),message:clean(error?.message,180)});return json({error:'resolution_unavailable'},500);}}};
