import app from './worker-v96.js';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
const now=()=>new Date().toISOString();
const clean=(value,max=1000)=>typeof value==='string'?value.trim().slice(0,max):'';
const imageTypes=new Set(['image/jpeg','image/png','image/webp']);
let schemaReady;

async function sha(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function cookie(request,name){for(const part of(request.headers.get('cookie')||'').split(';')){const[key,...value]=part.trim().split('=');if(key===name)return decodeURIComponent(value.join('='))}return''}
function safeUrl(value){const input=clean(value,600);if(!input)return null;try{const url=new URL(input);return['http:','https:'].includes(url.protocol)?url.toString():null}catch{return null}}
function safeLogoUrl(value){const input=clean(value,600);if(!input)return null;try{const url=new URL(input);const host=url.hostname.toLowerCase();if(url.protocol!=='https:'||!host.includes('.')||host.includes(':')||/^\d+(?:\.\d+){3}$/.test(host)||host==='localhost'||host.endsWith('.local')||host.endsWith('.internal'))return null;return url.toString()}catch{return null}}
function safeEmail(value){const email=clean(value,254).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:null}
function sameOrigin(request){const origin=request.headers.get('origin');return !origin||origin===new URL(request.url).origin}

async function schema(env){if(!schemaReady){schemaReady=env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS buyer_profiles(buyer_account_id TEXT PRIMARY KEY,display_name TEXT,picture_url TEXT,bio TEXT,share_with_connected_businesses INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS organization_profiles(organization_id TEXT PRIMARY KEY,display_name TEXT,logo_url TEXT,logo_source_url TEXT,description TEXT,website_url TEXT,support_email TEXT,updated_at TEXT NOT NULL)`),
  env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_buyer_profiles_updated ON buyer_profiles(updated_at DESC)'),
  env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_organization_profiles_updated ON organization_profiles(updated_at DESC)'),
  env.DB.prepare('PRAGMA optimize')
]).catch(error=>{schemaReady=undefined;throw error})}await schemaReady}

async function buyerSession(request,env){const raw=cookie(request,'still_buyer');if(!raw)return null;return await env.DB.prepare(`SELECT a.id buyer_account_id,a.email,a.name,a.picture_url google_picture FROM buyer_sessions s JOIN buyer_accounts a ON a.id=s.buyer_account_id WHERE s.token_hash=? AND s.expires_at>? AND a.status='active'`).bind(await sha(raw),now()).first()||null}
async function companySession(request,env){const raw=cookie(request,'still_company');if(!raw)return null;return await env.DB.prepare(`SELECT m.id member_id,m.email,m.role,o.id organization_id,o.name organization_name,o.status organization_status FROM merchant_sessions s JOIN merchant_members m ON m.id=s.member_id JOIN merchant_organizations o ON o.id=m.organization_id WHERE s.token_hash=? AND s.expires_at>? AND m.status='active'`).bind(await sha(raw),now()).first()||null}

async function buyerProfile(env,buyer){const row=await env.DB.prepare('SELECT * FROM buyer_profiles WHERE buyer_account_id=?').bind(buyer.buyer_account_id).first();return{buyerAccountId:buyer.buyer_account_id,displayName:row?.display_name||buyer.name||buyer.email,pictureUrl:row?.picture_url||buyer.google_picture||null,bio:row?.bio||'',shareWithConnectedBusinesses:row?!!row.share_with_connected_businesses:true,email:buyer.email,updatedAt:row?.updated_at||null}}
async function companyProfile(env,company){const row=await env.DB.prepare('SELECT * FROM organization_profiles WHERE organization_id=?').bind(company.organization_id).first();return{organizationId:company.organization_id,displayName:row?.display_name||company.organization_name,logoUrl:row?.logo_url||null,logoSourceUrl:row?.logo_source_url||'',description:row?.description||'',websiteUrl:row?.website_url||'',supportEmail:row?.support_email||'',verified:company.organization_status==='verified',status:company.organization_status,updatedAt:row?.updated_at||null}}

async function saveBuyerProfile(request,env,buyer){if(!sameOrigin(request))return json({error:'origin_not_allowed'},403);const body=await request.json().catch(()=>({})),displayName=clean(body.displayName,180),bio=clean(body.bio,600),share=body.shareWithConnectedBusinesses===false?0:1;if(displayName.length<2)return json({error:'invalid_profile'},422);await env.DB.prepare(`INSERT INTO buyer_profiles(buyer_account_id,display_name,bio,share_with_connected_businesses,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(buyer_account_id) DO UPDATE SET display_name=excluded.display_name,bio=excluded.bio,share_with_connected_businesses=excluded.share_with_connected_businesses,updated_at=excluded.updated_at`).bind(buyer.buyer_account_id,displayName,bio||null,share,now()).run();return json({ok:true,profile:await buyerProfile(env,buyer)})}
async function saveCompanyProfile(request,env,company){if(!sameOrigin(request))return json({error:'origin_not_allowed'},403);if(!['owner','admin','manager'].includes(company.role))return json({error:'forbidden'},403);const body=await request.json().catch(()=>({})),displayName=clean(body.displayName,180),description=clean(body.description,900),website=safeUrl(body.websiteUrl),support=safeEmail(body.supportEmail),hasLogo=Object.prototype.hasOwnProperty.call(body,'logoUrl'),logo=hasLogo?safeLogoUrl(body.logoUrl):null,logoPath=logo?`/api/v1/profile-media/company-logo/${encodeURIComponent(company.organization_id)}`:null;if(displayName.length<2||(body.websiteUrl&&!website)||(body.supportEmail&&!support)||(hasLogo&&body.logoUrl&&!logo))return json({error:'invalid_profile'},422);await env.DB.prepare(`INSERT INTO organization_profiles(organization_id,display_name,logo_url,logo_source_url,description,website_url,support_email,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET display_name=excluded.display_name,logo_url=CASE WHEN ?=1 THEN excluded.logo_url ELSE organization_profiles.logo_url END,logo_source_url=CASE WHEN ?=1 THEN excluded.logo_source_url ELSE organization_profiles.logo_source_url END,description=excluded.description,website_url=excluded.website_url,support_email=excluded.support_email,updated_at=excluded.updated_at`).bind(company.organization_id,displayName,logoPath,logo,description||null,website,support,now(),hasLogo?1:0,hasLogo?1:0).run();return json({ok:true,profile:await companyProfile(env,company)})}

async function uploadImage(request,env,owner,kind){if(!sameOrigin(request))return json({error:'origin_not_allowed'},403);if(!env.PROFILE_MEDIA)return json({error:'media_storage_not_configured'},503);const type=(request.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!imageTypes.has(type))return json({error:'invalid_image_type'},415);const bytes=await request.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>350000)return json({error:'image_too_large',maxBytes:350000},413);const extension=type==='image/png'?'png':type==='image/webp'?'webp':'jpg',scope=kind==='buyer'?'buyer':'company',ownerId=kind==='buyer'?owner.buyer_account_id:owner.organization_id,key=`${scope}/${ownerId}/profile.${extension}`;await env.PROFILE_MEDIA.put(key,bytes,{httpMetadata:{contentType:type},customMetadata:{ownerId,scope}});const mediaUrl=`/api/v1/profile-media/${scope}/${encodeURIComponent(ownerId)}/profile.${extension}`;if(kind==='buyer')await env.DB.prepare(`INSERT INTO buyer_profiles(buyer_account_id,picture_url,updated_at) VALUES(?,?,?) ON CONFLICT(buyer_account_id) DO UPDATE SET picture_url=excluded.picture_url,updated_at=excluded.updated_at`).bind(ownerId,mediaUrl,now()).run();else await env.DB.prepare(`INSERT INTO organization_profiles(organization_id,logo_url,logo_source_url,updated_at) VALUES(?, ?,NULL,?) ON CONFLICT(organization_id) DO UPDATE SET logo_url=excluded.logo_url,logo_source_url=NULL,updated_at=excluded.updated_at`).bind(ownerId,mediaUrl,now()).run();return json({ok:true,url:mediaUrl})}

async function buyerRelatedToCompany(env,buyerId,organizationId){const privacy=await env.DB.prepare('SELECT share_with_connected_businesses FROM buyer_profiles WHERE buyer_account_id=?').bind(buyerId).first().catch(()=>null);if(privacy&&privacy.share_with_connected_businesses===0)return false;const passport=await env.DB.prepare('SELECT 1 ok FROM ownership_passports WHERE buyer_account_id=? AND organization_id=? LIMIT 1').bind(buyerId,organizationId).first().catch(()=>null);if(passport)return true;const linked=await env.DB.prepare(`SELECT 1 ok FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id WHERE l.buyer_account_id=? AND c.organization_id=? LIMIT 1`).bind(buyerId,organizationId).first().catch(()=>null);return!!linked}
async function media(request,env,path){const remote=path.match(/^\/api\/v1\/profile-media\/company-logo\/([^/]+)$/);if(remote){const ownerId=decodeURIComponent(remote[1]),row=await env.DB.prepare(`SELECT o.status,p.logo_source_url FROM merchant_organizations o JOIN organization_profiles p ON p.organization_id=o.id WHERE o.id=?`).bind(ownerId).first();let allowed=row?.status==='verified';if(!allowed){const company=await companySession(request,env);allowed=company?.organization_id===ownerId}if(!allowed||!row?.logo_source_url)return new Response('Not found',{status:404});const source=await fetch(row.logo_source_url,{headers:{accept:'image/avif,image/webp,image/png,image/jpeg'},redirect:'follow',signal:AbortSignal.timeout(8000)});const type=(source.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!source.ok||!imageTypes.has(type))return new Response('Not found',{status:404});const declared=Number(source.headers.get('content-length')||0);if(declared>350000)return new Response('Image too large',{status:413});const bytes=await source.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>350000)return new Response('Image too large',{status:413});return new Response(bytes,{headers:{'content-type':type,'cache-control':'public, max-age=3600','x-content-type-options':'nosniff','cross-origin-resource-policy':'same-origin'}})}if(!env.PROFILE_MEDIA)return new Response('Not found',{status:404});const match=path.match(/^\/api\/v1\/profile-media\/(buyer|company)\/([^/]+)\/(profile\.(?:png|webp|jpg))$/);if(!match)return new Response('Not found',{status:404});const scope=match[1],ownerId=decodeURIComponent(match[2]),key=`${scope}/${ownerId}/${match[3]}`;if(scope==='buyer'){const buyer=await buyerSession(request,env);let allowed=buyer?.buyer_account_id===ownerId;if(!allowed){const company=await companySession(request,env);if(company)allowed=await buyerRelatedToCompany(env,ownerId,company.organization_id)}if(!allowed)return new Response('Forbidden',{status:403})}else{const org=await env.DB.prepare('SELECT status FROM merchant_organizations WHERE id=?').bind(ownerId).first();let allowed=org?.status==='verified';if(!allowed){const company=await companySession(request,env);allowed=company?.organization_id===ownerId}if(!allowed)return new Response('Forbidden',{status:403})}const object=await env.PROFILE_MEDIA.get(key);if(!object)return new Response('Not found',{status:404});const headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('x-content-type-options','nosniff');headers.set('cache-control',scope==='company'?'public, max-age=3600':'private, no-store');return new Response(object.body,{headers})}

async function safeFirst(env,sql,bindings=[]){return env.DB.prepare(sql).bind(...bindings).first().catch(()=>null)}
async function safeAll(env,sql,bindings=[]){return env.DB.prepare(sql).bind(...bindings).all().then(result=>result.results||[]).catch(()=>[])}
async function buyerDashboard(env,buyer){const profile=await buyerProfile(env,buyer);const [passport,commitments,cases,rewards,companies,recent]=await Promise.all([
  safeFirst(env,"SELECT COUNT(*) total,SUM(CASE WHEN organization_id IS NOT NULL THEN 1 ELSE 0 END) connected FROM ownership_passports WHERE buyer_account_id=? AND status<>'archived'",[buyer.buyer_account_id]),
  safeFirst(env,"SELECT COUNT(*) total FROM passport_commitments WHERE buyer_account_id=? AND status IN ('promised','in_progress')",[buyer.buyer_account_id]),
  safeFirst(env,'SELECT COUNT(*) total FROM buyer_case_links WHERE buyer_account_id=?',[buyer.buyer_account_id]),
  safeFirst(env,'SELECT points_balance,reputation_score,reputation_level FROM buyer_reward_accounts WHERE email_hash=?',[await sha(buyer.email.toLowerCase())]),
  safeAll(env,`WITH related AS (SELECT DISTINCT organization_id FROM ownership_passports WHERE buyer_account_id=? AND organization_id IS NOT NULL UNION SELECT DISTINCT c.organization_id FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id WHERE l.buyer_account_id=? AND c.organization_id IS NOT NULL) SELECT o.id organization_id,o.name legal_name,o.status,COALESCE(p.display_name,o.name) display_name,p.logo_url,p.description,p.website_url,p.support_email,(SELECT COUNT(*) FROM ownership_passports x WHERE x.buyer_account_id=? AND x.organization_id=o.id) passport_count FROM related r JOIN merchant_organizations o ON o.id=r.organization_id LEFT JOIN organization_profiles p ON p.organization_id=o.id ORDER BY display_name`,[buyer.buyer_account_id,buyer.buyer_account_id,buyer.buyer_account_id]),
  safeAll(env,`SELECT p.public_id,p.kind,p.title,p.business_name,p.status,p.updated_at,o.status organization_status,op.logo_url,COALESCE(op.display_name,o.name,p.business_name) company_display_name FROM ownership_passports p LEFT JOIN merchant_organizations o ON o.id=p.organization_id LEFT JOIN organization_profiles op ON op.organization_id=p.organization_id WHERE p.buyer_account_id=? AND p.status<>'archived' ORDER BY p.updated_at DESC LIMIT 8`,[buyer.buyer_account_id])
]);return json({profile,capabilities:{profileMediaUploads:!!env.PROFILE_MEDIA},metrics:{passports:Number(passport?.total||0),connectedPassports:Number(passport?.connected||0),openCommitments:Number(commitments?.total||0),cases:Number(cases?.total||0),points:Number(rewards?.points_balance||0),reputation:Number(rewards?.reputation_score||50),reputationLevel:rewards?.reputation_level||'participant'},companies,recentPassports:recent})}

async function companyDashboard(env,company){const profile=await companyProfile(env,company);const [passports,buyers,cases,services,tasks,commitments,relationships,recent]=await Promise.all([
  safeFirst(env,"SELECT COUNT(*) total,SUM(CASE WHEN buyer_account_id IS NOT NULL THEN 1 ELSE 0 END) connected FROM ownership_passports WHERE organization_id=? AND status<>'archived'",[company.organization_id]),
  safeFirst(env,`WITH related AS (SELECT buyer_account_id FROM ownership_passports WHERE organization_id=? AND buyer_account_id IS NOT NULL UNION SELECT l.buyer_account_id FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id WHERE c.organization_id=?) SELECT COUNT(*) total FROM related`,[company.organization_id,company.organization_id]),
  safeFirst(env,"SELECT COUNT(*) total,SUM(CASE WHEN status NOT IN ('resolved','closed','rejected') THEN 1 ELSE 0 END) open FROM consumer_cases WHERE organization_id=?",[company.organization_id]),
  safeFirst(env,"SELECT COUNT(*) total FROM service_engagements WHERE organization_id=? AND status NOT IN ('completed','cancelled')",[company.organization_id]),
  safeFirst(env,"SELECT COUNT(*) total FROM merchant_tasks WHERE organization_id=? AND status IN ('open','doing')",[company.organization_id]),
  safeFirst(env,"SELECT COUNT(*) total FROM passport_commitments WHERE organization_id=? AND status IN ('promised','in_progress')",[company.organization_id]),
  safeAll(env,`WITH related AS (SELECT buyer_account_id,MAX(updated_at) last_activity FROM ownership_passports WHERE organization_id=? AND buyer_account_id IS NOT NULL GROUP BY buyer_account_id UNION SELECT l.buyer_account_id,MAX(c.updated_at) last_activity FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id WHERE c.organization_id=? GROUP BY l.buyer_account_id), people AS (SELECT buyer_account_id,MAX(last_activity) last_activity FROM related GROUP BY buyer_account_id) SELECT a.id buyer_account_id,COALESCE(bp.display_name,a.name,a.email) display_name,CASE WHEN COALESCE(bp.share_with_connected_businesses,1)=1 THEN COALESCE(bp.picture_url,a.picture_url) ELSE NULL END picture_url,CASE WHEN COALESCE(bp.share_with_connected_businesses,1)=1 THEN bp.bio ELSE NULL END bio,a.email,(SELECT COUNT(*) FROM ownership_passports p WHERE p.organization_id=? AND p.buyer_account_id=a.id) passport_count,(SELECT COUNT(*) FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id WHERE c.organization_id=? AND l.buyer_account_id=a.id) case_count,people.last_activity FROM people JOIN buyer_accounts a ON a.id=people.buyer_account_id LEFT JOIN buyer_profiles bp ON bp.buyer_account_id=a.id ORDER BY people.last_activity DESC LIMIT 100`,[company.organization_id,company.organization_id,company.organization_id,company.organization_id]),
  safeAll(env,`SELECT p.public_id,p.kind,p.title,p.status,p.updated_at,COALESCE(bp.display_name,a.name,a.email) buyer_name,CASE WHEN COALESCE(bp.share_with_connected_businesses,1)=1 THEN COALESCE(bp.picture_url,a.picture_url) ELSE NULL END buyer_picture FROM ownership_passports p LEFT JOIN buyer_accounts a ON a.id=p.buyer_account_id LEFT JOIN buyer_profiles bp ON bp.buyer_account_id=a.id WHERE p.organization_id=? AND p.status<>'archived' ORDER BY p.updated_at DESC LIMIT 8`,[company.organization_id])
]);return json({profile,member:{email:company.email,role:company.role},capabilities:{profileMediaUploads:!!env.PROFILE_MEDIA},metrics:{passports:Number(passports?.total||0),connectedPassports:Number(passports?.connected||0),buyers:Number(buyers?.total||0),cases:Number(cases?.total||0),openCases:Number(cases?.open||0),activeServices:Number(services?.total||0),openTasks:Number(tasks?.total||0),openCommitments:Number(commitments?.total||0)},relationships,recentPassports:recent})}

async function enrich(request,env,path,response){if(!response.ok||request.method!=='GET')return response;let data;try{data=await response.json()}catch{return response}
  if(path==='/api/v1/buyer-auth/me'&&data.authenticated){const buyer=await buyerSession(request,env);if(buyer){const profile=await buyerProfile(env,buyer);data.profile=profile;data.buyer.name=profile.displayName;data.buyer.pictureUrl=profile.pictureUrl}}
  if(path==='/api/v1/auth/me'&&data.organization){const company=await companySession(request,env);if(company){const profile=await companyProfile(env,company);data.profile=profile;data.organization.displayName=profile.displayName;data.organization.logoUrl=profile.logoUrl}}
  if(path==='/api/v1/ownership/passports'&&Array.isArray(data.passports)){const buyer=await buyerSession(request,env);if(buyer){const companies=await safeAll(env,`SELECT o.id,COALESCE(p.display_name,o.name) display_name,p.logo_url,p.description,p.website_url,p.support_email,o.status FROM merchant_organizations o LEFT JOIN organization_profiles p ON p.organization_id=o.id WHERE o.id IN (SELECT DISTINCT organization_id FROM ownership_passports WHERE buyer_account_id=? AND organization_id IS NOT NULL)`,[buyer.buyer_account_id]);const map=new Map(companies.map(item=>[item.id,item]));data.passports=data.passports.map(item=>({...item,companyProfile:item.organizationId?map.get(item.organizationId)||null:null}))}}
  if(path==='/api/v1/business/passports'&&Array.isArray(data.passports)){const company=await companySession(request,env);if(company){const buyers=await safeAll(env,`SELECT p.public_id,a.id buyer_account_id,COALESCE(bp.display_name,a.name,a.email) display_name,CASE WHEN COALESCE(bp.share_with_connected_businesses,1)=1 THEN COALESCE(bp.picture_url,a.picture_url) ELSE NULL END picture_url FROM ownership_passports p LEFT JOIN buyer_accounts a ON a.id=p.buyer_account_id LEFT JOIN buyer_profiles bp ON bp.buyer_account_id=a.id WHERE p.organization_id=?`,[company.organization_id]);const map=new Map(buyers.map(item=>[item.public_id,item]));data.organization.profile=await companyProfile(env,company);data.passports=data.passports.map(item=>({...item,buyerProfile:map.get(item.publicId)||null}))}}
  if(path.startsWith('/api/v1/ownership/verify/')&&data.passport?.issuer?.type==='verified_business'){const record=await safeFirst(env,`SELECT p.logo_url,COALESCE(p.display_name,o.name) display_name,p.website_url FROM ownership_passports x JOIN merchant_organizations o ON o.id=x.organization_id LEFT JOIN organization_profiles p ON p.organization_id=o.id WHERE x.public_id=?`,[data.passport.publicId]);if(record)data.passport.issuer={...data.passport.issuer,name:record.display_name||data.passport.issuer.name,logoUrl:record.logo_url||null,websiteUrl:record.website_url||null}}
  const headers=new Headers(response.headers);headers.delete('content-length');headers.set('content-type','application/json; charset=utf-8');headers.set('cache-control','no-store');return new Response(JSON.stringify(data),{status:response.status,headers})}

export default{async fetch(request,env){try{const path=new URL(request.url).pathname;if(!path.startsWith('/api/'))return app.fetch(request,env);if(!env.DB)return json({error:'database_not_configured'},503);await schema(env);if(path.startsWith('/api/v1/profile-media/'))return media(request,env,path);
  if(path==='/api/v1/buyer-profile'){const buyer=await buyerSession(request,env);if(!buyer)return json({error:'unauthorized'},401);if(request.method==='GET')return json({profile:await buyerProfile(env,buyer)});if(request.method==='POST')return saveBuyerProfile(request,env,buyer)}
  if(path==='/api/v1/buyer-profile/photo'&&request.method==='POST'){const buyer=await buyerSession(request,env);if(!buyer)return json({error:'unauthorized'},401);return uploadImage(request,env,buyer,'buyer')}
  if(path==='/api/v1/buyer-dashboard'&&request.method==='GET'){const buyer=await buyerSession(request,env);if(!buyer)return json({error:'unauthorized'},401);return buyerDashboard(env,buyer)}
  if(path==='/api/v1/business-profile'){const company=await companySession(request,env);if(!company)return json({error:'unauthorized'},401);if(request.method==='GET')return json({profile:await companyProfile(env,company)});if(request.method==='POST')return saveCompanyProfile(request,env,company)}
  if(path==='/api/v1/business-profile/logo'&&request.method==='POST'){const company=await companySession(request,env);if(!company)return json({error:'unauthorized'},401);if(!['owner','admin','manager'].includes(company.role))return json({error:'forbidden'},403);return uploadImage(request,env,company,'company')}
  if(path==='/api/v1/business-dashboard'&&request.method==='GET'){const company=await companySession(request,env);if(!company)return json({error:'unauthorized'},401);return companyDashboard(env,company)}
  const response=await app.fetch(request,env);return enrich(request,env,path,response)}catch(error){console.error('relationship_identity_error',error);return json({error:'internal_error'},500)}}};
