import base from './worker.js';
const enc=new TextEncoder(),JSON_H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{...JSON_H,...h}}),now=()=>new Date().toISOString(),id=p=>p+crypto.randomUUID().replaceAll('-',''),clean=(v,n=500)=>typeof v==='string'?v.trim().slice(0,n):'';
async function sha(v){const b=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bytes(n){const a=new Uint8Array(n);crypto.getRandomValues(a);return a}function hex(a){return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}function fromHex(s){return new Uint8Array((s.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)))}
async function passwordHash(password,salt,iterations=100000){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return hex(new Uint8Array(bits))}
function cookie(req,name){const raw=req.headers.get('cookie')||'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return''}
function sessionCookie(token,maxAge=604800){return `still_company=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function session(req,env){const token=cookie(req,'still_company');if(!token)return null;const h=await sha(token);const r=await env.DB.prepare(`SELECT s.id session_id,s.member_id,m.email,m.role,m.status member_status,o.id organization_id,o.name organization_name,o.slug,o.country_code,o.status organization_status FROM merchant_sessions s JOIN merchant_members m ON m.id=s.member_id JOIN merchant_organizations o ON o.id=m.organization_id WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now()).first();if(!r||r.member_status!=='active')return null;env.DB.prepare('UPDATE merchant_sessions SET last_seen_at=? WHERE id=?').bind(now(),r.session_id).run().catch(()=>{});return r}
async function register(req,env){let b;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}const name=clean(b.companyName,160),country=clean(b.countryCode,2).toLowerCase(),email=clean(b.email,254).toLowerCase(),password=typeof b.password==='string'?b.password:'';if(name.length<2||!['hr','de','at','si','it','us'].includes(country)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<10)return json({error:'invalid_registration'},422);if(await env.DB.prepare('SELECT id FROM merchant_members WHERE email=?').bind(email).first())return json({error:'email_exists'},409);const ts=now(),org=id('org_'),member=id('mem_'),slug=(name.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||'company')+'-'+crypto.randomUUID().slice(0,6),salt=bytes(16),iterations=100000,ph=await passwordHash(password,salt,iterations);await env.DB.batch([env.DB.prepare('INSERT INTO merchant_organizations(id,slug,name,country_code,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(org,slug,name,country,'pending',ts,ts),env.DB.prepare('INSERT INTO merchant_members(id,organization_id,email,password_hash,password_salt,password_iterations,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(member,org,email,ph,hex(salt),iterations,'owner','active',ts,ts)]);const token=id('sess_'),exp=new Date(Date.now()+604800000).toISOString();await env.DB.prepare('INSERT INTO merchant_sessions(id,member_id,token_hash,expires_at,last_seen_at,created_at) VALUES(?,?,?,?,?,?)').bind(id('s_'),member,await sha(token),exp,ts,ts).run();return json({ok:true,organization:{name,status:'pending'}},201,{'set-cookie':sessionCookie(token)})}
async function login(req,env){let b;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}const email=clean(b.email,254).toLowerCase(),password=typeof b.password==='string'?b.password:'';const r=await env.DB.prepare('SELECT id,email,password_hash,password_salt,password_iterations,status FROM merchant_members WHERE email=?').bind(email).first();if(!r||r.status!=='active')return json({error:'invalid_credentials'},401);const got=await passwordHash(password,fromHex(r.password_salt),r.password_iterations);if(got!==r.password_hash)return json({error:'invalid_credentials'},401);const token=id('sess_'),ts=now(),exp=new Date(Date.now()+604800000).toISOString();await env.DB.prepare('INSERT INTO merchant_sessions(id,member_id,token_hash,expires_at,last_seen_at,created_at) VALUES(?,?,?,?,?,?)').bind(id('s_'),r.id,await sha(token),exp,ts,ts).run();return json({ok:true},200,{'set-cookie':sessionCookie(token)})}
async function logout(req,env){const token=cookie(req,'still_company');if(token)await env.DB.prepare('DELETE FROM merchant_sessions WHERE token_hash=?').bind(await sha(token)).run();return json({ok:true},200,{'set-cookie':sessionCookie('',0)})}
async function me(req,env){const s=await session(req,env);if(!s)return json({error:'unauthorized'},401);return json({member:{email:s.email,role:s.role},organization:{id:s.organization_id,name:s.organization_name,slug:s.slug,countryCode:s.country_code,status:s.organization_status}})}
async function list(req,env,s){const u=new URL(req.url),status=clean(u.searchParams.get('status'),30),q=clean(u.searchParams.get('q'),100);let sql='SELECT public_id,retailer_name,case_type,product_name,status,created_at,updated_at FROM consumer_cases WHERE organization_id=?',a=[s.organization_id];if(status){sql+=' AND status=?';a.push(status)}if(q){const x=`%${q}%`;sql+=' AND (public_id LIKE ? OR product_name LIKE ? OR retailer_name LIKE ?)';a.push(x,x,x)}sql+=' ORDER BY updated_at DESC LIMIT 100';const r=await env.DB.prepare(sql).bind(...a).all();return json({organization:{name:s.organization_name,status:s.organization_status},cases:r.results})}
async function detail(env,s,pid){const c=await env.DB.prepare('SELECT * FROM consumer_cases WHERE public_id=? AND organization_id=?').bind(pid,s.organization_id).first();if(!c)return json({error:'not_found'},404);const messages=await env.DB.prepare('SELECT id,actor_type,message_type,body,created_at FROM case_messages WHERE case_id=? ORDER BY created_at').bind(c.id).all(),decisions=await env.DB.prepare('SELECT id,decision_type,reason,service_reference,proposed_resolution,created_at FROM case_decisions WHERE case_id=? ORDER BY created_at DESC').bind(c.id).all();return json({case:c,messages:messages.results,decisions:decisions.results})}
const D={accepted:'approved',need_more_info:'waiting_consumer',bring_to_store:'in_review',repair:'repair',replacement:'replacement',refund:'refund',rejected:'rejected',other:'in_review'};
async function decision(req,env,s,pid){const c=await env.DB.prepare('SELECT id FROM consumer_cases WHERE public_id=? AND organization_id=?').bind(pid,s.organization_id).first();if(!c)return json({error:'not_found'},404);let b;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}const d=clean(b.decision,30);if(!(d in D))return json({error:'invalid_decision'},422);const ts=now(),did=id('dec_');await env.DB.batch([env.DB.prepare('INSERT INTO case_decisions(id,case_id,organization_id,decision_type,reason,service_reference,proposed_resolution,created_by_member_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(did,c.id,s.organization_id,d,clean(b.reason,3000)||null,clean(b.serviceReference,120)||null,clean(b.proposedResolution,2000)||null,s.member_id,ts),env.DB.prepare('UPDATE consumer_cases SET status=?,updated_at=? WHERE id=?').bind(D[d],ts,c.id),env.DB.prepare('INSERT INTO case_events(id,case_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('evt_'),c.id,'merchant_decision','merchant',s.member_id,JSON.stringify({decision:d,status:D[d],decisionId:did}),ts)]);return json({ok:true,decisionId:did,status:D[d],updatedAt:ts})}
export default{async fetch(req,env){try{const u=new URL(req.url),p=u.pathname;if(!p.startsWith('/api/'))return env.ASSETS.fetch(req);if(!env.DB)return json({error:'database_not_configured'},503);if(p==='/api/v1/auth/register'&&req.method==='POST')return register(req,env);if(p==='/api/v1/auth/login'&&req.method==='POST')return login(req,env);if(p==='/api/v1/auth/logout'&&req.method==='POST')return logout(req,env);if(p==='/api/v1/auth/me'&&req.method==='GET')return me(req,env);if(p.startsWith('/api/v1/merchant/')){const s=await session(req,env);if(s){if(p==='/api/v1/merchant/cases'&&req.method==='GET')return list(req,env,s);let m=p.match(/^\/api\/v1\/merchant\/cases\/([^/]+)$/);if(m&&req.method==='GET')return detail(env,s,m[1]);m=p.match(/^\/api\/v1\/merchant\/cases\/([^/]+)\/decision$/);if(m&&req.method==='POST')return decision(req,env,s,m[1])}}return base.fetch(req,env)}catch(e){console.error(e);return json({error:'internal_error'},500)}}};