import app from './worker-v75.js';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'},json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{...H,...h}}),now=()=>new Date().toISOString(),uid=p=>p+crypto.randomUUID().replaceAll('-',''),enc=new TextEncoder(),clean=(v,n=1000)=>typeof v==='string'?v.trim().slice(0,n):'';
async function sha(v){const b=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function cookie(req,n){for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return''}
function b64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function parseJwtPart(s){return JSON.parse(new TextDecoder().decode(b64url(s)))}
let jwksCache={at:0,keys:[]};
async function googleJwks(){if(Date.now()-jwksCache.at<30*60*1000&&jwksCache.keys.length)return jwksCache.keys;const r=await fetch('https://www.googleapis.com/oauth2/v3/certs',{headers:{accept:'application/json'}});if(!r.ok)throw Error('google_jwks_unavailable');const d=await r.json();jwksCache={at:Date.now(),keys:Array.isArray(d.keys)?d.keys:[]};return jwksCache.keys}
async function verifyGoogle(token,clientId){if(!clientId)throw Error('google_not_configured');const parts=String(token||'').split('.');if(parts.length!==3)throw Error('invalid_google_token');const [hs,ps,ss]=parts,h=parseJwtPart(hs),p=parseJwtPart(ps);if(h.alg!=='RS256'||!h.kid)throw Error('invalid_google_token');const keys=await googleJwks(),jwk=keys.find(k=>k.kid===h.kid&&k.kty==='RSA');if(!jwk)throw Error('google_key_not_found');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,b64url(ss),enc.encode(hs+'.'+ps));if(!ok)throw Error('invalid_google_signature');const t=Math.floor(Date.now()/1000);if(!['accounts.google.com','https://accounts.google.com'].includes(p.iss))throw Error('invalid_google_issuer');if(p.aud!==clientId)throw Error('invalid_google_audience');if(!p.exp||p.exp<t-30)throw Error('expired_google_token');if(p.nbf&&p.nbf>t+30)throw Error('invalid_google_token');if(!p.sub||!p.email||p.email_verified!==true)throw Error('google_email_not_verified');return{sub:String(p.sub),email:String(p.email).toLowerCase(),name:clean(p.name,180)||null,picture:clean(p.picture,600)||null,hd:clean(p.hd,180)||null}}
async function schema(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS buyer_accounts(id TEXT PRIMARY KEY,google_sub TEXT UNIQUE,email TEXT NOT NULL,email_verified INTEGER NOT NULL DEFAULT 0,name TEXT,picture_url TEXT,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_login_at TEXT NOT NULL)`),
 env.DB.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS idx_buyer_email ON buyer_accounts(email)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS buyer_sessions(id TEXT PRIMARY KEY,buyer_account_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,user_agent_hash TEXT,FOREIGN KEY(buyer_account_id) REFERENCES buyer_accounts(id) ON DELETE CASCADE)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_buyer_sessions_account ON buyer_sessions(buyer_account_id,expires_at)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS buyer_case_links(buyer_account_id TEXT NOT NULL,case_id TEXT NOT NULL,linked_at TEXT NOT NULL,PRIMARY KEY(buyer_account_id,case_id),FOREIGN KEY(buyer_account_id) REFERENCES buyer_accounts(id) ON DELETE CASCADE,FOREIGN KEY(case_id) REFERENCES consumer_cases(id) ON DELETE CASCADE)`)
])}
async function migrateBuyerData(env,a){const email=a.email;await env.DB.prepare(`INSERT OR IGNORE INTO buyer_case_links(buyer_account_id,case_id,linked_at) SELECT ?,id,? FROM consumer_cases WHERE lower(consumer_email)=lower(?)`).bind(a.id,now(),email).run();const reward=await env.DB.prepare(`SELECT id FROM buyer_reward_accounts WHERE email_hash=?`).bind(await sha(email.toLowerCase())).first().catch(()=>null);if(reward)await env.DB.prepare(`UPDATE buyer_reward_accounts SET email_display=?,updated_at=? WHERE id=?`).bind(email.replace(/^(.{2}).*(@.*)$/,'$1***$2'),now(),reward.id).run()}
async function makeSession(req,env,a){const raw=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),hash=await sha(raw),ts=now(),exp=new Date(Date.now()+30*86400000).toISOString(),ua=await sha(req.headers.get('user-agent')||'');await env.DB.prepare('INSERT INTO buyer_sessions(id,buyer_account_id,token_hash,created_at,expires_at,last_seen_at,user_agent_hash) VALUES(?,?,?,?,?,?,?)').bind(uid('bs_'),a.id,hash,ts,exp,ts,ua).run();return{raw,exp}}
async function buyerSession(req,env){await schema(env);const raw=cookie(req,'still_buyer');if(!raw)return null;const hash=await sha(raw);const s=await env.DB.prepare(`SELECT s.id session_id,s.expires_at,a.* FROM buyer_sessions s JOIN buyer_accounts a ON a.id=s.buyer_account_id WHERE s.token_hash=? AND s.expires_at>? AND a.status='active'`).bind(hash,now()).first();if(!s)return null;await env.DB.prepare('UPDATE buyer_sessions SET last_seen_at=? WHERE id=?').bind(now(),s.session_id).run();return s}
function sessionCookie(raw,maxAge=2592000){return `still_buyer=${encodeURIComponent(raw)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function login(req,env){await schema(env);if(!env.GOOGLE_CLIENT_ID)return json({error:'google_not_configured',message:'GOOGLE_CLIENT_ID is not configured in Cloudflare.'},503);const b=await req.json().catch(()=>({})),g=await verifyGoogle(b.credential,env.GOOGLE_CLIENT_ID);let a=await env.DB.prepare('SELECT * FROM buyer_accounts WHERE google_sub=?').bind(g.sub).first();if(!a){const byEmail=await env.DB.prepare('SELECT * FROM buyer_accounts WHERE lower(email)=lower(?)').bind(g.email).first();if(byEmail){if(byEmail.google_sub&&byEmail.google_sub!==g.sub)return json({error:'account_conflict'},409);await env.DB.prepare('UPDATE buyer_accounts SET google_sub=?,email_verified=1,name=COALESCE(?,name),picture_url=COALESCE(?,picture_url),updated_at=?,last_login_at=? WHERE id=?').bind(g.sub,g.name,g.picture,now(),now(),byEmail.id).run();a=await env.DB.prepare('SELECT * FROM buyer_accounts WHERE id=?').bind(byEmail.id).first()}else{const ts=now(),id=uid('ba_');await env.DB.prepare('INSERT INTO buyer_accounts(id,google_sub,email,email_verified,name,picture_url,created_at,updated_at,last_login_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,g.sub,g.email,1,g.name,g.picture,ts,ts,ts).run();a=await env.DB.prepare('SELECT * FROM buyer_accounts WHERE id=?').bind(id).first()}}else{await env.DB.prepare('UPDATE buyer_accounts SET email=?,email_verified=1,name=COALESCE(?,name),picture_url=COALESCE(?,picture_url),updated_at=?,last_login_at=? WHERE id=?').bind(g.email,g.name,g.picture,now(),now(),a.id).run();a=await env.DB.prepare('SELECT * FROM buyer_accounts WHERE id=?').bind(a.id).first()}await migrateBuyerData(env,a);const sess=await makeSession(req,env,a);return json({ok:true,buyer:{id:a.id,email:a.email,name:a.name,pictureUrl:a.picture_url,emailVerified:!!a.email_verified}},200,{'set-cookie':sessionCookie(sess.raw)})}
async function me(req,env){const a=await buyerSession(req,env);if(!a)return json({authenticated:false});await migrateBuyerData(env,a);const cases=await env.DB.prepare(`SELECT c.public_id,c.case_type,c.product_name,c.status,c.created_at,c.updated_at,o.name company_name FROM buyer_case_links l JOIN consumer_cases c ON c.id=l.case_id LEFT JOIN merchant_organizations o ON o.id=c.organization_id WHERE l.buyer_account_id=? ORDER BY c.updated_at DESC LIMIT 200`).bind(a.id).all();const reward=await env.DB.prepare('SELECT points_balance,lifetime_points,reputation_score,reputation_level FROM buyer_reward_accounts WHERE email_hash=?').bind(await sha(a.email.toLowerCase())).first().catch(()=>null);const red=reward?await env.DB.prepare(`SELECT r.code,r.status,r.claimed_at,r.redeemed_at,o.title,o.benefit_type,o.benefit_value FROM reward_redemptions r JOIN reward_offers o ON o.id=r.offer_id WHERE r.buyer_account_id=(SELECT id FROM buyer_reward_accounts WHERE email_hash=?) ORDER BY r.claimed_at DESC LIMIT 100`).bind(await sha(a.email.toLowerCase())).all():{results:[]};return json({authenticated:true,buyer:{id:a.id,email:a.email,name:a.name,pictureUrl:a.picture_url,emailVerified:!!a.email_verified,lastLoginAt:a.last_login_at},cases:cases.results,rewards:reward||{points_balance:0,lifetime_points:0,reputation_score:50,reputation_level:'participant'},redemptions:red.results})}
async function logout(req,env){const raw=cookie(req,'still_buyer');if(raw){await schema(env);await env.DB.prepare('DELETE FROM buyer_sessions WHERE token_hash=?').bind(await sha(raw)).run()}return json({ok:true},200,{'set-cookie':sessionCookie('',0)})}
async function linkCase(req,env,pid){const a=await buyerSession(req,env);if(!a)return json({error:'unauthorized'},401);const b=await req.json().catch(()=>({})),token=clean(b.accessToken,500);if(!token)return json({error:'case_token_required'},422);const c=await env.DB.prepare('SELECT * FROM consumer_cases WHERE public_id=? AND consumer_access_hash=?').bind(pid,await sha(token)).first();if(!c)return json({error:'not_found'},404);if(c.consumer_email&&c.consumer_email.toLowerCase()!==a.email.toLowerCase())return json({error:'email_mismatch'},409);if(!c.consumer_email)await env.DB.prepare('UPDATE consumer_cases SET consumer_email=?,updated_at=? WHERE id=?').bind(a.email,now(),c.id).run();await env.DB.prepare('INSERT OR IGNORE INTO buyer_case_links(buyer_account_id,case_id,linked_at) VALUES(?,?,?)').bind(a.id,c.id,now()).run();return json({ok:true})}
export default{async fetch(req,env){try{const u=new URL(req.url),p=u.pathname;if(p==='/api/v1/auth/google/config'&&req.method==='GET')return json({enabled:!!env.GOOGLE_CLIENT_ID,clientId:env.GOOGLE_CLIENT_ID||null});if(p==='/api/v1/auth/google'&&req.method==='POST')return login(req,env);if(p==='/api/v1/auth/me'&&req.method==='GET')return me(req,env);if(p==='/api/v1/auth/logout'&&req.method==='POST')return logout(req,env);let m=p.match(/^\/api\/v1\/auth\/cases\/([^/]+)\/link$/);if(m&&req.method==='POST')return linkCase(req,env,m[1]);return app.fetch(req,env)}catch(e){console.error(e);const msg=String(e?.message||e);if(msg.startsWith('google_')||msg.startsWith('invalid_google')||msg==='expired_google_token')return json({error:msg},401);return json({error:'internal_error'},500)}}};