import app from './worker-v142.js';
import {reconcileSchedules,expireStale,advanceScheduleDate} from './anticipation-engine-v143.js';
const H={'content-type':'application/json; charset=utf-8','cache-control':'private, no-store','x-content-type-options':'nosniff'},json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:H}),now=()=>new Date().toISOString();
function cookie(r,n){for(const p of(r.headers.get('cookie')||'').split(';')){const[k,...v]=p.trim().split('=');if(k===n)return decodeURIComponent(v.join('='))}return''}
async function sha(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v)));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function buyer(r,e){const t=cookie(r,'still_buyer');if(!t)return null;return e.DB.prepare(`SELECT a.id owner_user_id FROM buyer_sessions s JOIN buyer_accounts a ON a.id=s.buyer_account_id WHERE s.token_hash=? AND s.expires_at>? AND a.status='active'`).bind(await sha(t),now()).first()}
async function body(r){return r.json().catch(()=>({}))}
async function candidate(e,owner,id){return e.DB.prepare(`SELECT * FROM anticipation_candidates WHERE public_id=? AND owner_user_id=?`).bind(id,owner).first()}
async function feedback(e,owner,candidateId,action,reason=null){await e.DB.prepare(`INSERT INTO anticipation_feedback(id,owner_user_id,candidate_id,action,reason,created_at) VALUES(?,?,?,?,?,?)`).bind(`af_${crypto.randomUUID()}`,owner,candidateId,action,reason,now()).run()}
async function list(r,e,b){const u=new URL(r.url),status=u.searchParams.get('status')||'PENDING';const q=await e.DB.prepare(`SELECT public_id,candidate_type,title,explanation,why_now,confidence,status,snoozed_until,linked_need_id,created_at FROM anticipation_candidates WHERE owner_user_id=? AND status=? ORDER BY CASE confidence WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 ELSE 1 END DESC, created_at DESC LIMIT 50`).bind(b.owner_user_id,status).all();return json({candidates:q.results||[]})}
async function attention(e,b){const q=await e.DB.prepare(`SELECT public_id,attention_type,title,explanation,why_now,priority,effective_at,expires_at FROM attention_items WHERE owner_user_id=? AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>?) ORDER BY priority DESC,effective_at ASC LIMIT 20`).bind(b.owner_user_id,now()).all();return json({attention:q.results||[]})}
async function review(r,e,b,id,action){const c=await candidate(e,b.owner_user_id,id);if(!c)return json({error:'not_found'},404);const t=now(),data=await body(r);
 if(action==='dismiss'){await e.DB.prepare(`UPDATE anticipation_candidates SET status='DISMISSED',reviewed_at=?,updated_at=? WHERE id=?`).bind(t,t,c.id).run();await feedback(e,b.owner_user_id,c.id,'DISMISSED',data.reason||null);return json({ok:true,status:'DISMISSED'});}
 if(action==='snooze'){const until=data.until;if(!until||Number.isNaN(new Date(until).getTime())||new Date(until)<=new Date())return json({error:'valid_future_until_required'},422);await e.DB.prepare(`UPDATE anticipation_candidates SET status='SNOOZED',snoozed_until=?,reviewed_at=?,updated_at=? WHERE id=?`).bind(new Date(until).toISOString(),t,t,c.id).run();await feedback(e,b.owner_user_id,c.id,'SNOOZED');return json({ok:true,status:'SNOOZED',until:new Date(until).toISOString()});}
 if(action==='already-handled'){await e.DB.prepare(`UPDATE anticipation_candidates SET status='CONFIRMED',reviewed_at=?,updated_at=? WHERE id=?`).bind(t,t,c.id).run();await feedback(e,b.owner_user_id,c.id,'ALREADY_HANDLED',data.reason||null);return json({ok:true,status:'ALREADY_HANDLED'});}
 if(action==='confirm'){/* Existing Need creation is intentionally delegated through the Phase 3 API contract by the UI/resolution layer; provenance is preserved here until linked. */await e.DB.prepare(`UPDATE anticipation_candidates SET status='CONFIRMED',reviewed_at=?,updated_at=? WHERE id=?`).bind(t,t,c.id).run();await feedback(e,b.owner_user_id,c.id,'CONFIRMED');return json({ok:true,status:'CONFIRMED',proposedNeedType:c.proposed_need_type,proposedNeedPayload:JSON.parse(c.proposed_need_payload_json||'{}'),candidateId:c.public_id});}
 return json({error:'invalid_action'},400)}
async function schedules(r,e,b,id=null){if(r.method==='GET'){const q=await e.DB.prepare(`SELECT public_id,entity_type,entity_id,schedule_type,interval_unit,interval_value,next_due_at,active,title,created_at,updated_at FROM user_world_schedules WHERE owner_user_id=? ORDER BY active DESC,next_due_at ASC`).bind(b.owner_user_id).all();return json({schedules:q.results||[]})}const d=await body(r),t=now();
 if(r.method==='POST'){if(!d.entityType||!d.entityId||!d.scheduleType||!['DAYS','WEEKS','MONTHS','YEARS'].includes(d.intervalUnit)||!Number.isInteger(Number(d.intervalValue))||Number(d.intervalValue)<1||!d.nextDueAt||Number.isNaN(new Date(d.nextDueAt).getTime()))return json({error:'invalid_schedule'},422);const sid=`sch_${crypto.randomUUID()}`;await e.DB.prepare(`INSERT INTO user_world_schedules(id,public_id,owner_user_id,entity_type,entity_id,schedule_type,interval_unit,interval_value,next_due_at,active,title,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?,?)`).bind(sid,sid,b.owner_user_id,d.entityType,d.entityId,d.scheduleType,d.intervalUnit,Number(d.intervalValue),new Date(d.nextDueAt).toISOString(),d.title||null,t,t).run();return json({ok:true,id:sid},201)}
 if(r.method==='PATCH'&&id){const s=await e.DB.prepare(`SELECT * FROM user_world_schedules WHERE public_id=? AND owner_user_id=?`).bind(id,b.owner_user_id).first();if(!s)return json({error:'not_found'},404);if(d.complete===true){const next=advanceScheduleDate(s);await e.DB.prepare(`UPDATE user_world_schedules SET next_due_at=?,updated_at=? WHERE id=?`).bind(next,t,s.id).run();return json({ok:true,nextDueAt:next})}if(typeof d.active==='boolean'){await e.DB.prepare(`UPDATE user_world_schedules SET active=?,updated_at=? WHERE id=?`).bind(d.active?1:0,t,s.id).run();return json({ok:true,active:d.active})}return json({error:'no_supported_change'},422)}return json({error:'method_not_allowed'},405)}
async function preferences(r,e,b){if(r.method==='GET'){let p=await e.DB.prepare(`SELECT * FROM anticipation_preferences WHERE owner_user_id=?`).bind(b.owner_user_id).first();return json({preferences:p||{owner_user_id:b.owner_user_id,proactive_enabled:1,warranty_enabled:1,returns_enabled:1,service_enabled:1,open_loops_enabled:1,market_wants_enabled:1,product_notices_enabled:1,user_schedules_enabled:1}})}const d=await body(r),allowed=['proactive_enabled','warranty_enabled','returns_enabled','service_enabled','open_loops_enabled','market_wants_enabled','product_notices_enabled','user_schedules_enabled'];const current=await e.DB.prepare(`SELECT * FROM anticipation_preferences WHERE owner_user_id=?`).bind(b.owner_user_id).first()||{};const v=Object.fromEntries(allowed.map(k=>[k,d[k]===undefined?(current[k]??1):(d[k]?1:0)]));await e.DB.prepare(`INSERT INTO anticipation_preferences(owner_user_id,proactive_enabled,warranty_enabled,returns_enabled,service_enabled,open_loops_enabled,market_wants_enabled,product_notices_enabled,user_schedules_enabled,quiet_start,quiet_end,lead_times_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_user_id) DO UPDATE SET proactive_enabled=excluded.proactive_enabled,warranty_enabled=excluded.warranty_enabled,returns_enabled=excluded.returns_enabled,service_enabled=excluded.service_enabled,open_loops_enabled=excluded.open_loops_enabled,market_wants_enabled=excluded.market_wants_enabled,product_notices_enabled=excluded.product_notices_enabled,user_schedules_enabled=excluded.user_schedules_enabled,quiet_start=excluded.quiet_start,quiet_end=excluded.quiet_end,lead_times_json=excluded.lead_times_json,updated_at=excluded.updated_at`).bind(b.owner_user_id,...allowed.map(k=>v[k]),d.quietStart??current.quiet_start??null,d.quietEnd??current.quiet_end??null,JSON.stringify(d.leadTimes||JSON.parse(current.lead_times_json||'{}')),now()).run();return json({ok:true})}
export default{async fetch(r,e,c){const u=new URL(r.url);if(!u.pathname.startsWith('/api/v1/world/anticipation')&&!u.pathname.startsWith('/api/v1/world/attention')&&!u.pathname.startsWith('/api/v1/world/schedules'))return app.fetch(r,e,c);try{const b=await buyer(r,e);if(!b)return json({error:'unauthorized'},401);if(u.pathname==='/api/v1/world/anticipation'&&r.method==='GET')return list(r,e,b);if(u.pathname==='/api/v1/world/attention'&&r.method==='GET')return attention(e,b);if(u.pathname==='/api/v1/world/anticipation/preferences'&&['GET','PATCH'].includes(r.method))return preferences(r,e,b);let m=u.pathname.match(/^\/api\/v1\/world\/anticipation\/([^/]+)\/(confirm|dismiss|snooze|already-handled)$/);if(m&&r.method==='POST')return review(r,e,b,decodeURIComponent(m[1]),m[2]);if(u.pathname==='/api/v1/world/schedules')return schedules(r,e,b);m=u.pathname.match(/^\/api\/v1\/world\/schedules\/([^/]+)$/);if(m)return schedules(r,e,b,decodeURIComponent(m[1]));return json({error:'not_found'},404)}catch(x){console.error('anticipation_v143',x);return json({error:'anticipation_unavailable'},500)}},async scheduled(controller,e,c){c.waitUntil((async()=>{await expireStale(e.DB);await reconcileSchedules(e.DB)})());if(typeof app.scheduled==='function')return app.scheduled(controller,e,c)}};
