const fs = require('fs');
const path = require('path');
const BUNDLE = 49;
const runtime = ['theme.js','translations-v40.js','app.js','enhancements.js','v10.js','market-catalog-v36.js','visible-v20.js','core-search-v33.js','decision-v21.js','proof-v22.js','support-v23.js','saved-v24.js','saved-status-v25.js','saved-actions-v26.js','saved-organize-v27.js','case-v28.js','backup-v29.js','warranty-recovery-v39.js','merchant-v30.js','merchant-intake-v31.js','merchant-dashboard-v32.js','merchant-handoff-v34.js','merchant-response-v35.js','merchant-entry-v37.js','purchase-action-v41.js','resolution-v42.js','company-portal-v46.js','retailer-claim-v48.js','admin-review-v48.js'];
const files=['index.html','styles.css','share-icons.css',...runtime,'privacy.html','terms.html','methodology.html','legal-i18n.js','robots.txt','sitemap.xml'];
const outDir=path.join(__dirname,'public');fs.rmSync(outDir,{recursive:true,force:true});fs.mkdirSync(outDir,{recursive:true});for(const file of files){const src=path.join(__dirname,file);if(!fs.existsSync(src))throw new Error(`Missing canonical production asset: ${file}`);fs.copyFileSync(src,path.join(outDir,file))}
const indexPath=path.join(outDir,'index.html');let html=fs.readFileSync(indexPath,'utf8');const inlineStyles=[];html=html.replace(/<style(?:\s[^>]*)?>([\s\S]*?)<\/style>/gi,(_,css)=>{if(css.trim())inlineStyles.push(css.trim());return''});if(inlineStyles.length){const stylesPath=path.join(outDir,'styles.css'),existing=fs.readFileSync(stylesPath,'utf8');fs.writeFileSync(stylesPath,`${existing}\n\n/* Canonical shell styles migrated from index.html */\n${inlineStyles.join('\n')}\n`)}
const marketOptions='<select id="market"><option value="us">United States</option><option value="eu">European Union</option><option value="hr">Croatia</option><option value="de">Germany</option><option value="at">Austria</option><option value="si">Slovenia</option><option value="it">Italy</option></select>';html=html.replace(/<select id=["']market["']>\s*<\/select>/i,marketOptions);
if(!html.includes('class="mode-tabs"'))html=html.replace('<div class="checker-card" aria-live="polite">','<div class="checker-card" aria-live="polite"><div class="mode-tabs"><button type="button" class="active" data-mode="return">↩ <span>Povrat</span></button><button type="button" data-mode="warranty">◇ <span>Jamstvo</span></button></div>');
if(!html.includes('id="for-retailers"')){const hub=`<section id="for-retailers" class="section merchant-entry-static"><div class="section-heading"><span class="eyebrow">Kupac ↔ trgovac</span><h2>Uredniji način rješavanja povrata i jamstva.</h2><p>Still? pomaže kupcu pripremiti potpuni zahtjev, a trgovcu primiti strukturirane podatke umjesto nepotpunih poruka.</p></div><div class="steps"><article class="step"><span>01</span><h3>Za kupce</h3><p>Provjeri prava, pronađi trgovca, pripremi dokaz i pošalji uredan zahtjev.</p><a class="button button-secondary" href="#checker">Provjeri kupnju →</a></article><article class="step"><span>02</span><h3>Za trgovce</h3><p>Otvori račun tvrtke, verificiraj identitet, preuzmi profil trgovca, pregledaj strukturirane slučajeve i odgovori kupcu.</p><a class="button button-secondary" href="#companyPortalV46">Prijava / nova tvrtka →</a></article><article class="step"><span>03</span><h3>Zajednički ishod</h3><p>Kontakt, odgovor, popravak, zamjena, povrat novca ili obrazloženo odbijanje ostaju u jednom tijeku.</p></article></div></section>`;html=html.includes('<section class="section slim" id="recent">')?html.replace('<section class="section slim" id="recent">',`${hub}<section class="section slim" id="recent">`):html.replace('</main>',`${hub}</main>`)}
if(!html.includes('data-merchant-nav-static'))html=html.replace('</nav>','<a href="#for-retailers" data-merchant-nav-static="1">Za trgovce</a></nav>');
for(const file of runtime){const escaped=file.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp(`<script[^>]+src=["'][^"']*${escaped}(?:\\?[^"']*)?["'][^>]*>\\s*<\\/script>`,'gi');html=html.replace(re,'')}
html=html.replace(/<script[^>]+src=["'][^"']*runtime-recovery-v38\.js(?:\?[^"']*)?["'][^>]*>\s*<\/script>/gi,'');const tags=runtime.map(file=>`  <script src="${file}?v=${BUNDLE}" defer></script>`).join('\n');html=html.includes('</body>')?html.replace('</body>',`${tags}\n</body>`):`${html}\n${tags}\n`;html=html.replace(/<meta name=["']still-build["'][^>]*>/gi,'');html=html.replace('</head>',`  <meta name="still-build" content="${BUNDLE}">\n</head>`);const marker=`<span id="stillBuildMarker" style="display:block;margin-top:8px;font-size:9px;font-weight:500;opacity:.55">Build ${BUNDLE}</span>`;if(/<footer[\s>]/i.test(html))html=html.replace(/(<\/footer>)/i,`${marker}$1`);else html=html.replace('</body>',`${marker}\n</body>`);fs.writeFileSync(indexPath,html);fs.writeFileSync(path.join(outDir,'_headers'),`/*\n  Cache-Control: no-store, no-cache, must-revalidate\n  X-Still-Build: ${BUNDLE}\n`);const manifest={app:'Still?',productionBundle:BUNDLE,architecture:'deterministic-admin-route',generatedAt:new Date().toISOString(),runtime,files};fs.writeFileSync(path.join(outDir,'build.json'),JSON.stringify(manifest,null,2)+'\n');console.log(`Built V${BUNDLE}: deterministic Merchant Review Center route.`);