const fs=require('fs'),path=require('path');const BUNDLE=80;
const runtime=['theme.js','translations-v40.js','app.js','enhancements.js','v10.js','market-catalog-v36.js','visible-v20.js','core-search-v33.js','decision-v21.js','proof-v22.js','support-v23.js','saved-v24.js','saved-status-v25.js','saved-actions-v26.js','saved-organize-v27.js','case-v28.js','backup-v29.js','saved-polish-v58.js','warranty-recovery-v39.js','merchant-v30.js','merchant-intake-v31.js','merchant-handoff-v34.js','merchant-response-v35.js','purchase-action-v41.js','resolution-v42.js','relationship-v54.js','buyer-case-v60.js','relationship-v61.js','buyer-onboarding-v65.js','business-entry-v66.js','purchase-intelligence-v67.js','branch-match-v68.js','buyer-notifications-v69.js','buyer-rewards-v76.js','buyer-auth-routes-v79.js','buyer-auth-v77.js','buyer-auth-layout-v78.js'];
const css=['readability-v57.css','saved-polish-v58.css','readability-v59.css','buyer-company-v60.css','relationship-v61.css','buyer-case-polish-v62.css','hero-density-v63.css','buyer-onboarding-v65.css','business-entry-v66.css','purchase-intelligence-v67.css','branch-match-v68.css','notifications-v69.css','buyer-rewards-v76.css','buyer-auth-v77.css','buyer-auth-layout-v78.css'];
const companyScripts=['company-runtime-guard-v80.js','company-portal-v46.js','retailer-claim-v48.js','company-inbox-v60.js','company-relationship-v61.js','company-branches-v68.js','company-notifications-v69.js','company-workbench-v72.js','company-services-mount-v79.js','company-services-v73.js','company-ops-v74.js','company-rewards-v75.js'];
const companyStyles=['relationship-v61.css','company-branches-v68.css','notifications-v69.css','company-workbench-v72.css','company-services-v73.css','company-ops-v74.css','company-rewards-v75.css'];
const companyExtra=[...companyScripts,...companyStyles];
const files=['index.html','company.html','admin.html','styles.css',...css,'share-icons.css',...runtime,...companyExtra,'admin-notifications-v69.js','privacy.html','terms.html','methodology.html','legal-i18n.js','robots.txt','sitemap.xml'];
const out=path.join(__dirname,'public');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});for(const f of files){const src=path.join(__dirname,f);if(!fs.existsSync(src))throw Error(`Missing canonical production asset: ${f}`);fs.copyFileSync(src,path.join(out,f))}
const stripScript=(html,f)=>{const e=f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return html.replace(new RegExp(`<script[^>]+src=["'][^"']*${e}(?:\\?[^"']*)?["'][^>]*>\\s*<\\/script>`,'gi'),'')};
const stripStyle=(html,f)=>{const e=f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return html.replace(new RegExp(`<link[^>]+href=["'][^"']*${e}(?:\\?[^"']*)?["'][^>]*>`,'gi'),'')};
const ip=path.join(out,'index.html');let h=fs.readFileSync(ip,'utf8'),inline=[];h=h.replace(/<style(?:\s[^>]*)?>([\s\S]*?)<\/style>/gi,(_,x)=>{if(x.trim())inline.push(x.trim());return''});if(inline.length){const sp=path.join(out,'styles.css');fs.writeFileSync(sp,fs.readFileSync(sp,'utf8')+'\n'+inline.join('\n'))}h=h.replace(/<link rel=["']stylesheet["'] href=["']styles\.css["']\s*\/?>/i,m=>m+'\n'+css.map(f=>`<link rel="stylesheet" href="${f}?v=${BUNDLE}">`).join('\n'));const market='<select id="market"><option value="us">United States</option><option value="eu">European Union</option><option value="hr">Croatia</option><option value="de">Germany</option><option value="at">Austria</option><option value="si">Slovenia</option><option value="it">Italy</option></select>';h=h.replace(/<select id=["']market["']>\s*<\/select>/i,market);if(!h.includes('class="mode-tabs"'))h=h.replace('<div class="checker-card" aria-live="polite">','<div class="checker-card" aria-live="polite"><div class="mode-tabs"><button type="button" class="active" data-mode="return">↩ <span>Povrat</span></button><button type="button" data-mode="warranty">◇ <span>Jamstvo</span></button></div>');h=h.replace(/<section id=["']for-retailers["'][\s\S]*?<\/section>/gi,'');for(const f of runtime)h=stripScript(h,f);for(const f of companyScripts)h=stripScript(h,f);const tags=runtime.map(f=>`<script src="${f}?v=${BUNDLE}" defer></script>`).join('\n');h=h.replace('</body>',tags+'\n</body>').replace(/<meta name=["']still-build["'][^>]*>/gi,'').replace('</head>',`<meta name="still-build" content="${BUNDLE}"></head>`);const marker=`<span id="stillBuildMarker" style="display:block;margin-top:8px;font-size:9px;font-weight:500;opacity:.55">Build ${BUNDLE}</span>`;h=/<footer[\s>]/i.test(h)?h.replace(/(<\/footer>)/i,marker+'$1'):h.replace('</body>',marker+'</body>');fs.writeFileSync(ip,h);
const cp=path.join(out,'company.html');let company=fs.readFileSync(cp,'utf8');for(const f of companyScripts)company=stripScript(company,f);for(const f of companyStyles)company=stripStyle(company,f);company=stripScript(company,'theme.js');company=company.replace(/\?v=\d+/g,`?v=${BUNDLE}`);company=company.replace('</head>',companyStyles.map(f=>`<link rel="stylesheet" href="${f}?v=${BUNDLE}">`).join('')+'</head>');const companyTags=[`<script src="theme.js?v=${BUNDLE}" defer></script>`,...companyScripts.map(f=>`<script src="${f}?v=${BUNDLE}" defer></script>`)].join('');company=company.replace('</body>',companyTags+'</body>');fs.writeFileSync(cp,company);
const ap=path.join(out,'admin.html');let admin=fs.readFileSync(ap,'utf8');admin=admin.replace('</head>',`<link rel="stylesheet" href="notifications-v69.css?v=${BUNDLE}"></head>`).replace('</body>',`<script src="admin-notifications-v69.js?v=${BUNDLE}" defer></script></body>`);fs.writeFileSync(ap,admin);
fs.writeFileSync(path.join(out,'_headers'),`/*\n  Cache-Control: no-store, no-cache, must-revalidate\n  X-Still-Build: ${BUNDLE}\n/admin*\n  Cache-Control: no-store, no-cache, must-revalidate\n  X-Robots-Tag: noindex, nofollow\n`);fs.writeFileSync(path.join(out,'build.json'),JSON.stringify({app:'Still?',productionBundle:BUNDLE,architecture:'single-load-company-runtime-with-timeout-guard',generatedAt:new Date().toISOString(),runtime,companyScripts,files},null,2)+'\n');console.log(`Built V${BUNDLE}: company modules load once with runtime guard first.`);