(()=>{
  'use strict';
  const $=(selector,root=document)=>root.querySelector(selector);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const hr=()=>$('#language')?.value==='hr'||document.documentElement.lang==='hr';
  const t=(en,hrv)=>hr()?hrv:en;
  const date=value=>value?new Intl.DateTimeFormat(hr()?'hr-HR':'en',{dateStyle:'medium'}).format(new Date(value)):'—';
  const money=cents=>new Intl.NumberFormat(hr()?'hr-HR':'en',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(cents||0)/100);
  const icon=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>`;
  let state=null,selected=null,detail=null,activeTab='overview',searchTimer=0,legacyNode=null;

  const tools=[
    ['inventory',t('Inventory & stock','Zalihe i skladište'),'#companyInventoryLiveV110'],['traceability',t('Lots, serials & traceability','Serije i sljedivost'),'#companyOperationsV96'],['supply',t('Suppliers & purchasing','Dobavljači i nabava'),'#companyOperationsV96'],['repairs',t('Repairs & parts','Popravci i dijelovi'),'#companyOperationsV96'],['returns',t('Returns & disposition','Povrati i raspolaganje'),'#companyOperationsV96'],['warranty',t('Warranty & cases','Jamstva i slučajevi'),'#companyInboxV60'],['orders',t('Orders & fulfilment','Narudžbe i isporuka'),'#companyCommerceV92'],['agreements',t('Agreements & renewals','Ugovori i obnove'),'#companyOperationsV96'],['crm',t('Customers & CRM','Kupci i CRM'),'#businessWorkbenchV72'],['appointments',t('Calendar & appointments','Kalendar i termini'),'#companyOperationsV96'],['recalls',t('Recalls & safety','Opozivi i sigurnost'),'#companyOperationsV96'],['analytics',t('Operational intelligence','Operativni uvidi'),'#businessWorkbenchV72'],['passports',t('Verified Passports','Verificirane Putovnice'),'#companyPassportStudioV83'],['commerce',t('Offers & commerce','Ponude i trgovina'),'#companyCommerceV92'],['services',t('Service operations','Uslužne operacije'),'#companyServicesV73'],['lifecycle',t('Lifecycle & commitments','Životni ciklus i obećanja'),'#companyLifecycleV95'],['inbox',t('Customer inbox','Sandučić kupaca'),'#companyInboxV60'],['rewards',t('Rewards','Nagrade'),'#companyRewardsV75'],['branches',t('Branches','Poslovnice'),'#branchCenterV68'],['verification',t('Company verification','Verifikacija tvrtke'),'.cp46-verify'],['integrations',t('Webhooks & integrations','Webhookovi i integracije'),'#companyInboxV60'],['dailyOperations',t('Daily operations','Dnevne operacije'),'#businessWorkbenchV72'],['deliveryControl',t('Delivery control','Kontrola isporuke'),'#companyOpsV74'],['capacity',t('Capacity & resources','Kapaciteti i resursi'),'#companyServicesV73'],['customer360',t('Customer 360','Kupac 360'),'#businessWorkbenchV72'],['automation',t('Playbooks & follow-up','Playbookovi i praćenje'),'#companyOpsV74'],['supplierClaims',t('Supplier claims','Zahtjevi dobavljačima'),'#companyOpsV74'],['notifications',t('Notifications','Obavijesti'),'#companyNotifyV69'],['b2bAssets',t('Business assets','Poslovna imovina'),'#companyLifecycleV95'],['esl',t('Electronic shelf labels','Elektroničke cijene'),'#electronicShelfLabelsV106'],['controlCenter',t('Company control center','Kontrolni centar tvrtke'),'#companyControlCenterV101'],['retailerProfile',t('Retailer identity','Identitet trgovca'),'#cp48Claim'],['caseFollowup',t('Case collaboration','Suradnja na slučaju'),'#companyInboxV60']
  ];
  const toolGroups=[
    ['operate',t('Operate','Operacije'),['inventory','traceability','supply','dailyOperations','deliveryControl','capacity','appointments','b2bAssets','esl']],
    ['sell',t('Sell','Prodaja'),['orders','commerce','agreements','rewards','branches']],
    ['serve',t('Serve','Podrška'),['repairs','returns','warranty','services','inbox','caseFollowup','customer360','crm']],
    ['trust',t('Trust','Povjerenje'),['passports','lifecycle','recalls','verification','retailerProfile','supplierClaims']],
    ['grow',t('Grow','Rast'),['analytics','controlCenter','automation','integrations','notifications']]
  ];
  const toolFocus={traceability:'inventory',supply:'supply',repairs:'service',returns:'service',agreements:'sales',appointments:'schedule',recalls:'insights',crm:'customers',customer360:'customers',dailyOperations:'today'};

  async function api(path,options={}){
    const method=options.method||'GET';
    const headers={accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})};
    if(method!=='GET')headers['idempotency-key']=crypto.randomUUID();
    const response=await fetch(path,{credentials:'same-origin',...options,method,headers});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw Object.assign(new Error(data.error||`HTTP ${response.status}`),{status:response.status,data});
    return data;
  }
  function severityLabel(value){return({critical:t('Critical','Kritično'),high:t('Attention','Pažnja'),normal:t('Watch','Praćenje'),low:t('Low','Nisko')})[value]||value}
  function typeLabel(value){return String(value||'object').replaceAll('_',' ')}
  function sourceLabel(value){return({companyos_work_objects:'CompanyOS',ops_products:t('Operations catalogue','Operativni katalog'),ops_locations:t('Operations locations','Operativne lokacije'),ops_suppliers:t('Supplier records','Zapisi dobavljača'),ops_purchase_orders:t('Purchasing','Nabava'),ops_repair_jobs:t('Repair operations','Operacije popravaka'),ops_rmas:t('Returns operations','Operacije povrata'),ops_reservations:t('Order operations','Operacije narudžbi'),ops_agreements:t('Agreements','Ugovori'),ops_staff:t('Team records','Zapisi tima'),ops_appointments:t('Appointments','Termini'),ops_crm_contacts:'CRM',commerce_orders:t('Commerce','Trgovina'),service_engagements:t('Service operations','Uslužne operacije'),consumer_cases:t('Buyer cases','Slučajevi kupaca')})[value]||t('Connected company record','Povezani zapis tvrtke')}
  function toast(message){const node=$('#cos120Toast');if(!node)return;node.textContent=message;node.hidden=false;clearTimeout(node._timer);node._timer=setTimeout(()=>node.hidden=true,3600)}

  function shell(){const unread=state.notifications.filter(item=>!item.read_at).length;return `<section class="cos120" id="companyOSV120" aria-label="CompanyOS">
    <header class="cos120-top"><div class="cos120-brand"><i class="cos120-orb"></i><div><b>CompanyOS</b><small>${t('Your business. Remembered.','Vaše poslovanje. Zapamćeno.')}</small></div></div>
      <button class="cos120-search" type="button" data-cos-search>${icon}<span>${t('Ask CompanyOS anything…','Pitaj CompanyOS bilo što…')}</span><kbd>⌘ K</kbd></button>
      <div class="cos120-account"><button class="cos120-icon cos120-notify" type="button" data-cos-tool="notifications" aria-label="${t('Notifications','Obavijesti')}">♧${unread?`<i>${unread}</i>`:''}</button><button class="cos120-icon" type="button" data-cos-refresh aria-label="${t('Refresh','Osvježi')}">✦</button><span class="cos120-avatar">${esc((state.member.email||'?')[0].toUpperCase())}</span><div class="cos120-user"><b>${esc(state.member.email.split('@')[0])}</b><small>${esc(state.member.role)}</small></div><span class="cos120-chevron">⌄</span></div></header>
    <main class="cos120-main"><div class="cos120-dashboard"><div class="cos120-primary">
      <div class="cos120-welcome"><div><h1>${greeting()}, ${esc(state.organization.name)} <span>👋</span></h1><p>${state.situations.length?t(`Here are ${state.situations.length} situations that need your attention today.`,`Ovdje je ${state.situations.length} situacija koje danas traže pažnju.`):t('Your current company records show no urgent situations.','Trenutačni zapisi tvrtke ne pokazuju hitne situacije.')}</p></div><span class="cos120-state"><i></i>${t('Live company data','Stvarni podaci tvrtke')}</span></div>
      <section class="cos120-attention" id="cos120Attention">${attention()}</section>
      <section class="cos120-workspace" id="cos120Workspace">${workspace()}</section>
      <section class="cos120-objects"><div class="cos120-objects-head"><h2>${t('Your living objects','Vaši živi objekti')}</h2><button class="cos120-view" type="button" data-cos-all>${t('View all','Prikaži sve')} · ${state.livingObjects.length}</button></div><div class="cos120-object-rail">${objectCards(state.livingObjects.slice(0,18))}<button class="cos120-add-object" type="button" data-cos-create="object"><b>＋</b>${t('Add object','Dodaj objekt')}</button></div></section>
    </div><aside class="cos120-side">${pulse()}${memory()}${conversations()}${state.notifications.length?activity():''}</aside></div></main>${dock()}${overlays()}<div class="cos120-toast" id="cos120Toast" hidden></div></section>`}

  function greeting(){const hour=new Date().getHours();if(hour<12)return t('Good morning','Dobro jutro');if(hour<18)return t('Good afternoon','Dobar dan');return t('Good evening','Dobra večer')}

  function attention(){const items=state.situations.slice(0,3);if(!items.length)return `<div class="cos120-empty-attention"><span class="cos120-situation-icon">✓</span><div><small>${t('CURRENT STATUS','TRENUTAČNI STATUS')}</small><b>${t('Nothing urgent is hidden from you.','Ništa hitno nije skriveno.')}</b><p>${t('Still is watching real stock, orders, repairs, renewals, tasks and cases.','Still prati stvarne zalihe, narudžbe, popravke, obnove, zadatke i slučajeve.')}</p></div><button class="cos120-btn" type="button" data-cos-create="situation">${t('Create situation','Izradi situaciju')}</button></div>`;return items.map((item,index)=>`<button class="cos120-situation is-${esc(item.severity)}" type="button" data-cos-situation="${esc(item.publicId)}"><span>${index===0?'♢':index===1?'⚑':'◎'} ${esc(severityLabel(item.severity))}</span><h2>${esc(item.title)}</h2><p>${esc(item.description||item.cause)}</p><em>${t('Open','Otvori')} →</em><i class="cos120-situation-icon">${index===0?'⌁':index===1?'↗':'◇'}</i></button>`).join('')}
  function chooseDefault(){if(selected)return selected;const situation=state.situations[0];if(situation)return{mode:'situation',...situation};const object=state.livingObjects[0];return object?{mode:'object',...object}:{mode:'empty'}}
  function workspace(){selected=chooseDefault();if(selected.mode==='empty')return `<div class="cos120-empty-work"><span class="cos120-empty-orbit">＋</span><div><small>${t('LIVING WORKSPACE','ŽIVI RADNI PROSTOR')}</small><h2>${t('Your workspace is ready.','Vaš radni prostor je spreman.')}</h2><p>${t('Create the first real object or connect an existing operational record. Nothing here is sample data.','Izradite prvi stvarni objekt ili povežite postojeći operativni zapis. Ovdje nema oglednih podataka.')}</p><button class="cos120-btn primary" data-cos-create="object">${t('Add first object','Dodaj prvi objekt')}</button><button class="cos120-btn" data-cos-tools>${t('Open all business tools','Otvori sve poslovne alate')}</button></div></div>`;const title=selected.title||selected.id,subtitle=selected.mode==='situation'?`${severityLabel(selected.severity)} · ${typeLabel(selected.kind)}`:`${typeLabel(selected.type)} · ${selected.status}`;return `<div class="cos120-workframe"><aside class="cos120-record-rail">${recordRail(title,subtitle)}</aside><section class="cos120-record-main"><header class="cos120-workhead"><div class="cos120-title"><h2>${esc(title)} ${selected.status?`<i>${esc(selected.status)}</i>`:''}</h2><p>${esc(subtitle)}</p></div><div class="cos120-work-actions">${selected.mode==='situation'?`<button class="cos120-btn" data-cos-resolve="${esc(selected.publicId)}">✓ ${t('Resolve','Riješi')}</button>`:`<button class="cos120-btn" data-cos-event>＋ ${t('Event','Događaj')}</button><button class="cos120-btn primary" data-cos-document>↗ ${t('Attach','Priloži')}</button>`}</div></header>${workspaceTabs()}<div class="cos120-content">${workspaceContent()}</div></section></div>`}

  function workspaceTabs(){return `<nav class="cos120-tabs" aria-label="${t('Object workspace','Radni prostor objekta')}"><button class="${activeTab==='overview'?'active':''}" data-cos-tab="overview">${t('Overview','Pregled')}</button><button data-cos-tool="repairs">${t('Repairs','Popravci')}</button><button class="${activeTab==='documents'?'active':''}" data-cos-tab="documents">${t('Documents','Dokumenti')}</button><button data-cos-tool="inventory">${t('Parts','Dijelovi')}</button><button data-cos-tool="customer360">${t('Customer','Kupac')}</button><button data-cos-tool="warranty">${t('Warranty','Jamstvo')}</button><button class="${activeTab==='timeline'?'active':''}" data-cos-tab="timeline">${t('History','Povijest')}</button><button data-cos-assistant>${t('AI insights','AI uvidi')}</button><button data-cos-tools>••• ${t('More','Više')}</button></nav>`}

  function recordRail(title,subtitle){const events=selected.mode==='object'?(detail?.events||[]):[];const linked=selected.mode==='situation'?(selected.objects||[]):[];const timeline=events.slice(0,5).map(item=>`<li><i></i><time>${date(item.occurred_at)}</time><b>${esc(item.title)}</b><small>${esc(typeLabel(item.event_type))}</small></li>`).join('');const links=linked.slice(0,5).map(item=>`<li><i></i><b>${esc(typeLabel(item.type))}</b><small>${esc(item.id)}</small></li>`).join('');return `<button class="cos120-all-objects" type="button" data-cos-all>‹ ${t('All objects','Svi objekti')}</button><div class="cos120-record-hero"><span class="cos120-object-mark">${esc((selected.type||selected.kind||'SI').slice(0,3))}</span><h3>${esc(title)}</h3><p>${esc(subtitle)}</p></div><ol class="cos120-mini-timeline">${timeline||links||`<li class="empty"><i></i><b>${t('No history yet','Još nema povijesti')}</b><small>${t('Real events will appear here.','Stvarni događaji pojavit će se ovdje.')}</small></li>`}</ol>${selected.mode==='object'?`<button class="cos120-timeline-link" data-cos-tab="timeline">▣ ${t('Timeline view','Prikaz vremenske crte')}</button>`:''}`}

  function workspaceContent(){if(selected.mode==='situation')return situationView();if(!detail)return `<div class="cos120-zero">${t('Loading authorized record…','Učitavanje ovlaštenog zapisa…')}</div>`;if(activeTab==='timeline')return listPanel(t('Attributable timeline','Pripisiva vremenska crta'),detail.events||[],item=>[item.title,item.event_type,date(item.occurred_at)]);if(activeTab==='documents')return listPanel(t('Connected documents','Povezani dokumenti'),detail.documents||[],item=>[item.title,item.document_type,date(item.created_at)]);if(activeTab==='relationships')return listPanel(t('Object relationships','Odnosi objekta'),detail.relationships||[],item=>[item.relationship,`${item.from_type}:${item.from_public_id} → ${item.to_type}:${item.to_public_id}`,date(item.created_at)]);return objectOverview()}
  function situationView(){return `<div class="cos120-grid"><section class="cos120-panel"><h3>${t('Current situation','Trenutačna situacija')} <span class="cos120-ok">◎</span></h3><p>${esc(selected.description||t('No additional description recorded.','Nema dodatno zabilježenog opisa.'))}</p><div class="cos120-facts"><div class="cos120-fact"><span>${t('Cause','Uzrok')}</span><b>${esc(selected.cause||'—')}</b></div><div class="cos120-fact"><span>${t('Status','Status')}</span><b>${esc(selected.status)}</b></div></div></section><section class="cos120-panel"><h3>${t('Recommended next actions','Preporučene sljedeće radnje')}</h3><div class="cos120-list">${(selected.recommendedActions||[]).map(action=>`<div class="cos120-row"><i></i><div><b>${esc(action)}</b><small>${t('Connected real workflow','Povezani stvarni tijek rada')}</small></div></div>`).join('')||`<div class="cos120-zero">${t('No suggested action','Nema predložene radnje')}</div>`}</div></section><section class="cos120-panel cos120-quick"><h3>${t('Quick actions','Brze radnje')}</h3><button data-cos-resolve="${esc(selected.publicId)}">✓ ${t('Resolve situation','Riješi situaciju')}</button><button data-cos-tools>⌕ ${t('Find connected tool','Pronađi povezani alat')}</button><button data-cos-create="situation">＋ ${t('Create related situation','Izradi povezanu situaciju')}</button></section><section class="cos120-panel wide"><h3>${t('Affected objects','Pogođeni objekti')}</h3>${objectCards((selected.objects||[]).map(link=>state.livingObjects.find(object=>object.type===link.type&&object.id===link.id)).filter(Boolean))||`<div class="cos120-zero">${t('No object is linked yet.','Još nije povezan nijedan objekt.')}</div>`}</section></div>`}
  function objectOverview(){const object=detail.object;const facts=[['ID',object.id],[t('Type','Vrsta'),typeLabel(object.type)],[t('Status','Status'),object.status],[t('Source','Izvor'),sourceLabel(object.source)],[t('Updated','Ažurirano'),date(object.updatedAt)]];return `<div class="cos120-grid"><section class="cos120-panel"><h3>${t('Current situation','Trenutačna situacija')} <span class="cos120-ok">✓</span></h3><p>${esc(object.subtitle||t('No issue is recorded for this object.','Za ovaj objekt nije zabilježen problem.'))}</p><div class="cos120-facts">${facts.slice(0,4).map(([label,value])=>`<div class="cos120-fact"><span>${esc(label)}</span><b>${esc(value||'—')}</b></div>`).join('')}</div></section><section class="cos120-panel"><h3>${t('Record summary','Sažetak zapisa')}</h3><div class="cos120-summary-list"><p>✓ ${detail.events.length} ${t('attributable events','pripisivih događaja')}</p><p>✓ ${detail.documents.length} ${t('connected documents','povezanih dokumenata')}</p><p>✓ ${detail.relationships.length} ${t('object relationships','odnosa objekta')}</p><p>✓ ${detail.audit.length} ${t('audit entries','revizijskih zapisa')}</p></div><small>${t('Last updated','Posljednje ažuriranje')}: ${date(object.updatedAt)}</small></section><section class="cos120-panel cos120-quick"><h3>${t('Quick actions','Brze radnje')}</h3>${quickActions()}</section><section class="cos120-panel wide cos120-history"><h3>${t('Recent history','Nedavna povijest')}</h3>${rows((detail.events||[]).slice(0,6),item=>[item.title,item.event_type,date(item.occurred_at)])}</section></div>`}
  function quickActions(){return `<button data-cos-tool="warranty">♢ ${t('Create warranty claim','Izradi jamstveni zahtjev')}</button><button data-cos-tool="supply">▣ ${t('Order related parts','Naruči povezane dijelove')}</button><button data-cos-tool="appointments">◷ ${t('Schedule follow-up','Zakaži praćenje')}</button><button data-cos-tool="inbox">↗ ${t('Send update to customer','Pošalji ažuriranje kupcu')}</button><button data-cos-event>＋ ${t('Record object event','Zabilježi događaj objekta')}</button>`}
  function listPanel(title,items,map){return `<section class="cos120-panel wide"><h3>${esc(title)}</h3>${rows(items,map)}</section>`}
  function rows(items,map){return items.length?`<div class="cos120-list">${items.map(item=>{const [title,subtitle,when]=map(item);return `<div class="cos120-row"><i></i><div><b>${esc(title)}</b><small>${esc(subtitle||'')}</small></div><time>${esc(when||'')}</time></div>`}).join('')}</div>`:`<div class="cos120-zero"><b>${t('No records yet.','Još nema zapisa.')}</b>${t('New attributable records will appear here.','Novi pripisivi zapisi pojavit će se ovdje.')}</div>`}
  function pulseStatus(value){return({healthy:t('Healthy','Stabilno'),watch:t('Watch','Praćenje'),needs_attention:t('Needs attention','Traži pažnju')})[value]||typeLabel(value)}
  function pulse(){const pulse=state.pulse,summary=pulse.summary,buyerData=state.permissions.buyerFacing&&pulse.buyerData!==false;return `<section class="cos120-pulse"><header><div><span class="cos120-eyebrow">Company Pulse</span><b>${pulseStatus(pulse.status)}</b></div><div class="cos120-health" style="--health:${pulse.health}%"><span>${pulse.health}%</span></div></header><div class="cos120-pulse-copy"><b>${t('Current operational view','Trenutačni operativni pregled')}</b><small>${summary.objects} ${t('connected records','povezanih zapisa')} · ${summary.tasks} ${t('open tasks','otvorenih zadataka')}</small></div><div class="cos120-healthbar" role="meter" aria-label="${t('Company health','Stanje tvrtke')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pulse.health}"><i style="width:${pulse.health}%"></i></div><div class="cos120-kpis"><div class="cos120-kpi"><span>♧ ${t('Recorded order value','Evidentirana vrijednost')}</span><b>${money(summary.recognizedOrderValueCents)}</b></div><div class="cos120-kpi"><span>◇ ${t('Open orders','Otvorene narudžbe')}</span><b>${summary.orders}</b></div><div class="cos120-kpi"><span>⌁ ${t('Open services','Otvorene usluge')}</span><b>${summary.services}</b></div><div class="cos120-kpi${buyerData?'':' is-protected'}"><span>◎ ${t('Buyer cases','Slučajevi kupaca')}</span><b>${buyerData?summary.cases:'—'}</b></div></div><footer><span>${t('Updated','Ažurirano')} ${date(pulse.changedAt)}</span><span>${t('Calculated from live company records','Izračunato iz stvarnih zapisa tvrtke')}</span></footer></section>`}
  function memory(){return `<section class="cos120-memory" id="cos120Assistant"><header><h3>✦ ${t('AI Assistant','AI asistent')}</h3><span>${t('AUTHORIZED SEARCH','OVLAŠTENA PRETRAGA')}</span></header><p>${t('Ask CompanyOS to find patterns and records in data this company is authorized to access. Results are evidence-linked; no sample answer is generated.','Zatražite od CompanyOS-a da pronađe obrasce i zapise u podacima kojima ova tvrtka smije pristupiti. Rezultati su povezani s dokazima; ne generira se ogledni odgovor.')}</p><div class="cos120-assistant-prompts"><button type="button" data-cos-memory-query="repair">${t('Which repairs need attention?','Koji popravci traže pažnju?')}</button><button type="button" data-cos-memory-query="part">${t('Show parts activity','Prikaži aktivnost dijelova')}</button><button type="button" data-cos-memory-query="customer">${t('Which customers have activity?','Koji kupci imaju aktivnost?')}</button></div><form data-cos-memory><input name="q" minlength="2" required placeholder="${t('Ask about company data…','Pitaj o podacima tvrtke…')}"><button aria-label="${t('Search company memory','Pretraži memoriju tvrtke')}">↗</button></form><div class="cos120-memory-results" id="cos120MemoryResults"></div></section>`}
  function conversations(){const closed=new Set(['resolved','closed','archived','cancelled','rejected']),items=state.livingObjects.filter(item=>(item.type==='conversation'||item.type==='case')&&!closed.has(String(item.status).toLowerCase())).slice(0,5);return `<section class="cos120-conversations"><header><div><span class="cos120-eyebrow">${t('CUSTOMER & TEAM','KUPCI I TIM')}</span><h3>${t('Active conversations','Aktivni razgovori')}</h3></div><button type="button" data-cos-conversations>${t('View all','Prikaži sve')}</button></header>${items.length?`<div class="cos120-conversation-list">${items.map(item=>`<button type="button" data-cos-object="${esc(item.type)}:${esc(item.id)}"><i>${esc((item.title||'?').trim().slice(0,1).toUpperCase())}</i><span><b>${esc(item.title)}</b><small>${esc(item.subtitle||item.reference||t('Company conversation','Razgovor tvrtke'))}</small></span><time>${date(item.updatedAt)}</time></button>`).join('')}</div>`:`<div class="cos120-conversation-empty"><span>◌</span><div><b>${t('No active conversations','Nema aktivnih razgovora')}</b><small>${state.permissions.buyerFacing?t('New attributable conversations will appear here.','Novi pripisivi razgovori pojavit će se ovdje.'):t('Buyer conversations unlock after verification. Internal conversations remain available now.','Razgovori s kupcima otključavaju se nakon verifikacije. Interni razgovori dostupni su već sada.')}</small></div><button type="button" data-cos-create="conversation">${t('Start internal conversation','Pokreni interni razgovor')}</button></div>`}</section>`}
  function activity(){const items=state.notifications.slice(0,5);return `<section class="cos120-activity"><header><h3>${t('Recent activity','Nedavna aktivnost')}</h3><button data-cos-tool="notifications">${t('View all','Prikaži sve')}</button></header>${items.length?`<div>${items.map(item=>`<button data-cos-tool="notifications"><i class="is-${esc(item.severity||'normal')}"></i><span><b>${esc(item.title)}</b><small>${esc(item.body||date(item.created_at))}</small></span><time>${date(item.created_at)}</time></button>`).join('')}</div>`:`<div class="cos120-activity-empty"><span>◎</span><b>${t('No notifications yet','Još nema obavijesti')}</b><small>${t('Real company activity will appear here.','Stvarna aktivnost tvrtke pojavit će se ovdje.')}</small></div>`}</section>`}
  function objectCards(items){return items.map(item=>`<button class="cos120-object-card" type="button" data-cos-object="${esc(item.type)}:${esc(item.id)}"><i>${esc(item.type.slice(0,3))}</i><span><b>${esc(item.title)}</b><small>${esc(item.subtitle||item.status)}</small></span></button>`).join('')}
  function dock(){return `<nav class="cos120-dock" aria-label="CompanyOS"><button class="active" data-cos-dock="today"><i>✦</i><span><b>${t('Today','Danas')}</b><small>${state.situations.length} ${t('situations','situacija')}</small></span></button><button data-cos-tool="appointments"><i>◷</i><span><b>${t('Calendar','Kalendar')}</b><small>${t('Appointments','Termini')}</small></span></button><button data-cos-tool="dailyOperations"><i>✓</i><span><b>${t('Tasks','Zadaci')}</b><small>${state.pulse.summary.tasks} ${t('open','otvoreno')}</small></span></button><button class="cos120-create" data-cos-create="object" aria-label="${t('Create','Izradi')}">+</button><button data-cos-tool="notifications"><i>♧</i><span><b>${t('Notifications','Obavijesti')}</b><small>${state.notifications.length} ${t('recent','nedavno')}</small></span></button><button data-cos-tool="analytics"><i>⌁</i><span><b>${t('Reports','Izvještaji')}</b><small>${t('Live data','Stvarni podaci')}</small></span></button><button data-cos-tool="verification"><i>⚙</i><span><b>${t('Settings','Postavke')}</b><small>${esc(state.organization.status)}</small></span></button></nav>`}
  function overlays(){return `<div class="cos120-overlay" id="cos120SearchOverlay" hidden><section class="cos120-dialog cos120-tool-dialog"><header class="cos120-dialog-head">${icon}<input id="cos120SearchInput" autocomplete="off" placeholder="${t('Search all tools and records…','Pretraži sve alate i zapise…')}"><button data-cos-close aria-label="${t('Close','Zatvori')}">×</button></header><div class="cos120-results" id="cos120SearchResults"></div></section></div><div class="cos120-overlay" id="cos120FormOverlay" hidden><section class="cos120-dialog" id="cos120FormDialog"></section></div><section class="cos120-legacy" id="cos120Legacy" hidden><header class="cos120-legacy-bar"><div id="cos120LegacyTitle">${t('Connected tool','Povezani alat')}</div><button class="cos120-btn" data-cos-legacy-close>← ${t('Back to CompanyOS','Natrag u CompanyOS')}</button></header><div class="cos120-legacy-host" id="cos120LegacyHost"></div></section><div id="cos120ToolParking" hidden></div>`}

  async function load(){state=await api('/api/v1/companyos/bootstrap');document.body.classList.add('companyos-live');let root=$('#companyOSV120');if(!root){root=document.createElement('div');root.id='companyOSV120Mount';document.querySelector('.business-shell>main')?.append(root)}root.outerHTML=shell();bind();window.dispatchEvent(new CustomEvent('still:companyos-ready',{detail:{organization:state.organization}}));if(selected?.mode==='object')loadDetail()}
  function rerenderWorkspace(){const node=$('#cos120Workspace');if(node)node.innerHTML=workspace();bindWorkspace()}
  async function loadDetail(){if(selected?.mode!=='object')return;detail=null;rerenderWorkspace();try{detail=await api(`/api/v1/companyos/objects/${encodeURIComponent(selected.type)}/${encodeURIComponent(selected.id)}`);rerenderWorkspace()}catch(error){toast(t('This record could not be opened.','Ovaj zapis nije moguće otvoriti.'))}}
  function selectObject(type,id){const object=state.livingObjects.find(item=>item.type===type&&item.id===id);if(!object)return;selected={mode:'object',...object};detail=null;activeTab='overview';loadDetail();$('#cos120Workspace')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function selectSituation(id){const situation=state.situations.find(item=>item.publicId===id);if(!situation)return;selected={mode:'situation',...situation};detail=null;activeTab='overview';rerenderWorkspace();$('#cos120Workspace')?.scrollIntoView({behavior:'smooth',block:'start'})}

  function bind(){document.querySelectorAll('[data-cos-situation]').forEach(button=>button.onclick=()=>selectSituation(button.dataset.cosSituation));document.querySelectorAll('[data-cos-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.cosObject.split(':');selectObject(type,id.join(':'))});document.querySelectorAll('[data-cos-search]').forEach(button=>button.onclick=openSearch);document.querySelectorAll('[data-cos-close]').forEach(button=>button.onclick=closeOverlays);document.querySelectorAll('[data-cos-refresh]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{selected=null;detail=null;await load();toast(t('Company data refreshed.','Podaci tvrtke osvježeni.'))}finally{button.disabled=false}});document.querySelectorAll('[data-cos-create]').forEach(button=>button.onclick=()=>openCreate(button.dataset.cosCreate));document.querySelectorAll('[data-cos-tool]').forEach(button=>button.onclick=()=>openTool(button.dataset.cosTool));document.querySelectorAll('[data-cos-memory-query]').forEach(button=>button.onclick=()=>runAssistantQuery(button.dataset.cosMemoryQuery));document.querySelectorAll('[data-cos-conversations]').forEach(button=>button.onclick=openConversationSearch);document.querySelectorAll('[data-cos-dock="today"]').forEach(button=>button.onclick=goToday);$('[data-cos-all]')?.addEventListener('click',openSearch);$('[data-cos-memory]')?.addEventListener('submit',memorySearch);bindWorkspace();if(!window.__stillCompanyOSKeyboard){window.__stillCompanyOSKeyboard=true;document.addEventListener('keydown',keyboard)}}
  function bindWorkspace(){document.querySelectorAll('#cos120Workspace [data-cos-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.cosObject.split(':');selectObject(type,id.join(':'))});document.querySelectorAll('#cos120Workspace [data-cos-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.cosTab;rerenderWorkspace()});document.querySelectorAll('#cos120Workspace [data-cos-tool]').forEach(button=>button.onclick=()=>openTool(button.dataset.cosTool));document.querySelectorAll('#cos120Workspace [data-cos-tools]').forEach(button=>button.onclick=openSearch);document.querySelectorAll('#cos120Workspace [data-cos-create]').forEach(button=>button.onclick=()=>openCreate(button.dataset.cosCreate));document.querySelectorAll('#cos120Workspace [data-cos-all]').forEach(button=>button.onclick=openSearch);document.querySelectorAll('#cos120Workspace [data-cos-assistant]').forEach(button=>button.onclick=focusAssistant);$('[data-cos-resolve]')?.addEventListener('click',resolveSituation);$('[data-cos-event]')?.addEventListener('click',()=>openObjectForm('event'));$('[data-cos-document]')?.addEventListener('click',()=>openObjectForm('document'))}
  function focusAssistant(){const assistant=$('#cos120Assistant');assistant?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>assistant?.querySelector('input')?.focus(),260)}
  function runAssistantQuery(query){const form=$('[data-cos-memory]');const input=form?.querySelector('input[name="q"]');if(!form||!input)return;input.value=query;form.requestSubmit()}
  function keyboard(event){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openSearch()}if(event.key==='Escape')closeOverlays()}
  function openSearch(){const overlay=$('#cos120SearchOverlay');overlay.hidden=false;const input=$('#cos120SearchInput');input.value='';renderSearch('');setTimeout(()=>input.focus(),30);input.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>renderSearch(input.value),120)}}
  function openConversationSearch(){openSearch();const input=$('#cos120SearchInput');input.value=state.permissions.buyerFacing?'case':'conversation';renderSearch(input.value)}
  function goToday(){closeOverlays();closeLegacy();document.querySelector('.cos120-welcome')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function renderSearch(query){const q=query.trim().toLocaleLowerCase();const objectResults=state.livingObjects.filter(item=>q&&`${item.title} ${item.subtitle} ${item.type} ${item.id}`.toLocaleLowerCase().includes(q)).slice(0,35);const matches=item=>!q||`${item[0]} ${item[1]} ${categoryFor(item[0])}`.toLocaleLowerCase().includes(q);const grouped=toolGroups.map(group=>({...group,items:group[2].map(id=>tools.find(item=>item[0]===id)).filter(item=>item&&matches(item))})).filter(group=>group.items.length);const toolMarkup=grouped.map(group=>`<section class="cos120-tool-group"><header><span>${esc(group.group)}</span><h3>${esc(group[1])}</h3></header><div>${group.items.map(item=>`<button class="cos120-tool-card" data-search-tool="${esc(item[0])}"><i>${toolIcon(item[0])}</i><span><b>${esc(item[1])}</b><small>${t('Connected production workspace','Povezani produkcijski radni prostor')}</small></span><em>↗</em></button>`).join('')}</div></section>`).join('');$('#cos120SearchResults').innerHTML=`${toolMarkup}${objectResults.length?`<section class="cos120-tool-group cos120-object-results"><header><span>${t('RECORDS','ZAPISI')}</span><h3>${t('Living objects','Živi objekti')}</h3></header><div>${objectResults.map(item=>`<button class="cos120-tool-card" data-search-object="${esc(item.type)}:${esc(item.id)}"><i>${esc(item.type.slice(0,3))}</i><span><b>${esc(item.title)}</b><small>${esc(item.subtitle||item.id)}</small></span><em>↗</em></button>`).join('')}</div></section>`:''}${!grouped.length&&!objectResults.length?`<div class="cos120-zero">${t('No authorized tools or records match.','Nema odgovarajućih ovlaštenih alata ili zapisa.')}</div>`:''}`;document.querySelectorAll('[data-search-tool]').forEach(button=>button.onclick=()=>{closeOverlays();openTool(button.dataset.searchTool)});document.querySelectorAll('[data-search-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.searchObject.split(':');closeOverlays();selectObject(type,id.join(':'))})}
  function categoryFor(id){return toolGroups.find(group=>group[2].includes(id))?.[1]||t('Tools','Alati')}
  function toolIcon(id){return({inventory:'▦',repairs:'⌁',warranty:'♢',customer360:'◎',crm:'◎',orders:'▤',commerce:'◈',services:'⌁',passports:'◇',analytics:'⌁',notifications:'♧',appointments:'◷',esl:'▥'})[id]||'✦'}
  function closeOverlays(){$('#cos120SearchOverlay').hidden=true;$('#cos120FormOverlay').hidden=true}

  function openCreate(kind){const dialog=$('#cos120FormDialog');$('#cos120FormOverlay').hidden=false;if(kind==='situation')dialog.innerHTML=situationForm();else dialog.innerHTML=objectForm(kind==='conversation'?'conversation':'project');bindForm();setTimeout(()=>dialog.querySelector('input')?.focus(),30)}
  function situationForm(){return `<form class="cos120-form" data-form="situation"><h2>${t('Create a real situation','Izradi stvarnu situaciju')}</h2><p>${t('Saved to this company with attribution and audit history.','Sprema se ovoj tvrtki uz pripisivanje i revizijsku povijest.')}</p><div class="cos120-fields"><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="3" maxlength="180"></label><label>${t('Severity','Ozbiljnost')}<select name="severity"><option value="normal">${t('Normal','Normalno')}</option><option value="high">${t('High','Visoko')}</option><option value="critical">${t('Critical','Kritično')}</option><option value="low">${t('Low','Nisko')}</option></select></label><label>${t('Assign to','Dodijeli')}<select name="assignedMemberId"><option value="">${t('Unassigned','Nedodijeljeno')}</option>${state.members.map(member=>`<option value="${esc(member.id)}">${esc(member.email)}</option>`).join('')}</select></label><label class="wide">${t('What is happening?','Što se događa?')}<textarea name="description" maxlength="2000"></textarea></label><label class="wide">${t('Known cause','Poznati uzrok')}<textarea name="cause" maxlength="1200"></textarea></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Create situation','Izradi situaciju')}</button></footer></form>`}
  function objectForm(defaultType='project'){const option=(value,en,hrv)=>`<option value="${value}"${defaultType===value?' selected':''}>${t(en,hrv)}</option>`;return `<form class="cos120-form" data-form="object"><h2>${defaultType==='conversation'?t('Start an attributable conversation','Pokreni pripisivi razgovor'):t('Add a connected work object','Dodaj povezani radni objekt')}</h2><p>${t('This record is stored directly by CompanyOS with company attribution and audit history.','Ovaj zapis CompanyOS sprema izravno uz pripisivanje tvrtki i revizijsku povijest.')}</p><div class="cos120-fields"><label>${t('Type','Vrsta')}<select name="objectType">${option('project','Project','Projekt')}${option('shipment','Shipment','Pošiljka')}${option('document','Document record','Zapis dokumenta')}${option('conversation','Conversation','Razgovor')}${option('campaign','Campaign','Kampanja')}${option('integration','Integration','Integracija')}</select></label><label>${t('Status','Status')}<input name="status" value="active" maxlength="40"></label><label class="wide">${t('Name','Naziv')}<input name="title" required minlength="2" maxlength="180"></label><label class="wide">${t('Context','Kontekst')}<input name="subtitle" maxlength="300"></label><label class="wide">${t('Reference','Referenca')}<input name="reference" maxlength="180"></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Save object','Spremi objekt')}</button></footer></form>`}
  function bindForm(){document.querySelectorAll('#cos120FormDialog [data-cos-close]').forEach(button=>button.onclick=closeOverlays);$('#cos120FormDialog form')?.addEventListener('submit',submitForm)}
  async function submitForm(event){event.preventDefault();const form=event.currentTarget,message=$('.cos120-form-message',form),body=Object.fromEntries(new FormData(form));message.textContent=t('Saving…','Spremanje…');try{const path=form.dataset.form==='situation'?'/api/v1/companyos/situations':'/api/v1/companyos/objects';await api(path,{method:'POST',body:JSON.stringify(body)});closeOverlays();selected=null;detail=null;await load();toast(t('Saved with audit history.','Spremljeno uz revizijsku povijest.'))}catch(error){message.textContent=t('Could not save this record.','Nije moguće spremiti zapis.')}}
  function openObjectForm(kind){if(!detail)return;const dialog=$('#cos120FormDialog');$('#cos120FormOverlay').hidden=false;const object=detail.object;if(kind==='event')dialog.innerHTML=`<form class="cos120-form" data-form="event"><h2>${t('Add attributable event','Dodaj pripisivi događaj')}</h2><div class="cos120-fields"><input type="hidden" name="objectType" value="${esc(object.type)}"><input type="hidden" name="objectId" value="${esc(object.id)}"><label>${t('Event type','Vrsta događaja')}<input name="eventType" required value="note.recorded" minlength="3"></label><label>${t('Occurred at','Vrijeme događaja')}<input name="occurredAt" type="datetime-local"></label><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="2"></label><label class="wide">${t('Details','Detalji')}<textarea name="detailsText"></textarea></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Record event','Zabilježi događaj')}</button></footer></form>`;else dialog.innerHTML=`<form class="cos120-form" data-form="document"><h2>${t('Attach document reference','Priloži referencu dokumenta')}</h2><p>${t('CompanyOS stores metadata or a secure HTTPS link. It does not pretend to upload a file.','CompanyOS sprema metapodatke ili sigurnu HTTPS poveznicu. Ne simulira prijenos datoteke.')}</p><div class="cos120-fields"><input type="hidden" name="objectType" value="${esc(object.type)}"><input type="hidden" name="objectId" value="${esc(object.id)}"><label>${t('Document type','Vrsta dokumenta')}<input name="documentType" required value="record"></label><label>${t('MIME type','MIME vrsta')}<input name="mimeType" placeholder="application/pdf"></label><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="2"></label><label class="wide">${t('Secure HTTPS URL','Sigurna HTTPS poveznica')}<input name="externalUrl" type="url" placeholder="https://"></label><label class="wide">${t('Or internal reference','Ili interna referenca')}<input name="reference"></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Attach reference','Priloži referencu')}</button></footer></form>`;document.querySelectorAll('#cos120FormDialog [data-cos-close]').forEach(button=>button.onclick=closeOverlays);$('#cos120FormDialog form').onsubmit=submitObjectForm}
  async function submitObjectForm(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),message=$('.cos120-form-message',form);message.textContent=t('Saving…','Spremanje…');let path;if(form.dataset.form==='event'){path='/api/v1/companyos/events';data.details={note:data.detailsText||''};delete data.detailsText;if(data.occurredAt)data.occurredAt=new Date(data.occurredAt).toISOString();else delete data.occurredAt}else path='/api/v1/companyos/documents';try{await api(path,{method:'POST',body:JSON.stringify(data)});closeOverlays();await loadDetail();toast(t('Connected record saved.','Povezani zapis je spremljen.'))}catch(error){message.textContent=t('Could not save this record.','Nije moguće spremiti zapis.')}}
  async function resolveSituation(event){const id=event.currentTarget.dataset.cosResolve;try{await api(`/api/v1/companyos/situations/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:'resolved'})});selected=null;detail=null;await load();toast(t('Situation resolved and audited.','Situacija je riješena i zabilježena.'))}catch{toast(t('Situation could not be resolved.','Situaciju nije moguće riješiti.'))}}
  async function memorySearch(event){event.preventDefault();const q=new FormData(event.currentTarget).get('q'),root=$('#cos120MemoryResults');root.innerHTML=`<div class="cos120-zero">${t('Searching authorized company data…','Pretraživanje ovlaštenih podataka tvrtke…')}</div>`;try{const data=await api(`/api/v1/companyos/memory?q=${encodeURIComponent(q)}`);root.innerHTML=data.results.length?`<p class="cos120-memory-answer">${esc(data.answer||t('Matching records found.','Pronađeni su odgovarajući zapisi.'))}</p>`+data.results.slice(0,12).map(item=>`<div class="cos120-memory-item"><b>${esc(item.title)}</b><small>${esc(item.kind)} · ${esc(item.reference||'')} · ${date(item.created_at)}</small></div>`).join(''):`<div class="cos120-zero"><b>${t('No authorized records found.','Nema pronađenih ovlaštenih zapisa.')}</b>${t('Try a reference, customer, repair, part or event name.','Pokušajte s referencom, kupcem, popravkom, dijelom ili nazivom događaja.')}</div>`}catch{root.innerHTML=`<div class="cos120-zero">${t('Assistant search is unavailable.','Pretraga asistenta nije dostupna.')}</div>`}}
  function openTool(id){const tool=tools.find(item=>item[0]===id);if(!tool)return;const target=$(tool[2]);if(!target)return openUnavailableTool(id,tool);const host=$('#cos120LegacyHost'),parking=$('#cos120ToolParking');if(legacyNode&&legacyNode!==target){legacyNode.removeAttribute('data-cos-context');parking.append(legacyNode)}legacyNode=target;target.dataset.cosContext=id;host.replaceChildren(target);openToolShell(id,tool);target.hidden=false;target.style.removeProperty('display');requestAnimationFrame(()=>focusTool(target,id))}
  function openToolShell(id,tool){$('#cos120LegacyTitle').innerHTML=`<span>CompanyOS</span><i>›</i><span>${esc(categoryFor(id))}</span><i>›</i><b>${esc(tool[1])}</b>`;const shell=$('#cos120Legacy');shell.className=`cos120-legacy is-tool-${esc(id)}`;shell.hidden=false}
  function openUnavailableTool(id,tool){const buyerFacing=['warranty','inbox','integrations','retailerProfile','caseFollowup'].includes(id),verificationRequired=buyerFacing&&!state.permissions.buyerFacing,host=$('#cos120LegacyHost');if(legacyNode){$('#cos120ToolParking').append(legacyNode);legacyNode=null}host.innerHTML=`<section class="cos120-availability"><span>${verificationRequired?t('PROTECTED BUYER DATA','ZAŠTIĆENI PODACI KUPACA'):t('PRODUCTION MODULE','PRODUKCIJSKI MODUL')}</span><h2>${esc(tool[1])}</h2><p>${verificationRequired?t('This tool is integrated in CompanyOS. Company verification is required before buyer identities, warranty cases and private conversations can be opened. Your private operational tools remain available.','Ovaj je alat integriran u CompanyOS. Verifikacija tvrtke potrebna je prije otvaranja identiteta kupaca, jamstvenih slučajeva i privatnih razgovora. Vaši privatni operativni alati ostaju dostupni.'):t('The tool is integrated but did not finish loading for this session. Retry without losing your CompanyOS context.','Alat je integriran, ali se nije završio učitavati u ovoj sesiji. Pokušajte ponovno bez gubitka CompanyOS konteksta.')}</p><div>${verificationRequired?`<button class="cos120-btn primary" data-cos-gate-verify>${t('Open verification','Otvori verifikaciju')}</button>`:''}<button class="cos120-btn" data-cos-gate-retry>${t('Retry tool','Pokušaj ponovno')}</button></div></section>`;openToolShell(id,tool);host.querySelector('[data-cos-gate-verify]')?.addEventListener('click',()=>openTool('verification'));host.querySelector('[data-cos-gate-retry]')?.addEventListener('click',()=>{closeLegacy();setTimeout(()=>openTool(id),350)})}
  function focusTool(target,id){const focus=toolFocus[id];if(!focus)return;const selectors=[`[data-co96-tab="${focus}"]`,`[data-tab="${focus}"]`,`[data-cw72-tab="${focus}"]`,`[data-services-tab="${focus}"]`];for(const selector of selectors){const control=target.querySelector(selector);if(control){control.click();break}}}
  function closeLegacy(){const shell=$('#cos120Legacy'),parking=$('#cos120ToolParking');shell.hidden=true;if(legacyNode){legacyNode.removeAttribute('data-cos-context');parking.append(legacyNode);legacyNode=null}}
  document.addEventListener('click',event=>{if(event.target.closest('[data-cos-legacy-close]'))closeLegacy()});
  async function mount(detail){if(!detail?.organization||!document.body.classList.contains('business-page'))return;try{await load()}catch(error){console.error('[Still] CompanyOS failed to load.',error);toast?.(t('CompanyOS could not load authorized company data.','CompanyOS nije mogao učitati ovlaštene podatke tvrtke.'))}}
  window.addEventListener('still:company-authenticated',event=>mount(event.detail));
  window.StillCompanyOS=Object.freeze({openTool,openTools:openSearch,focusAssistant});
  if(window.__stillOrganization)mount({organization:window.__stillOrganization});
})();
