(()=>{
  'use strict';
  const $=(selector,root=document)=>root.querySelector(selector);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const hr=()=>$('#language')?.value==='hr'||document.documentElement.lang==='hr';
  const t=(en,hrv)=>hr()?hrv:en;
  const date=value=>value?new Intl.DateTimeFormat(hr()?'hr-HR':'en',{dateStyle:'medium'}).format(new Date(value)):'—';
  const money=cents=>new Intl.NumberFormat(hr()?'hr-HR':'en',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(cents||0)/100);
  const icon=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>`;
  let state=null,selected=null,detail=null,activeTab='overview',searchTimer=0,legacyNode=null;

  const tools=[
    ['inventory',t('Inventory & stock','Zalihe i skladište'),'#companyInventoryLiveV110'],['traceability',t('Lots, serials & traceability','Serije i sljedivost'),'#companyOperationsV96'],['supply',t('Suppliers & purchasing','Dobavljači i nabava'),'#companyOperationsV96'],['repairs',t('Repairs & parts','Popravci i dijelovi'),'#companyOperationsV96'],['returns',t('Returns & disposition','Povrati i raspolaganje'),'#companyOperationsV96'],['warranty',t('Warranty & cases','Jamstva i slučajevi'),'#companyInboxV60'],['orders',t('Orders & fulfilment','Narudžbe i isporuka'),'#companyCommerceV92'],['agreements',t('Agreements & renewals','Ugovori i obnove'),'#companyOperationsV96'],['crm',t('Customers & CRM','Kupci i CRM'),'#businessWorkbenchV72'],['appointments',t('Calendar & appointments','Kalendar i termini'),'#companyOperationsV96'],['recalls',t('Recalls & safety','Opozivi i sigurnost'),'#companyOperationsV96'],['analytics',t('Operational intelligence','Operativni uvidi'),'#businessWorkbenchV72'],['passports',t('Verified Passports','Verificirane Putovnice'),'#companyPassportStudioV83'],['commerce',t('Offers & commerce','Ponude i trgovina'),'#companyCommerceV92'],['services',t('Service operations','Uslužne operacije'),'#companyServicesV73'],['lifecycle',t('Lifecycle & commitments','Životni ciklus i obećanja'),'#companyLifecycleV95'],['inbox',t('Customer inbox','Sandučić kupaca'),'#companyInboxV60'],['rewards',t('Rewards','Nagrade'),'#companyRewardsV75'],['branches',t('Branches','Poslovnice'),'#branchCenterV68'],['verification',t('Company verification','Verifikacija tvrtke'),'.cp46-verify'],['integrations',t('Webhooks & integrations','Webhookovi i integracije'),'#companyInboxV60'],['dailyOperations',t('Daily operations','Dnevne operacije'),'#businessWorkbenchV72'],['deliveryControl',t('Delivery control','Kontrola isporuke'),'#companyOpsV74'],['capacity',t('Capacity & resources','Kapaciteti i resursi'),'#companyServicesV73'],['customer360',t('Customer 360','Kupac 360'),'#businessWorkbenchV72'],['automation',t('Playbooks & follow-up','Playbookovi i praćenje'),'#companyOpsV74'],['supplierClaims',t('Supplier claims','Zahtjevi dobavljačima'),'#companyOpsV74'],['notifications',t('Notifications','Obavijesti'),'#companyNotifyV69'],['b2bAssets',t('Business assets','Poslovna imovina'),'#companyLifecycleV95'],['esl',t('Electronic shelf labels','Elektroničke cijene'),'#electronicShelfLabelsV106']
  ];

  async function api(path,options={}){
    const method=options.method||'GET';
    const headers={accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})};
    if(method!=='GET')headers['idempotency-key']=crypto.randomUUID();
    const response=await fetch(path,{credentials:'same-origin',...options,method,headers});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw Object.assign(new Error(data.error||`HTTP ${response.status}`),{status:response.status,data});
    return data;
  }
  function severityLabel(value){return({critical:t('Critical','Kritično'),high:t('Attention','Pažnja'),normal:t('Watch','Praćenje'),low:t('Low','Nisko')})[value]||value}
  function typeLabel(value){return String(value||'object').replaceAll('_',' ')}
  function toast(message){const node=$('#cos120Toast');if(!node)return;node.textContent=message;node.hidden=false;clearTimeout(node._timer);node._timer=setTimeout(()=>node.hidden=true,3600)}

  function shell(){return `<section class="cos120" id="companyOSV120" aria-label="CompanyOS">
    <header class="cos120-top"><div class="cos120-brand"><i class="cos120-orb"></i><div><b>CompanyOS</b><small>${esc(state.organization.name)} · ${t('Your business. Remembered.','Vaše poslovanje. Zapamćeno.')}</small></div></div>
      <button class="cos120-search" type="button" data-cos-search>${icon}<span>${t('Search your company or open a tool…','Pretraži tvrtku ili otvori alat…')}</span><kbd>⌘ K</kbd></button>
      <div class="cos120-account"><button class="cos120-icon" type="button" data-cos-refresh aria-label="${t('Refresh','Osvježi')}">↻</button><span class="cos120-avatar">${esc((state.member.email||'?')[0].toUpperCase())}</span><div class="cos120-user"><b>${esc(state.member.email.split('@')[0])}</b><small>${esc(state.member.role)} · ${esc(state.organization.status)}</small></div></div></header>
    <main class="cos120-main"><div class="cos120-welcome"><div><h1>${t('Good day','Dobar dan')}, ${esc(state.organization.name)}.</h1><p>${state.situations.length?t(`Here are ${state.situations.length} situations that need attention.`,`Ovdje je ${state.situations.length} situacija koje traže pažnju.`):t('Your current company records show no urgent situations.','Trenutačni zapisi tvrtke ne pokazuju hitne situacije.')}</p></div><span class="cos120-state"><i></i>${t('Live company data','Stvarni podaci tvrtke')}</span></div>
      <section class="cos120-attention" id="cos120Attention">${attention()}</section>
      <div class="cos120-layout"><section class="cos120-workspace" id="cos120Workspace">${workspace()}</section><aside class="cos120-side">${pulse()}${memory()}</aside></div>
      <section class="cos120-objects"><div class="cos120-objects-head"><h2>${t('Your living objects','Vaši živi objekti')}</h2><button class="cos120-btn" type="button" data-cos-all>${t('View all','Prikaži sve')} (${state.livingObjects.length})</button></div><div class="cos120-object-rail">${objectCards(state.livingObjects.slice(0,18))}</div></section>
    </main>${dock()}${overlays()}<div class="cos120-toast" id="cos120Toast" hidden></div></section>`}

  function attention(){const items=state.situations.slice(0,3);if(!items.length)return `<div class="cos120-empty-attention"><div><b>${t('Nothing urgent is hidden from you.','Ništa hitno nije skriveno.')}</b><p>${t('Situations appear from real stock, orders, repairs, renewals, tasks and cases.','Situacije nastaju iz stvarnih zaliha, narudžbi, popravaka, obnova, zadataka i slučajeva.')}</p></div><button class="cos120-btn primary" type="button" data-cos-create="situation">${t('Create situation','Izradi situaciju')}</button></div>`;return items.map(item=>`<button class="cos120-situation is-${esc(item.severity)}" type="button" data-cos-situation="${esc(item.publicId)}"><span>◇ ${esc(severityLabel(item.severity))} · ${esc(typeLabel(item.kind))}</span><h2>${esc(item.title)}</h2><p>${esc(item.description||item.cause)}</p><em>${t('Open','Otvori')} →</em></button>`).join('')}
  function chooseDefault(){if(selected)return selected;const situation=state.situations[0];if(situation)return{mode:'situation',...situation};const object=state.livingObjects[0];return object?{mode:'object',...object}:{mode:'empty'}}
  function workspace(){selected=chooseDefault();if(selected.mode==='empty')return `<div class="cos120-zero"><b>${t('Your workspace is ready.','Vaš radni prostor je spreman.')}</b>${t('Create the first real object or connect an existing operational record.','Izradite prvi stvarni objekt ili povežite postojeći operativni zapis.')}<br><button class="cos120-btn primary" data-cos-create="object">${t('Add object','Dodaj objekt')}</button></div>`;const title=selected.title||selected.id,subtitle=selected.mode==='situation'?`${severityLabel(selected.severity)} · ${typeLabel(selected.kind)}`:`${typeLabel(selected.type)} · ${selected.status}`;return `<header class="cos120-workhead"><span class="cos120-object-mark">${esc((selected.type||selected.kind||'SI').slice(0,2))}</span><div class="cos120-title"><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><div class="cos120-work-actions">${selected.mode==='situation'?`<button class="cos120-btn" data-cos-resolve="${esc(selected.publicId)}">${t('Resolve','Riješi')}</button>`:`<button class="cos120-btn" data-cos-event>${t('Add event','Dodaj događaj')}</button><button class="cos120-btn primary" data-cos-document>${t('Attach','Priloži')}</button>`}</div></header><nav class="cos120-tabs"><button class="${activeTab==='overview'?'active':''}" data-cos-tab="overview">${t('Overview','Pregled')}</button><button class="${activeTab==='timeline'?'active':''}" data-cos-tab="timeline">${t('Timeline','Vremenska crta')}</button><button class="${activeTab==='documents'?'active':''}" data-cos-tab="documents">${t('Documents','Dokumenti')}</button><button class="${activeTab==='relationships'?'active':''}" data-cos-tab="relationships">${t('Relationships','Odnosi')}</button><button data-cos-tools>${t('Tools','Alati')} · ${tools.length}</button></nav><div class="cos120-content">${workspaceContent()}</div>`}

  function workspaceContent(){if(selected.mode==='situation')return situationView();if(!detail)return `<div class="cos120-zero">${t('Loading authorized record…','Učitavanje ovlaštenog zapisa…')}</div>`;if(activeTab==='timeline')return listPanel(t('Attributable timeline','Pripisiva vremenska crta'),detail.events||[],item=>[item.title,item.event_type,date(item.occurred_at)]);if(activeTab==='documents')return listPanel(t('Connected documents','Povezani dokumenti'),detail.documents||[],item=>[item.title,item.document_type,date(item.created_at)]);if(activeTab==='relationships')return listPanel(t('Object relationships','Odnosi objekta'),detail.relationships||[],item=>[item.relationship,`${item.from_type}:${item.from_public_id} → ${item.to_type}:${item.to_public_id}`,date(item.created_at)]);return objectOverview()}
  function situationView(){return `<div class="cos120-grid"><section class="cos120-panel"><h3>${t('Current situation','Trenutačna situacija')}</h3><p>${esc(selected.description||'')}</p><div class="cos120-facts"><div class="cos120-fact"><span>${t('Cause','Uzrok')}</span><b>${esc(selected.cause||'—')}</b></div><div class="cos120-fact"><span>${t('Status','Status')}</span><b>${esc(selected.status)}</b></div></div></section><section class="cos120-panel"><h3>${t('Recommended next actions','Preporučene sljedeće radnje')}</h3><div class="cos120-list">${(selected.recommendedActions||[]).map(action=>`<div class="cos120-row"><i></i><div><b>${esc(action)}</b><small>${t('Opens the connected real workflow','Otvara povezani stvarni tijek rada')}</small></div></div>`).join('')||`<div class="cos120-zero">${t('No suggested action','Nema predložene radnje')}</div>`}</div></section><section class="cos120-panel wide"><h3>${t('Affected objects','Pogođeni objekti')}</h3>${objectCards((selected.objects||[]).map(link=>state.livingObjects.find(object=>object.type===link.type&&object.id===link.id)).filter(Boolean))||`<div class="cos120-zero">${t('No object is linked yet.','Još nije povezan nijedan objekt.')}</div>`}</section></div>`}
  function objectOverview(){const object=detail.object;const facts=[['ID',object.id],[t('Type','Vrsta'),typeLabel(object.type)],[t('Status','Status'),object.status],[t('Source','Izvor'),object.source],[t('Updated','Ažurirano'),date(object.updatedAt)]];return `<div class="cos120-grid"><section class="cos120-panel"><h3>${t('Authorized business record','Ovlašteni poslovni zapis')}</h3><div class="cos120-facts">${facts.map(([label,value])=>`<div class="cos120-fact"><span>${esc(label)}</span><b>${esc(value||'—')}</b></div>`).join('')}</div></section><section class="cos120-panel"><h3>${t('Current context','Trenutačni kontekst')}</h3><p>${esc(object.subtitle||t('No additional context recorded.','Nema dodatno zabilježenog konteksta.'))}</p><div class="cos120-facts"><div class="cos120-fact"><span>${t('Events','Događaji')}</span><b>${detail.events.length}</b></div><div class="cos120-fact"><span>${t('Documents','Dokumenti')}</span><b>${detail.documents.length}</b></div><div class="cos120-fact"><span>${t('Relationships','Odnosi')}</span><b>${detail.relationships.length}</b></div><div class="cos120-fact"><span>${t('Audit entries','Revizijski zapisi')}</span><b>${detail.audit.length}</b></div></div></section><section class="cos120-panel wide"><h3>${t('Recent history','Nedavna povijest')}</h3>${rows((detail.events||[]).slice(0,6),item=>[item.title,item.event_type,date(item.occurred_at)])}</section></div>`}
  function listPanel(title,items,map){return `<section class="cos120-panel wide"><h3>${esc(title)}</h3>${rows(items,map)}</section>`}
  function rows(items,map){return items.length?`<div class="cos120-list">${items.map(item=>{const [title,subtitle,when]=map(item);return `<div class="cos120-row"><i></i><div><b>${esc(title)}</b><small>${esc(subtitle||'')}</small></div><time>${esc(when||'')}</time></div>`}).join('')}</div>`:`<div class="cos120-zero"><b>${t('No records yet.','Još nema zapisa.')}</b>${t('New attributable records will appear here.','Novi pripisivi zapisi pojavit će se ovdje.')}</div>`}
  function pulse(){const pulse=state.pulse,summary=pulse.summary;return `<section class="cos120-pulse"><header><b>Company Pulse</b><span class="cos120-pulse-status">${esc(pulse.status.replaceAll('_',' '))}</span></header><div class="cos120-health" style="--health:${pulse.health}%">${pulse.health}%</div><div class="cos120-kpis"><div class="cos120-kpi"><span>${t('Open situations','Otvorene situacije')}</span><b>${summary.situations}</b></div><div class="cos120-kpi"><span>${t('Orders in progress','Narudžbe u tijeku')}</span><b>${summary.orders}</b></div><div class="cos120-kpi"><span>${t('Open services','Otvorene usluge')}</span><b>${summary.services}</b></div><div class="cos120-kpi"><span>${t('Open buyer cases','Otvoreni slučajevi kupaca')}</span><b>${summary.cases}</b></div><div class="cos120-kpi"><span>${t('Recorded order value','Evidentirana vrijednost narudžbi')}</span><b>${money(summary.recognizedOrderValueCents)}</b></div></div></section>`}
  function memory(){return `<section class="cos120-memory"><h3>${t('Company Memory','Memorija tvrtke')}</h3><p>${t('Search only authorized records from this company. Results are deterministic, not generated.','Pretražuje samo ovlaštene zapise ove tvrtke. Rezultati su deterministički, nisu generirani.')}</p><form data-cos-memory><input name="q" minlength="2" required placeholder="${t('Repair, customer, reference…','Popravak, kupac, referenca…')}"><button aria-label="${t('Search memory','Pretraži memoriju')}">↗</button></form><div class="cos120-memory-results" id="cos120MemoryResults"></div></section>`}
  function objectCards(items){return items.map(item=>`<button class="cos120-object-card" type="button" data-cos-object="${esc(item.type)}:${esc(item.id)}"><i>${esc(item.type.slice(0,3))}</i><span><b>${esc(item.title)}</b><small>${esc(item.subtitle||item.status)}</small></span></button>`).join('')}
  function dock(){return `<nav class="cos120-dock" aria-label="CompanyOS"><button class="active" data-cos-dock="today"><b>${t('Today','Danas')}</b><span>${state.situations.length} ${t('situations','situacija')}</span></button><button data-cos-tool="appointments"><b>${t('Calendar','Kalendar')}</b><span>${t('Real appointments','Stvarni termini')}</span></button><button data-cos-tool="dailyOperations"><b>${t('Tasks','Zadaci')}</b><span>${state.pulse.summary.tasks} ${t('open','otvoreno')}</span></button><button class="cos120-create" data-cos-create="object" aria-label="${t('Create','Izradi')}">+</button><button data-cos-tool="notifications"><b>${t('Notifications','Obavijesti')}</b><span>${state.notifications.length} ${t('recent','nedavno')}</span></button><button data-cos-tool="analytics"><b>${t('Reports','Izvještaji')}</b><span>${t('Live data','Stvarni podaci')}</span></button><button data-cos-tool="verification"><b>${t('Settings','Postavke')}</b><span>${esc(state.organization.status)}</span></button></nav>`}
  function overlays(){return `<div class="cos120-overlay" id="cos120SearchOverlay" hidden><section class="cos120-dialog"><header class="cos120-dialog-head">${icon}<input id="cos120SearchInput" autocomplete="off" placeholder="${t('Search objects and tools…','Pretraži objekte i alate…')}"><button data-cos-close aria-label="${t('Close','Zatvori')}">×</button></header><div class="cos120-results" id="cos120SearchResults"></div></section></div><div class="cos120-overlay" id="cos120FormOverlay" hidden><section class="cos120-dialog" id="cos120FormDialog"></section></div><section class="cos120-legacy" id="cos120Legacy" hidden><header class="cos120-legacy-bar"><b id="cos120LegacyTitle">${t('Connected tool','Povezani alat')}</b><button class="cos120-btn" data-cos-legacy-close>${t('Back to CompanyOS','Natrag u CompanyOS')} ×</button></header><div class="cos120-legacy-host" id="cos120LegacyHost"></div></section>`}

  async function load(){state=await api('/api/v1/companyos/bootstrap');document.body.classList.add('companyos-live');let root=$('#companyOSV120');if(!root){root=document.createElement('div');root.id='companyOSV120Mount';document.querySelector('.business-shell>main')?.append(root)}root.outerHTML=shell();bind();if(selected?.mode==='object')loadDetail()}
  function rerenderWorkspace(){const node=$('#cos120Workspace');if(node)node.innerHTML=workspace();bindWorkspace()}
  async function loadDetail(){if(selected?.mode!=='object')return;detail=null;rerenderWorkspace();try{detail=await api(`/api/v1/companyos/objects/${encodeURIComponent(selected.type)}/${encodeURIComponent(selected.id)}`);rerenderWorkspace()}catch(error){toast(t('This record could not be opened.','Ovaj zapis nije moguće otvoriti.'))}}
  function selectObject(type,id){const object=state.livingObjects.find(item=>item.type===type&&item.id===id);if(!object)return;selected={mode:'object',...object};detail=null;activeTab='overview';loadDetail();$('#cos120Workspace')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function selectSituation(id){const situation=state.situations.find(item=>item.publicId===id);if(!situation)return;selected={mode:'situation',...situation};detail=null;activeTab='overview';rerenderWorkspace();$('#cos120Workspace')?.scrollIntoView({behavior:'smooth',block:'start'})}

  function bind(){document.querySelectorAll('[data-cos-situation]').forEach(button=>button.onclick=()=>selectSituation(button.dataset.cosSituation));document.querySelectorAll('[data-cos-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.cosObject.split(':');selectObject(type,id.join(':'))});document.querySelectorAll('[data-cos-search]').forEach(button=>button.onclick=openSearch);document.querySelectorAll('[data-cos-close]').forEach(button=>button.onclick=closeOverlays);document.querySelectorAll('[data-cos-refresh]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{selected=null;detail=null;await load();toast(t('Company data refreshed.','Podaci tvrtke osvježeni.'))}finally{button.disabled=false}});document.querySelectorAll('[data-cos-create]').forEach(button=>button.onclick=()=>openCreate(button.dataset.cosCreate));document.querySelectorAll('[data-cos-tool]').forEach(button=>button.onclick=()=>openTool(button.dataset.cosTool));$('[data-cos-all]')?.addEventListener('click',openSearch);$('[data-cos-memory]')?.addEventListener('submit',memorySearch);bindWorkspace();if(!window.__stillCompanyOSKeyboard){window.__stillCompanyOSKeyboard=true;document.addEventListener('keydown',keyboard)}}
  function bindWorkspace(){document.querySelectorAll('#cos120Workspace [data-cos-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.cosObject.split(':');selectObject(type,id.join(':'))});document.querySelectorAll('[data-cos-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.cosTab;rerenderWorkspace()});$('[data-cos-tools]')?.addEventListener('click',openSearch);$('[data-cos-resolve]')?.addEventListener('click',resolveSituation);$('[data-cos-event]')?.addEventListener('click',()=>openObjectForm('event'));$('[data-cos-document]')?.addEventListener('click',()=>openObjectForm('document'))}
  function keyboard(event){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openSearch()}if(event.key==='Escape')closeOverlays()}
  function openSearch(){const overlay=$('#cos120SearchOverlay');overlay.hidden=false;const input=$('#cos120SearchInput');input.value='';renderSearch('');setTimeout(()=>input.focus(),30);input.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>renderSearch(input.value),120)}}
  function renderSearch(query){const q=query.trim().toLocaleLowerCase();const objectResults=state.livingObjects.filter(item=>!q||`${item.title} ${item.subtitle} ${item.type} ${item.id}`.toLocaleLowerCase().includes(q)).slice(0,35);const toolResults=tools.filter(item=>!q||`${item[0]} ${item[1]}`.toLocaleLowerCase().includes(q)).slice(0,18);$('#cos120SearchResults').innerHTML=`${toolResults.map(item=>`<button class="cos120-result" data-search-tool="${esc(item[0])}"><i>↗</i><span><b>${esc(item[1])}</b><small>${t('Open connected production tool','Otvori povezani produkcijski alat')}</small></span><em>${t('Tool','Alat')}</em></button>`).join('')}${objectResults.map(item=>`<button class="cos120-result" data-search-object="${esc(item.type)}:${esc(item.id)}"><i>${esc(item.type.slice(0,3))}</i><span><b>${esc(item.title)}</b><small>${esc(item.subtitle||item.id)}</small></span><em>${esc(typeLabel(item.type))}</em></button>`).join('')||(!toolResults?`<div class="cos120-zero">${t('No authorized records match.','Nema odgovarajućih ovlaštenih zapisa.')}</div>`:'')}`;document.querySelectorAll('[data-search-tool]').forEach(button=>button.onclick=()=>{closeOverlays();openTool(button.dataset.searchTool)});document.querySelectorAll('[data-search-object]').forEach(button=>button.onclick=()=>{const [type,...id]=button.dataset.searchObject.split(':');closeOverlays();selectObject(type,id.join(':'))})}
  function closeOverlays(){$('#cos120SearchOverlay').hidden=true;$('#cos120FormOverlay').hidden=true}

  function openCreate(kind){const dialog=$('#cos120FormDialog');$('#cos120FormOverlay').hidden=false;if(kind==='situation')dialog.innerHTML=situationForm();else dialog.innerHTML=objectForm();bindForm();setTimeout(()=>dialog.querySelector('input')?.focus(),30)}
  function situationForm(){return `<form class="cos120-form" data-form="situation"><h2>${t('Create a real situation','Izradi stvarnu situaciju')}</h2><p>${t('Saved to this company with attribution and audit history.','Sprema se ovoj tvrtki uz pripisivanje i revizijsku povijest.')}</p><div class="cos120-fields"><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="3" maxlength="180"></label><label>${t('Severity','Ozbiljnost')}<select name="severity"><option value="normal">${t('Normal','Normalno')}</option><option value="high">${t('High','Visoko')}</option><option value="critical">${t('Critical','Kritično')}</option><option value="low">${t('Low','Nisko')}</option></select></label><label>${t('Assign to','Dodijeli')}<select name="assignedMemberId"><option value="">${t('Unassigned','Nedodijeljeno')}</option>${state.members.map(member=>`<option value="${esc(member.id)}">${esc(member.email)}</option>`).join('')}</select></label><label class="wide">${t('What is happening?','Što se događa?')}<textarea name="description" maxlength="2000"></textarea></label><label class="wide">${t('Known cause','Poznati uzrok')}<textarea name="cause" maxlength="1200"></textarea></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Create situation','Izradi situaciju')}</button></footer></form>`}
  function objectForm(){return `<form class="cos120-form" data-form="object"><h2>${t('Add a connected work object','Dodaj povezani radni objekt')}</h2><p>${t('For operational entities, open the matching production tool. These supplemental object types are stored directly by CompanyOS.','Za operativne entitete otvorite odgovarajući produkcijski alat. Ove dodatne vrste objekata sprema CompanyOS izravno.')}</p><div class="cos120-fields"><label>${t('Type','Vrsta')}<select name="objectType"><option value="project">${t('Project','Projekt')}</option><option value="shipment">${t('Shipment','Pošiljka')}</option><option value="document">${t('Document record','Zapis dokumenta')}</option><option value="conversation">${t('Conversation','Razgovor')}</option><option value="campaign">${t('Campaign','Kampanja')}</option><option value="integration">${t('Integration','Integracija')}</option></select></label><label>${t('Status','Status')}<input name="status" value="active" maxlength="40"></label><label class="wide">${t('Name','Naziv')}<input name="title" required minlength="2" maxlength="180"></label><label class="wide">${t('Context','Kontekst')}<input name="subtitle" maxlength="300"></label><label class="wide">${t('Reference','Referenca')}<input name="reference" maxlength="180"></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Save object','Spremi objekt')}</button></footer></form>`}
  function bindForm(){document.querySelectorAll('#cos120FormDialog [data-cos-close]').forEach(button=>button.onclick=closeOverlays);$('#cos120FormDialog form')?.addEventListener('submit',submitForm)}
  async function submitForm(event){event.preventDefault();const form=event.currentTarget,message=$('.cos120-form-message',form),body=Object.fromEntries(new FormData(form));message.textContent=t('Saving…','Spremanje…');try{const path=form.dataset.form==='situation'?'/api/v1/companyos/situations':'/api/v1/companyos/objects';await api(path,{method:'POST',body:JSON.stringify(body)});closeOverlays();selected=null;detail=null;await load();toast(t('Saved with audit history.','Spremljeno uz revizijsku povijest.'))}catch(error){message.textContent=t('Could not save this record.','Nije moguće spremiti zapis.')}}
  function openObjectForm(kind){if(!detail)return;const dialog=$('#cos120FormDialog');$('#cos120FormOverlay').hidden=false;const object=detail.object;if(kind==='event')dialog.innerHTML=`<form class="cos120-form" data-form="event"><h2>${t('Add attributable event','Dodaj pripisivi događaj')}</h2><div class="cos120-fields"><input type="hidden" name="objectType" value="${esc(object.type)}"><input type="hidden" name="objectId" value="${esc(object.id)}"><label>${t('Event type','Vrsta događaja')}<input name="eventType" required value="note.recorded" minlength="3"></label><label>${t('Occurred at','Vrijeme događaja')}<input name="occurredAt" type="datetime-local"></label><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="2"></label><label class="wide">${t('Details','Detalji')}<textarea name="detailsText"></textarea></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Record event','Zabilježi događaj')}</button></footer></form>`;else dialog.innerHTML=`<form class="cos120-form" data-form="document"><h2>${t('Attach document reference','Priloži referencu dokumenta')}</h2><p>${t('CompanyOS stores metadata or a secure HTTPS link. It does not pretend to upload a file.','CompanyOS sprema metapodatke ili sigurnu HTTPS poveznicu. Ne simulira prijenos datoteke.')}</p><div class="cos120-fields"><input type="hidden" name="objectType" value="${esc(object.type)}"><input type="hidden" name="objectId" value="${esc(object.id)}"><label>${t('Document type','Vrsta dokumenta')}<input name="documentType" required value="record"></label><label>${t('MIME type','MIME vrsta')}<input name="mimeType" placeholder="application/pdf"></label><label class="wide">${t('Title','Naslov')}<input name="title" required minlength="2"></label><label class="wide">${t('Secure HTTPS URL','Sigurna HTTPS poveznica')}<input name="externalUrl" type="url" placeholder="https://"></label><label class="wide">${t('Or internal reference','Ili interna referenca')}<input name="reference"></label></div><footer><span class="cos120-form-message"></span><button type="button" class="cos120-btn" data-cos-close>${t('Cancel','Odustani')}</button><button class="cos120-btn primary">${t('Attach reference','Priloži referencu')}</button></footer></form>`;document.querySelectorAll('#cos120FormDialog [data-cos-close]').forEach(button=>button.onclick=closeOverlays);$('#cos120FormDialog form').onsubmit=submitObjectForm}
  async function submitObjectForm(event){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),message=$('.cos120-form-message',form);message.textContent=t('Saving…','Spremanje…');let path;if(form.dataset.form==='event'){path='/api/v1/companyos/events';data.details={note:data.detailsText||''};delete data.detailsText;if(data.occurredAt)data.occurredAt=new Date(data.occurredAt).toISOString();else delete data.occurredAt}else path='/api/v1/companyos/documents';try{await api(path,{method:'POST',body:JSON.stringify(data)});closeOverlays();await loadDetail();toast(t('Connected record saved.','Povezani zapis je spremljen.'))}catch(error){message.textContent=t('Could not save this record.','Nije moguće spremiti zapis.')}}
  async function resolveSituation(event){const id=event.currentTarget.dataset.cosResolve;try{await api(`/api/v1/companyos/situations/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:'resolved'})});selected=null;detail=null;await load();toast(t('Situation resolved and audited.','Situacija je riješena i zabilježena.'))}catch{toast(t('Situation could not be resolved.','Situaciju nije moguće riješiti.'))}}
  async function memorySearch(event){event.preventDefault();const q=new FormData(event.currentTarget).get('q'),root=$('#cos120MemoryResults');root.innerHTML=`<div class="cos120-zero">${t('Searching authorized memory…','Pretraživanje ovlaštene memorije…')}</div>`;try{const data=await api(`/api/v1/companyos/memory?q=${encodeURIComponent(q)}`);root.innerHTML=data.results.length?data.results.slice(0,12).map(item=>`<div class="cos120-memory-item"><b>${esc(item.title)}</b><small>${esc(item.kind)} · ${esc(item.reference||'')} · ${date(item.created_at)}</small></div>`).join(''):`<div class="cos120-zero">${t('No authorized records found.','Nema pronađenih ovlaštenih zapisa.')}</div>`}catch{root.innerHTML=`<div class="cos120-zero">${t('Search is unavailable.','Pretraga nije dostupna.')}</div>`}}
  function openTool(id){const tool=tools.find(item=>item[0]===id);if(!tool)return;const target=$(tool[2]);if(!target){toast(t('This production tool has not finished loading. Try again.','Ovaj produkcijski alat još se učitava. Pokušajte ponovno.'));return}const host=$('#cos120LegacyHost');if(legacyNode&&legacyNode!==target)legacyNode.removeAttribute('data-cos-context');legacyNode=target;target.dataset.cosContext='';host.replaceChildren(target);$('#cos120LegacyTitle').textContent=tool[1];$('#cos120Legacy').hidden=false;target.hidden=false;target.style.removeProperty('display')}
  function closeLegacy(){$('#cos120Legacy').hidden=true}
  document.addEventListener('click',event=>{if(event.target.closest('[data-cos-legacy-close]'))closeLegacy()});
  async function mount(detail){if(!detail?.organization||!document.body.classList.contains('business-page'))return;try{await load()}catch(error){console.error('[Still] CompanyOS failed to load.',error);toast?.(t('CompanyOS could not load authorized company data.','CompanyOS nije mogao učitati ovlaštene podatke tvrtke.'))}}
  window.addEventListener('still:company-authenticated',event=>mount(event.detail));
  if(window.__stillOrganization)mount({organization:window.__stillOrganization});
})();
