(()=>{const $=s=>document.querySelector(s);let currentDeadline=null;
function isoLocal(d){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function resultPayload(){return{m:$('#market').value,t:$('#purchaseType').value,s:$('#store').value,d:$('#purchaseDate').value,i:$('#itemName').value.trim().slice(0,80),v:$('#modifier').value||'',c:$('#store').value==='custom'?$('#customDays').value:''}}
function resultUrl(){const raw=JSON.stringify(resultPayload());const encoded=btoa(unescape(encodeURIComponent(raw))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_');return `${location.origin}${location.pathname}?r=${encoded}`}
function restoreLink(){const r=new URLSearchParams(location.search).get('r');if(!r)return;try{const pad=r.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((r.length+3)%4);const x=JSON.parse(decodeURIComponent(escape(atob(pad))));if(!['us','hr','eu'].includes(x.m)||!/^\d{4}-\d{2}-\d{2}$/.test(x.d||''))return;$('#market').value=x.m;$('#purchaseType').value=x.t==='store'?'store':'online';$('#market').dispatchEvent(new Event('change'));$('#purchaseType').dispatchEvent(new Event('change'));setTimeout(()=>{if([...$('#store').options].some(o=>o.value===x.s)){$('#store').value=x.s;$('#store').dispatchEvent(new Event('change'));if(x.v&&[...$('#modifier').options].some(o=>o.value===x.v))$('#modifier').value=x.v;if(x.c)$('#customDays').value=x.c;$('#purchaseDate').value=x.d;$('#itemName').value=x.i||'';$('#returnForm').requestSubmit()}},0)}catch{}}
const originalShow=window.showResult;if(typeof originalShow==='function')window.showResult=function(p,start,item){originalShow(p,start,item);currentDeadline=p.days?new Date(start.getFullYear(),start.getMonth(),start.getDate()+p.days):null;$('#addReminder').classList.toggle('hidden',!currentDeadline);$('#reminderHelp').classList.toggle('hidden',!currentDeadline)};
$('#addReminder').onclick=()=>{if(!currentDeadline)return;const remind=new Date(currentDeadline);remind.setDate(remind.getDate()-3);if(remind<new Date())remind.setTime(currentDeadline.getTime());const title=`Still? Return deadline · ${$('#resultStore').textContent}`;const description=`${$('#resultTitle').textContent}. ${$('#deadlineText').textContent} Verify retailer policy before acting. ${resultUrl()}`;const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Still Return Checker//EN','BEGIN:VEVENT',`UID:${Date.now()}@still-return`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${isoLocal(remind)}`,`DTEND;VALUE=DATE:${isoLocal(new Date(remind.getFullYear(),remind.getMonth(),remind.getDate()+1))}`,`SUMMARY:${title.replace(/[,;]/g,'\\$&')}`,`DESCRIPTION:${description.replace(/\n/g,'\\n').replace(/[,;]/g,'\\$&')}`,'BEGIN:VALARM','TRIGGER:-PT9H','ACTION:DISPLAY','DESCRIPTION:Return reminder','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='still-return-reminder.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
async function recognize(file){if(!('TextDetector'in window))throw new Error('unsupported');const bitmap=await createImageBitmap(file);const detector=new TextDetector();const blocks=await detector.detect(bitmap);bitmap.close();return blocks.map(b=>b.rawValue).join('\n')}
function infer(text){const lower=text.toLowerCase();const stores=[['ikeahr',['ikea']],['decathlonhr',['decathlon']],['linkshr',['links']],['ekupihr',['ekupi']],['elipsohr',['elipso']],['apple',['apple']],['bestbuy',['best buy']],['target',['target']],['walmart',['walmart']],['costco',['costco']]];let s='';for(const [key,names] of stores)if(names.some(n=>lower.includes(n))){s=key;break}const matches=[...text.matchAll(/\b(20\d{2})[.\/-](0?[1-9]|1[0-2])[.\/-](0?[1-9]|[12]\d|3[01])\b|\b(0?[1-9]|[12]\d|3[01])[.\/-](0?[1-9]|1[0-2])[.\/-](20\d{2})\b/g)];let d='';if(matches.length){const m=matches[0];d=m[1]?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:`${m[6]}-${String(m[5]).padStart(2,'0')}-${String(m[4]).padStart(2,'0')}`}return{s,d}}
$('#scanReceipt').onclick=()=>$('#receiptFile').click();$('#receiptFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const status=$('#scanStatus');status.textContent='Reading receipt on this device…';try{const text=await recognize(file),x=infer(text);if(!x.s&&!x.d){status.textContent='Text was read, but no supported retailer/date was confidently found. Please enter them manually.';return}if(x.s){const hr=x.s.endsWith('hr');$('#market').value=hr?'hr':'us';$('#market').dispatchEvent(new Event('change'));if([...$('#store').options].some(o=>o.value===x.s)){$('#store').value=x.s;$('#store').dispatchEvent(new Event('change'))}}if(x.d)$('#purchaseDate').value=x.d;status.textContent='Receipt suggestions filled. Please confirm the store and date before checking.'}catch(err){status.textContent='On-device receipt text recognition is not available in this browser yet. You can still enter the receipt details manually.'}finally{e.target.value=''}};
document.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',async e=>{if(b.dataset.share==='copy'){e.stopImmediatePropagation();try{await navigator.clipboard.writeText(resultUrl());$('#shareStatus').textContent='Result link copied.'}catch{}}},true));
restoreLink();})();