/* Run with: node smoke-test.js */
const fs=require('fs');
const files=['index.html','app.js','enhancements.js','v10.js','theme.js','styles.css','privacy.html','terms.html','methodology.html'];
const read=f=>fs.readFileSync(f,'utf8');
const fail=[];
for(const f of files){if(!fs.existsSync(f))fail.push(`missing ${f}`);}
if(!fail.length){
 const html=read('index.html'),app=read('app.js'),v10=read('v10.js'),enh=read('enhancements.js'),theme=read('theme.js'),css=read('styles.css');
 const ids=['returnForm','market','purchaseType','store','purchaseDate','itemName','result','language','themeToggle','addReminder','scanReceipt','retailerSearch'];
 ids.forEach(id=>{if(!html.includes(`id="${id}"`))fail.push(`missing DOM id ${id}`)});
 ['value="en"','value="hr"'].forEach(x=>{if(!html.includes(x))fail.push(`missing language option ${x}`)});
 ['warrantyNote','goWarranty','checkReturn'].forEach(k=>{if(!v10.includes(k))fail.push(`missing localization key ${k}`)});
 ['whatsapp','facebook','linkedin','telegram','email','native','copy'].forEach(k=>{if(!enh.includes(k)&&!app.includes(k))fail.push(`missing share route ${k}`)});
 if(!theme.includes('still-theme'))fail.push('theme preference is not persisted');
 if(!css.includes('[data-theme="dark"]'))fail.push('dark theme CSS missing');
 if(!enh.includes('BEGIN:VCALENDAR'))fail.push('calendar reminder generation missing');
 if(!enh.includes('TextDetector'))fail.push('receipt OCR capability detection missing');
 if(!app.includes('eu14'))fail.push('EU withdrawal calculator missing');
 if(!read('privacy.html').includes('Checks and recent history'))fail.push('privacy disclosure missing');
 if(!read('terms.html').includes('Not legal advice'))fail.push('legal disclaimer missing');
 if(!read('methodology.html').includes('Source hierarchy'))fail.push('source methodology missing');
 const buyerAuth=read('buyer-auth-v77.js');
 const authWorker=read('merchant-backend/worker-v79.js');
 const worker=read('merchant-backend/worker-v83.js');
 const commerceWorker=read('merchant-backend/worker-v92.js');
 const lifecycleWorker=read('merchant-backend/worker-v95.js');
 const operationsWorker=read('merchant-backend/worker-v96.js');
 const relationshipWorker=read('merchant-backend/worker-v103.js');
 const contactWorker=read('merchant-backend/worker-v104.js');
 const setupWorker=read('merchant-backend/worker-v105.js');
 const eslWorker=read('merchant-backend/worker-v106.js');
 const operationsHardeningWorker=read('merchant-backend/worker-v107.js');
 const build=read('build-public.js');
 const company=read('company.html');
 if(!buyerAuth.includes('/api/v1/buyer-auth/google/config'))fail.push('buyer Google config does not use isolated auth namespace');
 if(!buyerAuth.includes('/api/v1/buyer-auth/google'))fail.push('buyer Google login does not use isolated auth namespace');
 if(buyerAuth.includes("api('/api/v1/auth/google"))fail.push('buyer auth still calls the shared company auth namespace');
 if(!buyerAuth.includes('Google authenticates only buyer accounts'))fail.push('buyer-only Google scope is not explained');
 if(company.includes('buyer-auth-v77.js'))fail.push('buyer Google authentication is loaded on the company page');
 if(!authWorker.includes("pathname === '/api/v1/buyer-auth/google/config'"))fail.push('worker does not route buyer Google config');
 if(!authWorker.includes("VALUES('GOOGLE_CLIENT_ID'"))fail.push('auth worker does not persist Google Client ID');
 if(!worker.includes("import app from './worker-v79.js'"))fail.push('ownership worker does not delegate to the audited auth router');
 if(!read('wrangler.jsonc').includes('merchant-backend/worker-v107.js'))fail.push('wrangler does not use the Build 107 operations wrapper');
 if(!operationsHardeningWorker.includes("import app from './worker-v106.js'"))fail.push('Build 107 does not delegate to the validated Build 106 base');
 ['platform_audit_events','OPERATIONS_REVIEWER_TOKEN','OPERATIONS_SUPPORT_TOKEN','OPERATIONS_READONLY_TOKEN','/api/v1/admin/audit','request.complete'].forEach(capability=>{if(!operationsHardeningWorker.includes(capability))fail.push(`Build 107 operations capability missing ${capability}`)});
 if(!build.includes('site-quality-v82.js')||!build.includes('site-quality-v82.css'))fail.push('responsive visibility layer missing from production build');
 if(build.includes("'buyer-auth-routes-v79.js'"))fail.push('obsolete global fetch auth shim is still shipped');
 if(!read('_headers').includes('Content-Security-Policy:'))fail.push('content security policy missing');
 if(!read('_headers').includes('same-origin-allow-popups'))fail.push('Google-compatible opener policy missing');
 if(!read('sitemap.xml').includes('/company.html'))fail.push('business workspace missing from sitemap');
 if(!read('site-quality-v82.js').includes('/privacy.html'))fail.push('legal footer navigation missing');
 const companyLoader=read('company-authenticated-loader-v82.js');
 if(!companyLoader.includes("still:company-authenticated"))fail.push('company features are not gated by successful company authentication');
 if(!companyLoader.includes("status !== 'verified'"))fail.push('company operational features are not gated by verified-company status');
 if(!read('company-portal-v46.js').includes("still:company-authenticated"))fail.push('company portal does not release authenticated feature modules');
 if(!build.includes('companyFeatureScripts'))fail.push('company authenticated feature bundle is missing');
 if(!build.includes('ownership-platform-v83.js')||!build.includes('ownership-platform-v83.css'))fail.push('buyer ownership passport bundle is missing');
 if(!build.includes('design-clarity-v84.js')||!build.includes('design-system-v84.css'))fail.push('modern progressive-disclosure design layer is missing');
 if(!build.includes('responsive-readability-v85.css'))fail.push('responsive readability layer is missing');
 if(!build.includes('surface-polish-v86.css'))fail.push('borderless surface polish layer is missing');
 if(!build.includes('refinement-v87.css'))fail.push('final visual refinement layer is missing');
 if(!build.includes('progressive-forms-v88.js')||!build.includes('interaction-clarity-v88.css'))fail.push('progressive form clarity layer is missing');
 if(!build.includes('flow-feedback-v89.js')||!build.includes('flow-feedback-v89.css'))fail.push('action feedback layer is missing');
 if(!build.includes('visual-details-v90.css'))fail.push('visual detail layer is missing');
 if(!build.includes('rewards-visible-v91.css'))fail.push('visible rewards proposition layer is missing');
 if(!build.includes('og-v85.png'))fail.push('responsive social preview artwork is missing from the production bundle');
 if(!build.includes('company-passport-studio-v83.js'))fail.push('verified company passport studio is missing');
 if(!read('company-authenticated-loader-v82.js').includes('company-passport-studio-v83.js'))fail.push('company passport studio is not behind verified authentication');
 if(!worker.includes("'/api/v1/ownership/connect'"))fail.push('buyer-company passport connection route is missing');
 if(!worker.includes("'/api/v1/business/passports'"))fail.push('business passport route is missing');
 if(!read('legal-i18n.js').includes('not a webshop'))fail.push('mediator role is missing from terms disclosure');
 if(!read('legal-i18n.js').includes('private notes'))fail.push('passport privacy disclosure is missing');
 if(!read('ownership-platform-v83.js').includes('Decide before buying'))fail.push('three-task buyer entry point is missing');
 if(!read('buyer-rewards-v76.js').includes('Claim benefit'))fail.push('buyer reward claim action is missing');
 if(!read('buyer-rewards-v76.js').includes('/rewards/offers/'))fail.push('buyer reward claim endpoint is not connected');
 if(!read('company-positioning-v83.js').includes('Earn business credits'))fail.push('company rewards value proposition is missing');
 if(!read('site-quality-v82.js').includes("t('Next dates', 'Rokovi')"))fail.push('compact responsive buyer navigation is missing');
 if(!build.includes('passport-commerce-v92.js')||!build.includes('passport-commerce-v92.css'))fail.push('buyer Passport Commerce bundle is missing');
 if(!build.includes('company-commerce-v92.js')||!build.includes('company-commerce-v92.css'))fail.push('business Passport Commerce bundle is missing');
 if(!read('company-authenticated-loader-v82.js').includes('company-commerce-v92.js'))fail.push('business commerce tools are not verification-gated');
 if(!commerceWorker.includes("'/api/v1/commerce/offers'"))fail.push('public Passport Offer API is missing');
 if(!commerceWorker.includes("'/api/v1/commerce/requests'"))fail.push('buyer request API is missing');
 if(!commerceWorker.includes("'/api/v1/business/commerce/requests'"))fail.push('verified business request board API is missing');
 if(!commerceWorker.includes('acceptQuote'))fail.push('private quote acceptance flow is missing');
 if(!read('passport-commerce-v92.js').includes('Request verified quotes'))fail.push('buyer quote request action is missing');
 if(!read('passport-commerce-v92.js').includes('data-pc92-accept-quote'))fail.push('buyer quote comparison and acceptance UI is missing');
 if(!read('company-commerce-v92.js').includes('data-cc93-quote'))fail.push('company quote response form is missing');
 if(!commerceWorker.includes("'/api/v1/commerce/webhooks/stripe'"))fail.push('verified payment webhook is missing');
 if(!commerceWorker.includes('application_fee_amount'))fail.push('direct seller payment platform fee is missing');
 if(!commerceWorker.includes('activateOrder'))fail.push('payment-to-passport activation is missing');
 if(!commerceWorker.includes('demo_confirmation_required'))fail.push('honest demo checkout guard is missing');
 if(!read('legal-i18n.js').includes('Payment and demonstration mode'))fail.push('commerce payment disclosure is missing');
 const cspHeader=read('_headers')
   .split(/\r?\n/)
   .find(line=>line.trimStart().startsWith('Content-Security-Policy:'));
 const stripeOrigin=cspHeader
   ?.slice(cspHeader.indexOf(':')+1)
   .trim()
   .split(/\s+/)
   .some(source=>{
     try{
       const url=new URL(source);
       return url.protocol==='https:'&&url.hostname==='js.stripe.com'&&url.port==='';
     }catch{
       return false;
     }
   });
 if(!stripeOrigin)fail.push('payment provider CSP is missing');
 if(!build.includes('qrcode-generator-v94.js')||!build.includes('BUNDLE=106'))fail.push('Passport QR generator is missing from Build 106');
 const ownership=read('ownership-platform-v83.js');
 if(!ownership.includes('Passport QR')||!ownership.includes('passportSnapshot'))fail.push('Passport QR buyer interface is missing');
 if(!ownership.includes('/shares')||!ownership.includes('/ownership/verify/'))fail.push('Passport QR verification client routes are missing');
 if(!worker.includes('passport_public_shares')||!worker.includes('verifyPassportShare')||!worker.includes('revokePassportShare'))fail.push('revocable Passport QR server routes are missing');
 if(!read('legal-i18n.js').includes('Passport QR links and portable snapshots'))fail.push('Passport QR privacy disclosure is missing');
 if(!build.includes('lifecycle-platform-v95.js')||!build.includes('lifecycle-platform-v95.css'))fail.push('buyer lifecycle platform is missing from production');
 if(!build.includes('company-lifecycle-v95.js')||!build.includes('company-lifecycle-v95.css'))fail.push('company lifecycle workspace is missing from production');
 if(!read('company-authenticated-loader-v82.js').includes('company-lifecycle-v95.js'))fail.push('company lifecycle workspace is not verification-gated');
 ['lifecycle_preferences','promise_templates','passport_service_events','passport_alerts','passport_threads','passport_messages','business_assets'].forEach(table=>{if(!lifecycleWorker.includes(table))fail.push(`lifecycle schema missing ${table}`)});
 ['/api/v1/lifecycle/dashboard','/api/v1/lifecycle/actions','/history','/support','/templates','/alerts','/assets'].forEach(route=>{if(!lifecycleWorker.includes(route))fail.push(`lifecycle route missing ${route}`)});
 if(!read('lifecycle-platform-v95.js').includes('Calculate true cost')||!read('lifecycle-platform-v95.js').includes('REPAIR READINESS'))fail.push('total cost and repairability tool is missing');
 if(!read('company-lifecycle-v95.js').includes('Outcome reputation')||!read('company-lifecycle-v95.js').includes('B2B PASSPORT'))fail.push('company reputation or B2B passport UI is missing');
 if(!build.includes('company-operations-v96.js')||!build.includes('company-operations-v96.css'))fail.push('company operations workspace is missing from production');
 if(!read('company-authenticated-loader-v82.js').includes('company-operations-v96.js'))fail.push('company operations are not verification-gated');
 ['ops_products','ops_stock_movements','ops_purchase_orders','ops_repair_jobs','ops_rmas','ops_reservations','ops_agreements','ops_appointments','ops_crm_contacts','ops_quotes','ops_recall_campaigns','ops_audit_log'].forEach(table=>{if(!operationsWorker.includes(table))fail.push(`operations schema missing ${table}`)});
 ['/api/v1/business/ops/dashboard','/stock/adjust','/purchase-orders','/repairs','/returns','/reservations','/agreements','/appointments','/quotes','/recalls'].forEach(route=>{if(!operationsWorker.includes(route))fail.push(`operations route missing ${route}`)});
 if(!read('company-operations-v96.js').includes('Automatic reorder queue')||!read('company-operations-v96.js').includes('Batch and serial recall center'))fail.push('operations UI is missing reorder or recall workflows');
 if(!build.includes('company-preview-v97.js')||!build.includes('company-preview-v97.css'))fail.push('pre-verification company preview is missing from production');
 if(!read('company-preview-v97.js').includes('Your password was not checked')||!read('company-preview-v97.js').includes('Nothing is saved'))fail.push('company login capacity feedback or safe preview disclosure is missing');
 if(!read('company-preview-v97.js').includes('event.stopImmediatePropagation()')||!read('company-preview-v97.js').includes("form.id!=='cp46Login'"))fail.push('company login does not reliably replace the legacy submit handler');
 if(!read('company-preview-v97.js').includes("id:'inventory'")||!read('company-preview-v97.js').includes("id:'analytics'")||!read('company-preview-v97.js').includes('Temporary interactive workspace'))fail.push('company preview does not expose all detailed interactive product-tour workspaces');
 if(!read('company-preview-v97.js').includes('Problem solved')||!read('company-preview-v97.js').includes('Buyer gains')||!read('company-preview-v97.js').includes('Business gains'))fail.push('company preview is missing decision-making value explanations');
 ['passports','commerce','services','lifecycle','inbox','rewards','branches','verification','integrations','dailyops','deliverycontrol','capacity','customer360','automation','supplierclaims','notifications','b2bassets'].forEach(module=>{if(!read('company-preview-v97.js').includes(`id:'${module}'`))fail.push(`complete company tour is missing ${module}`)});
 if((read('company-preview-v97.js').match(/number:'\d{2}'/g)||[]).length!==29)fail.push('complete company tour does not contain exactly 29 modules');
 if(!read('company-preview-v97.js').includes('PARTIALLY CONNECTED')||!read('company-preview-v97.js').includes('EXTERNAL CONNECTIONS MISSING'))fail.push('company tour does not disclose partial or missing integrations');
 if(!read('company-authenticated-loader-v82.js').includes('?v=106'))fail.push('authenticated company features are not cache-aligned with Build 106');
 if(!build.includes('company-control-center-v101.js')||!build.includes('company-control-center-v101.css'))fail.push('advanced verified-company control center is missing from production');
 if(!read('company-authenticated-loader-v82.js').includes('company-control-center-v101.js'))fail.push('advanced company controls are not verification-gated');
 const controlCenter=read('company-control-center-v101.js');
 ['/milestones','/changes','/completion-events','/evidence-requirements','/ops/capacity','/customers/','/ops/playbooks','/followup-rules','/supplier-claims'].forEach(route=>{if(!controlCenter.includes(route))fail.push(`advanced company control center is missing ${route}`)});
 if(!build.includes('company-demo-v102.js')||!build.includes('company-demo-v102.css'))fail.push('interactive company demo workspace is missing from production');
 const demo=read('company-demo-v102.js');
 ['sessionStorage','visibleRows','openAction','data-cpv102-form','exportCSV','data-cpv102-step','data-cpv102-undo','data-cpv102-reset-all'].forEach(capability=>{if(!demo.includes(capability))fail.push(`interactive company demo is missing ${capability}`)});
 if(!read('company-preview-v97.js').includes('Temporary interactive workspace')||!read('company-preview-v97.js').includes('data-cpv97-row'))fail.push('all company tour modules are not connected to the interactive demo workspace');
 if(!build.includes('relationship-dashboard-v103.js')||!build.includes('relationship-dashboard-v103.css'))fail.push('buyer and company relationship dashboards are missing from production');
 if(!relationshipWorker.includes('PROFILE_MEDIA')||!relationshipWorker.includes('profileMediaUploads'))fail.push('protected profile-media capability detection is missing');
 ['/api/v1/buyer-profile','/api/v1/business-profile','/api/v1/buyer-dashboard','/api/v1/business-dashboard','/api/v1/profile-media/'].forEach(route=>{if(!relationshipWorker.includes(route))fail.push(`relationship identity API is missing ${route}`)});
 if(!relationshipWorker.includes('share_with_connected_businesses')||!relationshipWorker.includes('buyerRelatedToCompany'))fail.push('buyer profile visibility is not relationship-gated');
 if(!relationshipWorker.includes("hasLogo=Object.prototype.hasOwnProperty.call(body,'logoUrl')"))fail.push('company profile lacks a production logo URL fallback');
 if(!relationshipWorker.includes('/api/v1/profile-media/company-logo/')||!relationshipWorker.includes('safeLogoUrl'))fail.push('remote company logos are not privacy-proxied and SSRF-filtered');
 if(!read('ownership-platform-v83.js').includes("qrcode(0, 'H')")||!read('ownership-platform-v83.js').includes('op103-qr-brand'))fail.push('branded high-resilience Passport QR rendering is missing');
 if(!read('company-passport-studio-v83.js').includes('buyerProfile'))fail.push('company passport studio does not show connected buyer profiles');
 if(!build.includes('contact-profile-v104.js')||!build.includes('brand-alignment-v104.css'))fail.push('contact profiles or brand-aligned dashboard styles are missing from production');
 ['buyer_contact_profiles','organization_contact_profiles','commerce_order_parties','contact_required','buyer_json','seller_json'].forEach(capability=>{if(!contactWorker.includes(capability))fail.push(`complete order-party contact layer is missing ${capability}`)});
 if(!read('passport-commerce-v92.js').includes('checkoutContactFields')||!read('passport-commerce-v92.js').includes('buyerName'))fail.push('buyer checkout does not collect fulfilment contact details');
 if(!read('company-commerce-v92.js').includes('decorateOrderContacts'))fail.push('company orders do not show immutable buyer contact snapshots');
 if(!build.includes('company-available-tools-v105.js')||!build.includes('company-available-tools-v105.css'))fail.push('authenticated pre-verification company workspace is missing from production');
 ['organization_setup_profiles','/api/v1/business/setup','organization_status','sameOrigin','owner','manager'].forEach(capability=>{if(!setupWorker.includes(capability))fail.push(`pre-verification setup API is missing ${capability}`)});
 const availableTools=read('company-available-tools-v105.js');
 ['companyAvailableToolsV105','companyControlCenterV101','companyToolsPreviewV97','cp46-verify','29 modules','/api/v1/business/setup'].forEach(capability=>{if(!availableTools.includes(capability))fail.push(`pre-verification company workspace is missing ${capability}`)});
 if(!availableTools.includes('rewirePendingLinks')||!availableTools.includes('MutationObserver'))fail.push('pending-company tools CTA is not repaired after dashboard rerenders');
 if(!read('company-authenticated-loader-v82.js').includes("status !== 'verified'"))fail.push('live company operations were accidentally opened before verification');
 if(!read('legal-i18n.js').includes('Pre-verification company setup'))fail.push('pre-verification setup privacy disclosure is missing');
 if(!build.includes('electronic-shelf-labels-v106.js')||!build.includes('electronic-shelf-labels-v106.css'))fail.push('electronic shelf-label studio is missing from production');
 ['esl_connectors','esl_labels','esl_price_updates','/api/v1/business/esl','verification_required','bluetoothEslProfile','adapterPayload'].forEach(capability=>{if(!eslWorker.includes(capability))fail.push(`electronic shelf-label API is missing ${capability}`)});
 const eslStudio=read('electronic-shelf-labels-v106.js');
 ['1.54','2.13','2.90','4.20','5.80','7.50','10.20','lcd_wide','custom','widthMm','widthPx','Bluetooth ESL Profile 1.0','GS1 Digital Link','exportSvg','exportPng','exportJson','exportCsv','sessionStorage'].forEach(capability=>{if(!eslStudio.includes(capability))fail.push(`electronic shelf-label studio is missing ${capability}`)});
 if(!eslStudio.includes('vendor adapter required')||!eslWorker.includes('vendor_credentials_and_gateway_required'))fail.push('electronic shelf-label vendor boundary is not disclosed');
 if(!read('legal-i18n.js').includes('Electronic shelf labels and price updates'))fail.push('electronic shelf-label privacy disclosure is missing');
 if(!read('legal-i18n.js').includes('Lifecycle history, alerts and support'))fail.push('lifecycle privacy disclosure is missing');
}
if(fail.length){console.error('Still? smoke tests FAILED\n- '+fail.join('\n- '));process.exit(1)}
console.log('Still? smoke tests passed');
